### ISSUE TITLE
Help wanted: how to set a task to 'done'?

### ISSUE THREAD

**Issue by timkley** [awork-io/awork#10]
Hi awork 👋

We are currently trying to implement a way to complete a project task via the api.

What is the best way to achieve this? I understood that every project has it's own task statuses, therefore it is not possible to just store the done-id as a `const` somewhere, right?

Using `/project/entityId` as endpoint I don't get the statuses of a task. I found the (undocumented?) endpoint `/project/entityId/tasktstatuses` which gives me all statuses.

I'd try the following, would be great to hear if I missed some "shortcut"

1. Get all task statuses with `/project/entityId/taskstatuses`
2. Filter them by type `done` (for simplicity I'll assume we only have one per type or just use the first one)
3. Update the task with `/tasks/entityId/`

Thanks in advance :)

**Comment by nilzzzzzz** [comment]
Hi @timkley,

thanks for reaching out. 
Yes you need 3 steps.
1. Get statuses: https://developers.awork.io/#/ProjectTasks/get_projects__projectId__taskstatuses
2. Filter them by type done
3. https://developers.awork.io/#/Tasks/post_tasks_changestatuses

For me the 1. endpoint is also documented. Am i missing something?

Best

Nils

**Comment by timkley** [comment]
Hi Nils,

thanks for your answer!

Yeah, I can see the endpoint now (altough the deeplink isn't working for me?), it just wasn't the most intuitive way to find it because you have to select Tasks -> ProjectTasks to get to it when I would've expected the documentation under "Projects".

Thank you for the last endpoint, that helps a lot 👍

Cheers!

**Comment by nilzzzzzz** [comment]
@timkley yeah, we will have new docs on monday, we are also unhappy with that ;)
