### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by tahirbilal1** [awork-io/awork#100]
### What is your question?

Why it is giving me html instead of all task statuses whenever I get all taskstatuses of a sepcific project?

**Comment by nilzzzzzz** [comment]
@tahirbilal1 can you please provide a trace id (you get it from the response headers..) or at least an url you are calling?

**Comment by tahirbilal1** [comment]
var settings = {
                    "url": "https://api.awork.io/api/v1/5815b1ca-f57d-4379-81f2-3f77cc243a86/taskstatuses",
                    "method": "GET",
                    "timeout": 0,
                    "headers": {
                        "Content-Type": "application/json ",

                        "Authorization": "Bearer " + window.localStorage.getItem("access_token")
                    },
                };
                $.ajax(settings).done(function (response) {

                    console.log(response);
                  

                });

**Comment by nilzzzzzz** [comment]
@tahirbilal1 url is wrong. `https://api.awork.io/api/v1/5815b1ca-f57d-4379-81f2-3f77cc243a86/taskstatuses` needs to be `https://api.awork.io/api/v1/projects/5815b1ca-f57d-4379-81f2-3f77cc243a86/taskstatuses`
