### ISSUE TITLE
Upload files to task

### ISSUE THREAD

**Issue by tahirbilal1** [awork-io/awork#101]
### What is your question?

![image](https://user-images.githubusercontent.com/127947363/225422237-8371b1b3-da06-4126-b647-b7e9e1f271d9.png)
This is giving error of missing content type boundary,  please guide me, I want to upload attachment from email outlook body

**Comment by nilzzzzzz** [comment]
Should be something like this:

'$.ajax({
  url: 'your_upload_url',
  type: 'POST',
  data: formData,
  contentType: false,
  processData: false,
  beforeSend: function(xhr) {
    xhr.setRequestHeader('Content-Type', 'multipart/form-data; boundary=----WebKitFormBoundary' + new Date().getTime());
  },
  success: function(data) {
    // handle success response
  },
  error: function(xhr, status, error) {
    // handle error response
  }
});'

**Comment by tahirbilal1** [comment]
Can I upload base64 of the file?
