### ISSUE TITLE
Add file in task via api with base64 of a file

### ISSUE THREAD

**Issue by tahirbilal1** [awork-io/awork#103]
### What is your question?

How can I upload a file in a specific task with api when I have base64 of the file?

**Comment by nilzzzzzz** [comment]
The question is not really awork related but this should help you:

https://developer.mozilla.org/en-US/docs/Web/API/btoa

**Comment by tahirbilal1** [comment]
My question is that how to upload file with it base64 to task files? instead of form data

**Comment by nilzzzzzz** [comment]
The format does not matter for us. You can use any format to upload your files, but always needs to be send as form data..

**Comment by themaan** [comment]
How can I upload file when i have its base64, can you give me sample ajax?

**Comment by tahirbilal1** [comment]
I am uploading by appending thae binary of a file in form data, file is
uploading but when I download it becomes unreachable or unspoorted

**Comment by sebastianrosch** [comment]
Hi @tahirbilal1 can you please provide the trace id from the response header so we can investigate this? Thanks
