### ISSUE TITLE
File is uploading correct but not being downloadable

### ISSUE THREAD

**Issue by themaan** [awork-io/awork#106]
### What is your question?

![image](https://user-images.githubusercontent.com/51510378/225589165-46095018-dda2-4327-a5a9-808ee468ae71.png)
With this code the file is being uploaded to files, but when i want to see or download it gives unspoorted  media

**Comment by sebastianrosch** [comment]
Hi @themaan can you please provide us with the trace id from the response header so we can investigate this? Thanks

**Comment by themaan** [comment]
a534fecbdc352d38b68c90bf34b0ab26
