### ISSUE TITLE
 I am uploading file to files for task, it is giving success but the uploaded file can not be opened after downloading

### ISSUE THREAD

**Issue by Usman1104** [awork-io/awork#108]
### What is your question?

 am uploading file to files for task, it is giving success but the uploaded file can not be opened after downloading

**Comment by nilzzzzzz** [comment]
Hi @Usman1104 
i just tried it and it works. Here an example:

`var client = new RestClient("https://api.awork.io/api/v1/tasks/{taskId}/files");
client.Timeout = -1;
var request = new RestRequest(Method.POST);
request.AddHeader("Authorization", "Bearer TOKEN");
request.AddFile("testdatei.txt", "/Users/Nils/Desktop/all_pans.txt");
request.AddParameter("name", "test2.txt");
IRestResponse response = client.Execute(request);
Console.WriteLine(response.Content);`

Postman Settings as an example attached.
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/22219385/225714179-fb6c6c6d-7253-4fbf-a0a1-88814b0c550a.png">

**Comment by Usman1104** [comment]
But for me it is not working both on postman and ajax
Please provide sample for javscript ajax

**Comment by sebastianrosch** [comment]
Hi @Usman1104 unfortunately we cannot provide samples in Ajax. If the call is failing or not working as expected, please provide us with the trace id from the response header. Thanks

**Comment by Usman1104** [comment]
The call is not failing at all, it is uploading the file with 200 but that
file can not be opened

**Comment by themaan** [comment]
a534fecbdc352d38b68c90bf34b0ab26 this is the trace id
