### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by Usman1104** [awork-io/awork#109]
### What is your question?

Please show me ajax code for jquerry in postman as my file is not being uploaded to files apis.
Also I am appending binary data of file in formdata after getting binary from base64

**Comment by sebastianrosch** [comment]
Hi @Usman1104 we unfortunately cannot provide Ajax examples as we use different technologies at awork. Please consult with an Ajax community or online resource for the requested samples.

**Comment by Usman1104** [comment]
a534fecbdc352d38b68c90bf34b0ab26 this is the trace id, I am uploading, it is giving 200 but file is not valid in awork portal after downloading

**Comment by nilzzzzzz** [comment]
Can you please this code? This works for me w/o problem.
```
var form = new FormData();
form.append("testdatei.txt", fileInput.files[0], "all_pans.txt");
form.append("name", "test2.txt");

var settings = {
  "url": "https://api.awork.io/api/v1/tasks/{taskId}/files",
  "method": "POST",
  "timeout": 0,
  "headers": {
    "Authorization": "Bearer {Token}"
  },
  "processData": false,
  "mimeType": "multipart/form-data",
  "contentType": false,
  "data": form
};

$.ajax(settings).done(function (response) {
  console.log(response);
});
```

**Comment by Usman1104** [comment]
I am using this same code and I am appending blob type in formdata and then
sending to api it gives success but file becomes invalid after uploading

**Comment by nilzzzzzz** [comment]
For me it works. What do you mean file is invalid. We do not modify the file, we upload it directly and then you download it again. We have no code which modifies the file itself. Perhaps you upload base64 files and that is the reason you cannot read it after downloading?

**Comment by Usman1104** [comment]
I tried on postman too but same thing happens
However I do not have real file as I am getting from email body and I can
get only base64 of the file

**Comment by Usman1104** [comment]
Or just guide me how can I save that file into files when I am getting the
base64 from outlook and I am converting it into blob for formdata

**Comment by nilzzzzzz** [comment]
So you upload a base64 file, and then you download it and it is still a base 64 file. Thats expected.. so where is the issue?

**Comment by Usman1104** [comment]
how can I avoid this? I want to upload outlook attachments as it is

**Comment by nilzzzzzz** [comment]
Where do you get the attachments from?

**Comment by Usman1104** [comment]
Also why it is doing same thing on postman where I select the file from my local system

**Comment by Usman1104** [comment]
I get attachments in email from any user, and I want to store those attachments in my tasks, and outlook is providing base64 using office js api

**Comment by nilzzzzzz** [comment]
have you tried the exact same thing like i did in my postman screenshot? did you provide also a correct file name with a file extension like i did?

**Comment by nilzzzzzz** [comment]
you need do base 64 decode them and then upload

**Comment by Usman1104** [comment]
base64 decode to which format? I am decoding it in binary and then blob

**Comment by Usman1104** [comment]
Do i need to decode it in file?

**Comment by Usman1104** [comment]
I jave tried everything and also Chatgpt that's why I am asking, but thank
you for your time and patience , I will try this
