### ISSUE TITLE
[Bug]: API client removes assignees from tasks overnight

### ISSUE THREAD

**Issue by lsellem** [awork-io/awork#110]
### What happened?

I regularly receive emails around midnight CET informing me that our API client has removed me as assignee from a task. We are using EvidentIQ solely to create the awork project and export the logged time from awork. All project management is taking place in awork. This is problematic as it increases the risk of tasks going under the radar and missing deadlines. Can you please help us understand why the API client would behave this way?

![image](https://user-images.githubusercontent.com/130036465/230301034-eb740937-d1f6-4a0e-92e4-d2beef69f74a.png)

### What is the trace id of the call?

N/A

### Relevant error responses

```shell
N/A
```

**Comment by sebastianrosch** [comment]
Hi @lsellem, is this the awork-HQ integration that you're using? This integration is maintained by HQ, but I will reach out to them to see if they can help. We would need the trace id to investigate further.

**Comment by sebastianrosch** [comment]
In the meantime, could you provide me with the subdomain of your awork workspace, name of a project and task or ideally the URL to the task where this is happening? You can also send this to support@awork.io and mention this conversation.

**Comment by lsellem** [comment]
Hi @sebastianrosch thanks for your prompt reply. Our team has contacted HQ back in November but they advised us to fill in a bug report here. The problem has come up on several task, but here's the link to the most recent one: https://ghostwhite-brilliant-virtuosos.awork.io/tasks/b0119ab1-6857-444b-9d12-67d63762e7e9/details 

Thanks!

**Comment by nilzzzzzz** [comment]
Hi @lsellem ,

i double checked what happened to the task you gave us as an example.
At `April 6 2023, 00:08:28.232` a call was made to our API Endpoint `SetAssignees` with a different `Assignee` than assigned before. 
The call was made by an external API-Client which is not maintained by us. The `Client-Id` was `evidentiq-awork-hq`. So we have no influence on external clients using our API. For me it looks like this is an API Client used by the HQ. But could also be any other external integration.

So your options are: 
* Talk to the HQ, ask if they use this client-id
* Delete the client-id (then the api client cannot make those calls anymore, but potentially you break your integration).

Best

Nils

**Comment by lsellem** [comment]
Hi @nilzzzzzz, thanks for your help with this. I'll forward the info to the HQ and hopefully they'll be able to sort it out. 

Best wishes,
Laury
