### ISSUE TITLE
AccountId for POST /users on API

### ISSUE THREAD

**Issue by nebal9** [awork-io/awork#111]
### What is your question?

Hello,
I'm trying to create a new user through the API.

I'm making a POST to /users
But the request body should has an "accountId" which can't be null!
My question is where can I get it's value from?

I checked in the settings but couldn't find any accountId.
Thank you!

### Do you have a trace id of the call?

POST to /users

**Comment by sebastianrosch** [comment]
HI @nebal9 you have to invite users to the workspace using the `POST /invitations` endpoint.
