### ISSUE TITLE
[Question]: how can i add new tasks to a private project?

### ISSUE THREAD

**Issue by c0dingc0d3r** [awork-io/awork#112]
### What is your question?

I tried to add a new task to a private project via the POST /tasks route and a global api key. However i got a 401 response. How is it actually possible to add new tasks to a private project?

### Do you have a trace id of the call?

9ba9afe473ff92483c1bb1e625d4546e

**Comment by sebastianrosch** [comment]
HI @c0dingc0d3r, the project you are trying to access was created by a different user and is private. Only the project creator can access the project. To access this project via API, you need to create an API token as this user and access the project with this token.

I hope this helps,
Sebastian

**Comment by c0dingc0d3r** [comment]
ok is there any way to access this priavte project with an global admin api token or sth like that? Or is it just possible with the creators api token.

**Comment by sebastianrosch** [comment]
It's only possible for the creator.

**Comment by c0dingc0d3r** [comment]
thank u that helped a lot
