### ISSUE TITLE
Filter auf ein Mehrdimensionales Array, z.B. users --> status --> isDeactivated

### ISSUE THREAD

**Issue by TSchaefer78** [awork-io/awork#115]
### What is your question?

Hallo liebe Entwickler,

benötige noch eine Info!
Wie filtert man ein Mehrdimensionales Array, quasi eine Ebene tiefer.
Ich kann in der Doku nichts darüber finden.

Beispiel: isDeactivated in status zum user?

user
[
    {
    "firstName": "string",
    "lastName": "string",
    "status": { 
        "invitationAccepted": true,
        "isDeactivated": true <-------------------------------
     },

freundliche Grüße
Tom Schäfer

**Comment by TSchaefer78** [comment]
hier mal ein Versuch:

const response = await axiosAwork.get(`/timeentries/task?filterby=id eq guid'f826491d-a8ac-45ed-85f0-cccf52c379c5')`, {})

trace-id: '25e3b78e35a56a5f8969a00d7480a25a'

Fehlermeldung:
        
GET https://api.awork.io/api/v1/timeentries/task?filterby=id%20eq%20guid%27f826491d-a8ac-45ed-85f0-cccf52c379c5%27) 404 (Not Found)

**Comment by nilzzzzzz** [comment]
hi @TSchaefer78 `/timeentries/task?filterby=id eq guid'f826491d-a8ac-45ed-85f0-cccf52c379c5'` ist nicht korrekt leider.
Es gibt keinen Endpoints `timeentries/task`. Du kannst alle endpoints hier finden: https://openapi.awork.io/

Wenn du timeentries nach task filtern möchtest, müsstest du folgendes tun: `timeentries?filterby=task/id eq guid'f826491d-a8ac-45ed-85f0-cccf52c379c5'

Für deine erste Frage: hier sind die Filter beschrieben -> https://developers.awork.io/filtering
Filter für den user wäre: `?filterby=status/isDeactivated eq true`

Hilft dies?

**Comment by TSchaefer78** [comment]
Besten Dank! :)

**Comment by TSchaefer78** [comment]
geht denn auch eine UND / ODER Verknüpfung?
Wie z.B.

axiosAwork.get(`/timeentries?filterby=projectId eq guid'f12177b5-2d94-4fc1-bb36-fcc4484f1878'  && ?filterby=user/id eq guid'72bf19be-037c-eb11-a607-00155d314496')`, {}) // timeentries.user.id
