### ISSUE TITLE
filterby UND/ODER Verknüpfung

### ISSUE THREAD

**Issue by TSchaefer78** [awork-io/awork#116]
### What is your question?

Hallo,
geht denn auch eine UND / ODER Verknüpfung?
Wie z.B.

axiosAwork.get(/timeentries?filterby=projectId eq guid'f12177b5-2d94-4fc1-bb36-fcc4484f1878'  && ?filterby=user/id eq guid'72bf19be-037c-eb11-a607-00155d314496'), {})

Danke im Voraus,
Tom Schäfer

**Comment by TSchaefer78** [comment]
Leider nein, da ich ein response bekomme leider wird der zweite Filter anscheinend ignoriert.

/timeentries?filterby=projectId eq guid'f12177b5-2d94-4fc1-bb36-fcc4484f1878'&&?filterby=user/id eq guid'72bf19be-037c-eb11-a607-00155d314496'

**Comment by TSchaefer78** [comment]
trace-id: '5c1be2136a122c954187d8e8cf2c03bb'

**Comment by nilzzzzzz** [comment]
And geht, it's auch auf der Filter Seite beschrieben mit and anstatt &&

**Comment by TSchaefer78** [comment]
bekomme nur Fehlermeldungen bei AND

/timeentries?filterby=projectId eq guid'f12177b5-2d94-4fc1-bb36-fcc4484f1878' and filterby=user/id eq guid'72bf19be-037c-eb11-a607-00155d314496'

trace-id: '4cc48349472fc453742b6199da52a15d'

**Comment by TSchaefer78** [comment]
PS:

habe es hinbekommen ohne nochmaligen filterby :)
