### ISSUE TITLE
API fetch auf typeofwork liefert Fehler 404 Not Found

### ISSUE THREAD

**Issue by TSchaefer78** [awork-io/awork#117]
### What is your question?

Hallo,

bei dem Versuch die TypeOfWork abzurufen bekomme ich den Fehler 404.

const response = await axiosAwork.get(`/typeofwork)`, {})

### Do you have a trace id of the call?

trace-id: 'c2274217b1c0669b4a814030412456d3'

**Comment by nilzzzzzz** [comment]
@TSchaefer78 can you remove the slash at the end? 
<img width="299" alt="image" src="https://github.com/awork-io/awork/assets/22219385/15cfb0df-9ad2-4c53-8c1f-fb6242a572de">

In the trace there is an additional slash.

**Comment by TSchaefer78** [comment]
hat sich erledigt, war eine Klammer zu viel
