### ISSUE TITLE
Wie kommt man an die Aufgaben zu einem Projekt ran?

### ISSUE THREAD

**Issue by TSchaefer78** [awork-io/awork#118]
### What is your question?

Wie kommt man an die Aufgaben zu einem Projekt ran?

z.B. Projekt-id:
085438be-cf95-4158-b2ca-2bb346295dbc

**Comment by nilzzzzzz** [comment]
Hi @TSchaefer78 du kennst unsere docs oder? 
https://openapi.awork.io/#/ProjectTasks/get_projects__projectId__projecttasks
