### ISSUE TITLE
[Question]: Kunden (Company) Daten aktualsieren

### ISSUE THREAD

**Issue by sebastiantheobald** [awork-io/awork#119]
### What is your question?

Hey, 
ich möchte neben den Feldern
name,
description,
und industry

auch weitere Felder pflegen, bzw. aktualisieren. 
In meinem konkreten Fall möchte ich ein benutzerdefiniertes Label hinzufügen und dort einen Wert schreiben. 

Ich nutze make.com - in der Make Integration ist das nicht möglich, ich hatte gehofft die API nutzen zu können - aber auch hier nur diese drei Werte. 

Zudem stellt sich mir die Frage was "description" ist - in awork kann ich diesen Wert nirgends einsehen.

**Comment by sebastianrosch** [comment]
Moin @sebastiantheobald, du kannst mit `POST /companies/{companyId}/addtags` nutzerdefinierte labels hinzufügen. Diese werden auch in awork angezeigt. Die description nutzen wir aktuell nicht.

Mehr dazu findest du hier in der Doku: https://openapi.awork.io/#/CompanyTags/post_companies__companyId__addtags

**Comment by sebastiantheobald** [comment]
> Moin @sebastiantheobald, du kannst mit `POST /companies/{companyId}/addtags` nutzerdefinierte labels hinzufügen. Diese werden auch in awork angezeigt. Die description nutzen wir aktuell nicht.
> 
> Mehr dazu findest du hier in der Doku: https://openapi.awork.io/#/CompanyTags/post_companies__companyId__addtags

Hey @sebastianrosch danke für die super schnelle Antwort! 
Ich möchte die Lexoffice Kontakt ID des Kunden hinterlegen. Das sähe in einem Badge glaube ich etwas unschön aus. Daher wollte ich das verstecken hier: 
![image](https://github.com/awork-io/awork/assets/23461821/bbc4701c-c64f-43db-bc1a-2fdbbacf2cd0)

Siehst du hierfür eine Möglichkeit?

**Comment by sebastianrosch** [comment]
Das geht über ContactInfos: https://openapi.awork.io/#/Companies/post_companies__companyId__contactinfo Da musst du am besten mal eins im UI anlegen und dann über die API holen damit du siehst wie das dann erstellt werden muss.
