### ISSUE TITLE
API: How can i read comments or activities from a task?

### ISSUE THREAD

**Issue by pmarkus84** [awork-io/awork#12]
Your documentation describes the comments or activities can be read with "/entityName/entityId/comments". I don´t know where i can find the "entityName". The debugger only shows the "entityId".

![grafik](https://user-images.githubusercontent.com/29916438/125782561-21c69edb-b52d-4716-8d4c-b1d0d6aa9b81.png)

**Code** (from Google-Sheet):
![grafik](https://user-images.githubusercontent.com/29916438/125782783-49378e0b-89a1-47d2-8cc1-152bae6b2b0c.png)

Thanks in advance.

**Comment by nilzzzzzz** [comment]
@pmarkus84 sure, its 'tasks' or 'projects'
/api/v1/tasks/{taskId}/comments

Best

Nils

**Comment by pmarkus84** [comment]
@nilzzzzzz Thanks for the fast answer. It works. 😎

BR 
Markus
