### ISSUE TITLE
[Bug]: timeentries-Anfrage liefert unterschiedliche Anzahl an Ergebnissen pro Seite

### ISSUE THREAD

**Issue by MircoKoenig** [awork-io/awork#120]
### What happened?

Seit ein paar Tagen taucht das Problem auf, dass bei den timeentries-Anfragen vorkommt, dass es mehr als 1000 Treffer gibt, aber auf den einzeln Seiten nicht die maximale Anzahl von 1000 erreicht, selbst wenn man zusätzlich den entsprechenden Parameter setzt. 

Beispiel:
Ich erhalte 6100 Ergebnisse insgesamt, auf der ersten Seite tauchen aber nur 998 Treffer auf. 

### What is the trace id of the call?

https://api.awork.io/api/v1/projects/{projectId}/timeentries?filterby=Project%2FProjectStatus%2FType+eq+%27closed%27+and+Project%2FProjectType%2Fid+eq+guid%{ProjecttypeId}%27+and+startDateLocal+ge+datetime%272022-10-01T00%3A00%27&orderby=Project%2FName+asc&page=1

**Comment by MircoKoenig** [comment]
Hi @nilzzzzzz 
c1d1b7e1fb86c8e3c329b017279f4f34

bei der Anfrage mit der trace Id taucht der Fehler auf.

**Comment by nilzzzzzz** [comment]
Hallo @MircoKoenig ,

wir konnten das Verhalte nachstellen und arbeiten an einer Lösung. ETA ist bis spätestens Dienstag. Das Problem tritt auf bei TimeEntries bei denen der User gelöscht wurde und wir müssen eine Anpassung an der Datenbankstruktur machen, daher braucht der Fix etwas. Danke fürs melden!

Grüße

Nils

**Comment by nilzzzzzz** [comment]
Hi @MircoKoenig ,

der Fehler ist behoben. 

Viele Grüße

Nils
