### ISSUE TITLE
[Question]: Mehrere Tasks mit einer Anfrage erhalten

### ISSUE THREAD

**Issue by MircoKoenig** [awork-io/awork#121]
### What is your question?

Hallo,

Eine Aufgabe, die ich bisher über die Schnittstelle bewältigt habe, war es, zu ermitteln, wieviel Zeit ein Mitarbeiter pro Monat an einem bestimmten Tag (z.B. Social Media) innerhalb eines Projektes gearbeitet hat. Dies konnte ich ich bisher über das Feld task.tags innerhalb der Timeentry-Anfrage bewerkstelligen.
Dieses Feld ist aber seit kurzem nicht mehr vorhanden und wenn ich durch jede Aufgabe gehen muss, um die Tags der entsprechenden Tasks zu erhalten, lande ich schnell bei über 100 Anfragen für einen Monat alleine.

Meine Frage ist nun: Gibt es die Möglichkeit bei der Task-Request mehrere IDs anzugeben (ähnlich wie IN(..., ...) bei SQL) ?

**Comment by nilzzzzzz** [comment]
Hallo @MircoKoenig ,

wir mussten das Feld aus dem Json Model aus Performancegründen entfernen. Du kannst aber nach wie vor danach filtern, ich denke dies ist für dich der einfachste weg:

`https://api.awork.io/api/v1/timeentries?filterby=task/tags/any(a: a/name eq 'NameOfTag')`

Hilft dir das weiter?

Grüße

Nils

**Comment by MircoKoenig** [comment]
Das hat viel geholfen. Vielen Dank für die schnelle Antwort
