### ISSUE TITLE
[Question]: When is an appointment an absence?

### ISSUE THREAD

**Issue by eXahostCOM** [awork-io/awork#124]
### What is your question?

We maintain our employees' absences in the Absence.io tool, which are synchronized with Microsoft Calendar. This in turn is synchronized with Awork. Thus, our absences are available as appointments in Awork. For one of our employees, these appointments are also stored as real absences in Awork, but for all others only as appointments. What could be the reason for this? How does Awork determine whether an appointment is an absence? How do we ensure that these appointments are always recognized as absences?

**Comment by nilzzzzzz** [comment]
Hi @eXahostCOM,

absences can only be created by the ui or from our personio integration. Calendar Appointments are no absences for us. Could you give us an example for an absence so we check how it was created?

Best

Nils
