### ISSUE TITLE
Update von project and project-statuses via API werden manchmal  Safari nicht aktualisiert

### ISSUE THREAD

**Issue by wwdto** [awork-io/awork#126]
### What happened?

Jobs und Jons-Stati werden vie API aktualsiert.

project_id: 
 facec1d8-5568-4553-bf4d-3f369b374214

Stati: 
1b634cc1-9b3b-49b8-b14b-f36e093d2cc0     {"Abgerechnet", closed}
ffa59312-ca54-4373-8b67-92ee19181243      {"Abgeschlossen,closed}
de178f34-2605-40b2-8a12-1a00171fbdd4       {"In Arbeit", progress}

URL:
https://api.awork.io/api/v1/projects/facec1d8-5568-4553-bf4d-3f369b374214/changeStatus  
...MIT PAYLOAD:
{"ProjectStatusId": "1b634cc1-9b3b-49b8-b14b-f36e093d2cc0"}

Danach: Aufruf der URL:
https://coral-breathtaking-professionals.awork.io/projects/facec1d8-5568-4553-bf4d-3f369b374214/details

Ergebnis: Weder der geänderte Status, noch der Projektname werden angezeigt
Workarround:Umschgalten von "Details" zu "Aufgaben" -  und wieder zurück:

Anzeige ist wieder korrekt.
Es werden  der geänderte Status und der Korrekte name des Projekts angezeigt 

Siehe angehängtes Quicktime

https://github.com/awork-io/awork/assets/90595629/0538e4c7-12cf-4910-9215-2f31f18ddba8

### What is the trace id of the call?

204 No Content

**Comment by nilzzzzzz** [comment]
Hi @wwdto , 

i can repro the issue, its not API related but seems to be an issue in the Frontend. I created an issue on our side and we will try to fix this ASAP. Thanks for bringing this up.

Nils

**Comment by nilzzzzzz** [comment]
HI @wwdto , 

jetzt können wir es doch in keinem Szenario mehr nachstellen. Passiert es bei euch immer? Ihr macht nur den Call zu Change Status und ruft dann das Projekt auf und der Status & Name erscheint nicht?

Viele Grüße
