### ISSUE TITLE
How to combine filters in API

### ISSUE THREAD

**Issue by wwdto** [awork-io/awork#129]
### What is your question?

I want to combine filters:

This one works:
https://api.awork.io/api/v1/timeentries?filterby=createdOn gt datetime'2023-03-22T00:00:00' and createdOn lt datetime'2023-03-22T23:59:59'

This on does NOT work: 
https://api.awork.io/api/v1/timeentries?filterby=user.id GUID'12345678-ec37-ed11-ae83-38563d6848fe'

What I want ist to combine all this  filters  like:
https://api.awork.io/api/v1/timeentries?filterby=createdOn gt datetime'2023-03-22T00:00:00' and createdOn lt datetime'2023-03-22T23:59:59' AND user.id GUID'12345678-ec37-ed11-ae83-38563d6848fe'

Goal is to get all timeentries of timeperiod of a certain  user .

**Comment by nilzzzzzz** [comment]
> ### What is your question?
> I want to combine filters:
> 
> This one works: https://api.awork.io/api/v1/timeentries?filterby=createdOn gt datetime'2023-03-22T00:00:00' and createdOn lt datetime'2023-03-22T23:59:59'
> 
> This on does NOT work: https://api.awork.io/api/v1/timeentries?filterby=user.id GUID'12345678-ec37-ed11-ae83-38563d6848fe'
> 
> What I want ist to combine all this filters like: https://api.awork.io/api/v1/timeentries?filterby=createdOn gt datetime'2023-03-22T00:00:00' and createdOn lt datetime'2023-03-22T23:59:59' AND user.id GUID'12345678-ec37-ed11-ae83-38563d6848fe'
> 
> Goal is to get all timeentries of timeperiod of a certain user .
> 
> ### Do you have a trace id of the call?
> _No response_

Hi @wwdto, 

it needs to be: 
 `https://api.awork.io/api/v1/timeentries?filterby=user/id guid'12345678-ec37-ed11-ae83-38563d6848fe'´

The `Guid` needs to be in lowercase and you need a slash between object and property. And the `And` needs to be in lowercase.
