### ISSUE TITLE
How can we generate fixed token to work with the API?

### ISSUE THREAD

**Issue by H4mz4-mk** [awork-io/awork#13]
Hey, lately I've been accessing the API wit OAuth 2, which is expiring  in a short time, I would like to use the API with a fixed Access Token, in the Docs there's a link which is explaining the details [https://support.awork.io/hc/de/articles/360002815960-Client-Applications-und-API-Keys](url) but it's not working, so how can we do that?
Thanks

**Comment by nilzzzzzz** [comment]
hi @H4mz4-mk ,

i upgraded the link. The correct one is https://support.awork.io/en/articles/5415664-client-applications-and-api-keys

Best

Nils
