### ISSUE TITLE
API Authentication

### ISSUE THREAD

**Issue by SebastianIngress** [awork-io/awork#130]
### What is your question?

We would like to authenticate with the aWork API and got to a certain point in your documentation and now we are stuck; all App-Data has been created in the aWork App. https://developers.awork.io/authentication

POST https://api.awork.io/api/v1/accounts/token
Authorization: Basic Base64(client_id:client_secret )
Content-Type: application/x-www-form-urlencoded

redirect_uri=http://localhost/
&grant_type=authorization_code
&code={code}

Of course the variables "cliend_id", "client_secret" and "code" are replaced with our real data.
But we receive the HTTP Error 400.

The variable "code" we took out of the URL after granting access over your Interface after getting it from this request: 

GET-Request:
https://api.awork.io/api/v1/accounts/authorize?client_id=vacation-app&response_type=code&grant_type=authorization_code&redirect_uri=http://localhost&scope=offline_access

**Comment by nilzzzzzz** [comment]
Hi @SebastianIngress , could you provide us with the `Trace-Id` of the 400 call. You find this Id in the Response Headers of the call, then we can easily see what is going on.

Best

Nils

**Comment by SebastianIngress** [comment]
> Hi @SebastianIngress , could you provide us with the `Trace-Id` of the 400 call. You find this Id in the Response Headers of the call, then we can easily see what is going on.
> 
> Best
> 
> Nils

Hi @nilzzzzzz,

we found out that our HttpRequest.class was causing the issue and now we got the access-token with another Curl-Method, so it's working for now, thanks. I will write if we get another issue.

Best regards

Sebastian

**Comment by nilzzzzzz** [comment]
@SebastianIngress great to hear! Have a good day!
