### ISSUE TITLE
[Question]: awork Aufgabe anlegen in Python

### ISSUE THREAD

**Issue by aeon93** [awork-io/awork#131]
### What is your question?

Hallo,
ich würde gerne mit Python eine Aufgabe in awork anlegen. Welche API Daten benötige ich dafür und wie lautet der Python Code dafür?
Ich konnte schon die IDs der Projekte mit folgenden Code mir auflisten, also eine READ Funktion habe ich hinbekommen. Nur einen WRITE Befehl in Python konnte ich leider nicht machen, da habe ich immer eine Fehlermeldung erhalten.
`import requests
import json

# Setzen Sie hier Ihren awork API-Schlüssel ein
api_key = 'API-KEY'

1# Definieren Sie die URL für die awork API
url = "https://api.awork.io/api/v1/projects"

# Erstellen Sie die Header für die Anfrage
headers = {
    'Authorization': f'Bearer {api_key}',
    'Content-Type': 'application/json'
}

# Senden Sie die Anfrage an die API
response = requests.get(url, headers=headers)

# Überprüfen Sie den Statuscode der Antwort
if response.status_code == 200:
    projects = response.json()
    for project in projects:
        print(f"Projektname: {project['name']}, Projekt-ID: {project['id']}")
else:
    print(f"Fehler beim Abrufen der Projekte, Statuscode: {response.status_code}.")
`

**Comment by nilzzzzzz** [comment]
Hi @aeon93 ,

we are not experts in python, but this worked out for me:

```
import http.client
import json

conn = http.client.HTTPSConnection("api.awork.io")

headersList = {
 "Accept": "*/*",
 "User-Agent": "Thunder Client (https://www.thunderclient.com)",
 "Content-Type": "application/json",
 "Authorization": "Bearer YOUR_API_KEY" 
}

payload = json.dumps({
  "typeOfWorkId": "04fcb592-a918-e911-9f2b-00155d31542d",
  "taskStatusId": "a6266e68-8e41-405c-b925-bbc2aca8623e",
  "name": "ok",
  "description": "",
  "entityId": "e14f5498-f2f7-440b-b558-cde3cdf14fe9",
  "baseType": "projecttask",
  "order": null,
  "lists": [
    {
      "id": "536ee8af-4855-424f-8427-b4d9c9161540",
      "order": 0
    }
  ],
  "subtaskOrder": null
})

conn.request("POST", "/api/v1/tasks", payload, headersList)
response = conn.getresponse()
result = response.read()

print(result.decode("utf-8"))
```

Please make sure to change the ids to the values which match the values in your workspace. The response should give you a hint if any of the pre-requirements are not fulfilled.

**Comment by aeon93** [comment]
Hey, what exactly would this code do? Will it create a task in a project? The name of the task would be "ok"? Can i also assign a collegue on this task and a deadline? Please let me know what all of the listed IDs stand for.

**Comment by nilzzzzzz** [comment]
Yes it creates a task in a project. The task name is `ok`. To assign a user you need to do this additional call after creating a task. `/tasks/{taskId}/setassignees`. The deadline is the `dueOn` field on the POST call. The explaination about all fields you can find here: openapi.awork.io .

Best

Nils

**Comment by aeon93** [comment]
Hey, am I using the correct API Token?
Please have a look at the pictures attached.
I would like to create a task named "Test" in a project with the ID "ff588d1a-d495-4e73-8855-cf6d5bd36666" but it doesn't work.
Is my token only valid for GET requests or timely limited?
![1](https://github.com/awork-io/awork/assets/140618650/501bbc7b-a33b-43b7-9c4c-741249d15154)
![2](https://github.com/awork-io/awork/assets/140618650/c8cbe720-0dfa-4f7b-8065-0b07b63b685c)
![3](https://github.com/awork-io/awork/assets/140618650/7f1954bd-a95d-4335-b829-83122c6c1740)
![4](https://github.com/awork-io/awork/assets/140618650/1d8c6179-4909-4d99-9f10-11f7004164f2)

**Comment by aeon93** [comment]
I just want to get the tasks in a project and it also doesn't work. The API is not working.
Could you please write me a simple python script to get all tasks from the project with the ID: "ff588d1a-d495-4e73-8855-cf6d5bd36666"?
Does the project need any specific settings?
- It's not a private project
- the project is running "Läuft"
- autopilot is not activated
- there's no automation activated
- it's a "Intern" project

I don't know what to do. I get the following error:
Fehler beim Abrufen der Aufgaben, Statuscode: 404.

This is the python code i use:

import requests
import json

api_key = ''

project_id = 'ff588d1a-d495-4e73-8855-cf6d5bd36666'

url = f"https://api.awork.io/api/v1/projects/{project_id}/tasks/lists"

headers = {
    'Authorization': f'Bearer {api_key}',
    'Content-Type': 'application/json'
}

response = requests.get(url, headers=headers)

if response.status_code == 200:
    tasks = response.json()
    for task in tasks:
        print(f"Aufgabenname: {task['name']}, Aufgaben-ID: {task['id']}")
else:
    print(f"Fehler beim Abrufen der Aufgaben, Statuscode: {response.status_code}.")


Just to make sure, yes i've inserted the API Key, but for security reasons, i deleted it now for this sample.

**Comment by nilzzzzzz** [comment]
Hi @aeon93 ,

in this case you received a `404` because the `url` you used is wrong. 
To get the tasks of a specific project you need to use: `https://api.awork.io/api/v1/projects/{project_id}/projecttasks`.

I hope that helps.

Best 

Nils
