### ISSUE TITLE
[Question]: How can we get planned effort split per member?

### ISSUE THREAD

**Issue by AHEPhoenix** [awork-io/awork#134]
### What is your question?

We want to get the "planned effort" specified per "project member" of all tasks via API. Is it possible?

example 
![image](https://github.com/awork-io/awork/assets/141328770/3be4ea27-920e-4efe-9c62-4fd68f5347f8)

Or is there a "workaround solution" for it?

**Comment by nilzzzzzz** [comment]
Hi @AHEPhoenix,

i am not 100% sure if i understand your requirement but my guess is you mean the planned effort per assignee of a task:

That value is included in Task->assignees->[.]->plannedEffort. 
So you could get all tasks for a project and then group by the user assignments. 

Does that help?

Best 

Nils

**Comment by AHEPhoenix** [comment]
Thank you, @nilzzzzzz ! 
It worked for one Task. 
Is it possible to get it for all tasks from all projects?

**Comment by HLUPX** [comment]
> Hi @AHEPhoenix,
> 
> i am not 100% sure if i understand your requirement but my guess is you mean the planned effort per assignee of a task:
> 
> That value is included in Task->assignees->[.]->plannedEffort. So you could get all tasks for a project and then group by the user assignments.
> 
> Does that help?
> 
> Best
> 
> Nils

Hi @nilzzzzzz @AHEPhoenix 
I want to jump in this topic. 
What is our target: After we planned a project in awork, we want to know how many hours are planned for each project member for the whole project. In our projects, quite often several project members are working on one task with a different number of planned hours. We don't know how to get this information via the API. Can you help us?

**Comment by nilzzzzzz** [comment]
Hi @HLUPX ,

yeah i can help here, but unfortunately there is no way around to fetch all tasks in this case. So what i would do in this case:
1. Get all Projects via `api/v1/projects?filterby=plannedduration gt 0`
2. Iterate over all projects
3. Make for each project a call to `api/v1/projects/{projectId}/projecttasks?filterby=plannedduration gt 0` (important, if you have projects with more than 1k tasks , you need to paginate.
4.  Sum up the Task->assignees->[.]->plannedEffort grouped by ProjectId and UserId

I hope this helps.

Best

Nils

**Comment by nilzzzzzz** [comment]
https://github.com/awork-io/awork/issues/135 <- i answered here.
