### ISSUE TITLE
One call for all projects including all tasks per project with planned effort and tracked hours per task

### ISSUE THREAD

**Issue by HLUPX** [awork-io/awork#135]
### What is your question?

We are using Power Bi to do additional analytics besides the existing Time reports and Exports in awork.

General target: We want to have all our awork projects in Power Bi with as much information as possible to do further analytics. 

Specific question:
We want to have all projects from awork in Power Bi and the possibility to select each project in Power Bi and get all tasks of the selected project including planned effort and tracked hours per task. 

Currently, it looks like that we have to submit a single call for each projectID to get the information of the planned effort and tracked time for each task of the project. But this is not efficient and very time consuming. Could you help us?

Thank you
Best, Harald

**Comment by nilzzzzzz** [comment]
Hi @HLUPX, 

okay, i found a more efficient way for you:
`api/v1/me/allavailabletasks?filterby=baseType eq 'projecttask'` 
This should give you all project tasks. Please keep in mind our api is paginated and only returns 1k results per request.

Does that help?

Best

Nils

**Comment by HLUPX** [comment]
Hi @nilzzzzzz 
ok. Very helpful again!
Now we must handle the restriction of 1.000 tasks. 
Is it possible to define the filterby: 
- only for active projects and in addition:
* only for a certain project type
* only for a certain client
* only for a certain project tag?

**Comment by nilzzzzzz** [comment]
Hi @HLUPX ,

why not paginate? You can filter for all properties on the Models. 
How is defined here: https://developers.awork.io/filtering
You can filter for the `projectStatus/name` and the `Tag`. The `ProjectType` and the `Client` is not part of the task model.

Best 

Nils

**Comment by nilzzzzzz** [comment]
My colleague just told me that we have existing solutions for the PowerBi case, give me a few mins ;)

**Comment by nilzzzzzz** [comment]
Hi @HLUPX ,

it was a bit more complex as expected BUT, this should work:
```
let
    baseUrl = "https://api.awork.io/api/v1/me/allavailableTasks",
    headers = [#"Content-Type"="application/json", Authorization="Bearer {yourToken}"],
    getPageOfTasks = (page) =>
        Json.Document(
            Web.Contents(baseUrl, [Headers=headers, Query=[page=Text.From(page), pageSize="1000"]])
        ),
    allTasks = List.Generate(
        () => 1,
        each List.Count(getPageOfTasks(_)) > 0,
        each _ + 1,
        each try getPageOfTasks(_) otherwise null
    ),
    taskRecords = List.Combine(allTasks),
    taskTable = Table.FromList(taskRecords, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    allRecords = Table.ExpandRecordColumn(taskTable, "Column1", {"name", "project", "assignees"}),
    #"Erweiterte project" = Table.ExpandRecordColumn(allRecords, "project", {"name"}, {"project.name"}),
    #"Erweiterte assignees" = Table.ExpandListColumn(#"Erweiterte project", "assignees"),
    #"Erweiterte assignees1" = Table.ExpandRecordColumn(#"Erweiterte assignees", "assignees", {"plannedEffort", "firstName", "lastName"}, {"assignees.plannedEffort", "assignees.firstName", "assignees.lastName"})
in
    #"Erweiterte assignees1"
```

and solve your requirement. 

You can just use this code in powerbi here:
<img width="1573" alt="image" src="https://github.com/awork-io/awork/assets/22219385/54d85177-cb08-47fe-a52f-20b640d9f767">

I would appreciate a feedback.

Best

Nils

**Comment by AHEPhoenix** [comment]
Hi @nilzzzzzz 
Thank you for the answer, it worked well to get all tasks!

To connect tabels and make analytics we need the "taskID", "ProjectID", "userID", "task.duration" and "project.type".

**Comment by nilzzzzzz** [comment]
Hi @AHEPhoenix ,

```
let
    baseUrl = "https://api.cwork.io/api/v1/me/allavailableTasks",
    headers = [#"Content-Type"="application/json", Authorization="Bearer {yourToken}"],
    getPageOfTasks = (page) =>
        Json.Document(
            Web.Contents(baseUrl, [Headers=headers, Query=[page=Text.From(page), pageSize="1000"]])
        ),
    allTasks = List.Generate(
        () => 1,
        each List.Count(getPageOfTasks(_)) > 0,
        each _ + 1,
        each try getPageOfTasks(_) otherwise null
    ),
    taskRecords = List.Combine(allTasks),
    taskTable = Table.FromList(taskRecords, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Erweiterte Column1" = Table.ExpandRecordColumn(taskTable, "Column1", {"id", "assignees", "projectId", "project", "plannedDuration"}, {"Column1.id", "Column1.assignees", "Column1.projectId", "Column1.project", "Column1.plannedDuration"}),
    #"Erweiterte Column1.assignees" = Table.ExpandListColumn(#"Erweiterte Column1", "Column1.assignees"),
    #"Erweiterte Column1.assignees1" = Table.ExpandRecordColumn(#"Erweiterte Column1.assignees", "Column1.assignees", {"plannedEffort", "id"}, {"Column1.assignees.plannedEffort", "Column1.assignees.id"}),
    #"Erweiterte Column1.project" = Table.ExpandRecordColumn(#"Erweiterte Column1.assignees1", "Column1.project", {"projectStatus", "company", "projectType", "name"}, {"Column1.project.projectStatus", "Column1.project.company", "Column1.project.projectType", "Column1.project.name"}),
    #"Erweiterte Column1.project.projectStatus" = Table.ExpandRecordColumn(#"Erweiterte Column1.project", "Column1.project.projectStatus", {"name"}, {"Column1.project.projectStatus.name"}),
    #"Erweiterte Column1.project.company" = Table.ExpandRecordColumn(#"Erweiterte Column1.project.projectStatus", "Column1.project.company", {"name"}, {"Column1.project.company.name"}),
    #"Erweiterte Column1.project.projectType" = Table.ExpandRecordColumn(#"Erweiterte Column1.project.company", "Column1.project.projectType", {"name"}, {"Column1.project.projectType.name"})
    //allRecords = Table.ExpandRecordColumn(taskTable, "Column1", {"name", "project", "assignees"}),
  
in
    #"Erweiterte Column1.project.projectType"
```

You can easily adjust those fields by removing everything again going back to this:
```
let
    baseUrl = "https://api.cwork.io/api/v1/me/allavailableTasks",
    headers = [#"Content-Type"="application/json", Authorization="Bearer {yourToken}"],
    getPageOfTasks = (page) =>
        Json.Document(
            Web.Contents(baseUrl, [Headers=headers, Query=[page=Text.From(page), pageSize="1000"]])
        ),
    allTasks = List.Generate(
        () => 1,
        each List.Count(getPageOfTasks(_)) > 0,
        each _ + 1,
        each try getPageOfTasks(_) otherwise null
    ),
    taskRecords = List.Combine(allTasks),
    taskTable = Table.FromList(taskRecords, Splitter.SplitByNothing(), null, null, ExtraValues.Error)

  
in
    taskTable
```

and just expand the Fields in the Ui.

Best

Nils

**Comment by AHEPhoenix** [comment]
Hi @nilzzzzzz 
this is great! thank you for your help! 

the only thing we don't understand is the "tracked duration" of a task. Most sums are wrong. Isn't it split by assignee? the sums are wrong.

**Comment by nilzzzzzz** [comment]
The tracked duration is a field on the task, so it is not split by user. If you want to get the timetracking values, you need to fetch the timetrackings.

**Comment by AHEPhoenix** [comment]
Ok, that makes sense. 
but now I have the same problem with the maximum of 1k results.

**Comment by nilzzzzzz** [comment]
But the solution from above can be easily adapted to the timetrackings?

**Comment by AHEPhoenix** [comment]
I tried to adopt it several times, but it doesn't work. 
What would be the correct code or name of the table?

**Comment by nilzzzzzz** [comment]
Hi @AHEPhoenix ,

let
    baseUrl = "https://api.cwork.io/api/v1/timeentries",
    headers = [#"Content-Type"="application/json", Authorization="Bearer {yourkToken}"],
    getPageOfTimeTrackings = (page) =>
        Json.Document(
            Web.Contents(baseUrl, [Headers=headers, Query=[page=Text.From(page), pageSize="1000"]])
        ),
    allTimeTrackings = List.Generate(
        () => 1,
        each List.Count(getPageOfTimeTrackings(_)) > 0,
        each _ + 1,
        each try getPageOfTimeTrackings(_) otherwise null
    ),
    timtrackingRecords = List.Combine(allTimeTrackings),
    timetrackingTable = Table.FromList(timtrackingRecords, Splitter.SplitByNothing(), null, null, ExtraValues.Error)

  
in
    timetrackingTable

This worked for me.

**Comment by AHEPhoenix** [comment]
Thank you!
