### ISSUE TITLE
[Question]: Test account

### ISSUE THREAD

**Issue by Morpheus-ro** [awork-io/awork#137]
### What is your question?

is there a way to have a test account? I want to develop 3rd party package for awork

**Comment by vdurante** [comment]
@Morpheus-ro can you please share your development workspace subdomain with us? Thanks!

**Comment by Morpheus-ro** [comment]
Do you mean awork subdomain? I don't have any at the moment

**Comment by nilzzzzzz** [comment]
Hi @Morpheus-ro,

can you signup for a new workspace and then provide us with that subdomain, then you can use that one for your development purposes.

Best

Nils

**Comment by Morpheus-ro** [comment]
Hi @nilzzzzzz ,

here is my domain -> aqua-outstanding-virtuosos.
Thank you and have a nice day :)

Best
Alecs

**Comment by Morpheus-ro** [comment]
hello guys, any news here from your side? @vdurante @nilzzzzzz

**Comment by nilzzzzzz** [comment]
Hi @Morpheus-ro ,

sorry for the slow response.
I updated your subscription and you are good to go. 

Just out of interest, is that a OS project or a specific development for a customer?

Best

Nils

**Comment by Morpheus-ro** [comment]
Hi @nilzzzzzz 

this is for an OS project.

Thank you and have a nice weekend :)
