### ISSUE TITLE
[Question]: Task Name Updates Result in Deleted Descriptions

### ISSUE THREAD

**Issue by digitalwert-devs** [awork-io/awork#139]
### What is your question?

**Description:**
When tasks are created, our bot appends numbers to their names. In updating only the task name using the following code:

```
ticket = {
    name: entity.name + " #" + newTicketNumber,
};



```
we've observed inconsistent behavior where the task's description gets deleted. This deletion always happens when the task is created from a template.

**Expected Behavior:**
Updating the name should only change the task's name and not affect or delete any other properties, especially the description.

**Actual Behavior:**

- Task descriptions are sometimes deleted upon name update.

- Task descriptions are always deleted when tasks are created from templates.

**Question:**

1. Is there a way to update only the name without affecting other properties?

2. Can you provide or suggest a solution that allows for name updates without risking the deletion of other properties?

**Comment by nilzzzzzz** [comment]
Hi @digitalwert-devs ,

1: No, unfortunately not, we only support HTTP PUT where this behavior is expected.
2: Fetch the task first, update the property you want to modify and then send the full model. 

Does that help?

Best

Nils

**Comment by digitalwert-devs** [comment]
Thank you for the clarification.

I understand the current approach you've described using HTTP PUT. However, I have concerns about potential race conditions. In a scenario where:

I fetch the task.
Another process/user updates the task (e.g., adds a description).
I then update the name of the task using the fetched data.
The changes made by the other process/user in step 2 would be unintentionally overwritten in step 3. This could lead to data inconsistencies and potential loss of information.

The only solution I could think of is updating the name during the night when no one else is working. However, this is far from ideal and poses logistical challenges.

Considering these potential complications, are there any other suggested workarounds or strategies we might employ to safely update the task name without risking other properties?

Best regards

**Comment by digitalwert-devs** [comment]
would it be an option for you to implement PATCH instead of PUT?

**Comment by nilzzzzzz** [comment]
Right now it's not planned to implement `PATCH`.

The risk of race conditions is there, but it's quite unlikely. The reason for that is, that we push changes with websockets to other client applications. So if another user is using the WebApp and writes a description in the meantime, the user would get the update you have done via the API. And if you keep the timeframe between the `GET` and the `PUT` short, the timeframe for a race condition is under < 100 ms. 
From my experience this should make it highly unlikely, if there are not multiple high frequency automations modifying the same entity at the same time.

**Comment by digitalwert-devs** [comment]
Thank you. I'll proceed with implementing your suggestion and monitor its behavior to assess the likelihood of the edge case arising.
