### ISSUE TITLE
API: Assign a user to a new task doesn´t run (Apps Script)

### ISSUE THREAD

**Issue by pmarkus84** [awork-io/awork#14]
The task was created, but no user is assigned. How can i set this?

![grafik](https://user-images.githubusercontent.com/29916438/126768577-bd48928e-9977-44bb-843c-372c47a3e3ff.png)

Thanks in advance.

**Comment by IanBuck-dev** [comment]
Hey Markus,
the user gets assigned via an additional POST endpoint /tasks/assignusers which you can find here https://openapi.awork.io/#/Tasks/post_tasks_assignusers
The model is a list of { userId: Guid,  taskId: Guid }.
Btw., you can find all our endpoints in the swagger docs at https://openapi.awork.io/ which shows you the model for each endpoint that can be used including all possible fields.

Hope I could help you. Let us know if you have any other questions.

Happy coding!
Ian
