### ISSUE TITLE
[Bug]: Link to Swagger Docs on https://developers.awork.com/ broken

### ISSUE THREAD

**Issue by MurmeltierS** [awork-io/awork#141]
### What happened?

After the domain migration from awork.io -> awork.com the link to the OpenAPI Swagger Docs (previosly available on https://openapi.awork.io/) is broken and links to a non-existant workspace.

see: https://openapi.awork.com/

![image](https://github.com/awork-io/awork/assets/6160707/aefa7e42-b515-4471-b1be-5a62eb73fd6a)

![image](https://github.com/awork-io/awork/assets/6160707/df0a66a2-e683-4a81-ac3f-945f69db903b)

### What is the trace id of the call?

n/a

**Comment by sebastianrosch** [comment]
Thanks @MurmeltierS, I fixed the link.
