### ISSUE TITLE
[Bug]: Outdated(?) list of Webhook Event Names

### ISSUE THREAD

**Issue by MurmeltierS** [awork-io/awork#142]
### What happened?

The list of webhook events on https://developers.awork.io/webhooks describes a `task_changed` webhook, using that event will result in an invalid-model error. 

Looking at the event identifier [used in the admin dashboard](https://brandboosting.awork.com/settings/workspace/integrations) it seems like the correct event identifier is `task_updated`.

prbly also affects other events.

### What is the trace id of the call?

n/a

**Comment by nilzzzzzz** [comment]
Hi @MurmeltierS ,

thanks for bringing that up. We are right now fixing the docs and the UI and will release it soon. 

Best

Nils
