### ISSUE TITLE
How to filter/search items by associated tags?

### ISSUE THREAD

**Issue by DirkOrange** [awork-io/awork#144]
### What is your question?

With the filterby parameter I can search for items. Like "/companies?filterby=startswith(name,'myCompany')."

This works well for the direct item properties. But how to search for a items with a certain tag? E.g. "All companies with a tag of name 'Billable'"? Something like "/companies?filterby=tags.name eq 'Billable'" ...

**Comment by nilzzzzzz** [comment]
Hi @DirkOrange,

the correct syntax for this case:
`/companies?filterby=tags/any(p: p/name eq 'Billable')`

Best

Nils
