### ISSUE TITLE
[Question]: Connection with make.com can't be established

### ISSUE THREAD

**Issue by julianwitzel** [awork-io/awork#146]
### What is your question?

When connecting to make.com I keep getting this error: "[400] Subscription has been cancelled".

I followed your guide (https://support.awork.com/de/articles/6664037-make-integration) and did everything exactly the same.

Your support team told me to submit an issue here so you can investigate and get back to me directly.

**Comment by sebastianrosch** [comment]
Hi @julianwitzel do you have the trace id of the call? Can you share a screenshot of where you're seeing this error? Can you also share the URL of the workspace? Thanks

**Comment by julianwitzel** [comment]
Hi @sebastianrosch. Unfortunately I don't have a lot of information.

I create the integration in awork, copy the details over to make.com and click "save". Then I get redirected to the awork authentication page, choose my workspace and click on "allow all". Then I get redirected back to the make.com scenario where I am working. Here is where I see the error from above.

<img width="458" alt="Bildschirmfoto 2023-09-10 um 17 58 53" src="https://github.com/awork-io/awork/assets/43474478/34d7feb5-3e7e-43ef-921e-32b38b228de6">
<img width="586" alt="Bildschirmfoto 2023-09-10 um 17 59 33" src="https://github.com/awork-io/awork/assets/43474478/5dffcf8f-8eb2-48b4-9ff4-c4d336aa8c76">

**Comment by nilzzzzzz** [comment]
Hi @julianwitzel ,

i just tried the flow with a fresh make.com account and for me the flow worked as expected. Could you try again, perhaps it was a transient issue on the make.com side, we do not see what could cause the issue on our side. 

If its then still not working for you, probably you need to contact make.com and ask them for further information.

Best

Nils

**Comment by julianwitzel** [comment]
@nilzzzzzz I just deleted the integration in awork again, refreshed the make.com page and tried again with a fresh integration from awork.

Same result.

I will contact make.com now for further assistance.

Do you restrict the API access to certain plans? The error code indicates to me that I don't have the permissions to do what I need. ([400] Subscription has been cancelled.)

**Comment by nilzzzzzz** [comment]
Ah, if your subscription has been cancelled you cannot use the API anymore. But you can also not login anymore..

**Comment by nilzzzzzz** [comment]
But we have no plan restrictions, this just means you cancelled or your trial expired.

**Comment by julianwitzel** [comment]
We have an active subscription (Premium) in awork and the core plan in make.com

**Comment by nilzzzzzz** [comment]
Okay, strange, the message comes definitely from us and not make.com and usually indicates that it was cancelled, can you give me your awork subdomain so i can double check on our site?

**Comment by julianwitzel** [comment]
@nilzzzzzz  tomato-outstanding-angels.awork.com

**Comment by julianwitzel** [comment]
Unfortunately still the same.

I just created a new secret and tried again.

<img width="786" alt="Bildschirmfoto 2023-09-11 um 14 39 27" src="https://github.com/awork-io/awork/assets/43474478/e3abf476-5ba4-42c6-84c6-aaeab3b9219f">

**Comment by nilzzzzzz** [comment]
Sorry, can you try once again, maybe you hit one of our cache layers. I just tried the permission calls involved and for me they are succeed. Creating an ew clientId is not neccessary.

**Comment by julianwitzel** [comment]
Same thing :(

**Comment by nilzzzzzz** [comment]
@julianwitzel sorry for that. So to be honest we have right now no clue because we have limited observability during the connection establishment. 

What we will try to do tomorrow is try different cases which could reproduce the issue.
Could you check in the meantime if you see a specific response body for the network call to `https://eu1.make.com/api/v2/connections/XXX/test`

**Comment by julianwitzel** [comment]
This is what I can find. I hope it helps you.

<img width="854" alt="response" src="https://github.com/awork-io/awork/assets/43474478/324e2391-9ca8-4c84-ba75-47e23aafdf20">

**Comment by nilzzzzzz** [comment]
Hi @julianwitzel ,

thank you! Could you do it one last time? We added now at all relevant places logs and should be able to identify the issue when you do the flow again.

Best

Nils

**Comment by julianwitzel** [comment]
Now it works! I don't know what changed or what was the reason though.

**Comment by nilzzzzzz** [comment]
Okay :D Thank you so much for bringing patience ;) We will monitor if others run into that issue but we also have no idea why it not worked.
