### ISSUE TITLE
[Question]: Is it possible to find a company by name?

### ISSUE THREAD

**Issue by julianwitzel** [awork-io/awork#148]
### What is your question?

Hey, it's me again!

I was wondering if it is possible to find a company by name. In make.com I don't find this option. There is only "Get company" and it returns a list of all companies. Our automation is dynamic and the company name originates from a form on our intranet website.

For example:
If a company that exists already in awork is called "Testcompany Inc." and I have a value "Testcompany" from my form, how can I find the company since the name is not exactly equal. Is there a way to search for a match in the string so that it still counts as "exists already"?

I built a similar automation for Google Drive. There we also check if the folder already exists by comparing the company name strings from the form and the actual folder name.

<img width="431" alt="Bildschirmfoto 2023-09-12 um 16 10 32" src="https://github.com/awork-io/awork/assets/43474478/03fbf00c-a918-4b4d-abc1-8cb14190be0c">

I hope you get my question since it is not so easy to explain.

**Comment by nilzzzzzz** [comment]
Hi @julianwitzel ,

sure. You need to do a custom request with make and then do a call to `https://api.awork.com/api/v1/companies?filterby=name eq '{YOURNAME}'

**Comment by julianwitzel** [comment]
Ok, that is already a good hint.

Now I get this response:
<img width="402" alt="Bildschirmfoto 2023-09-12 um 16 19 20" src="https://github.com/awork-io/awork/assets/43474478/d56059a6-bd96-4d3d-accc-12ef9e1e5a6b">

**Comment by nilzzzzzz** [comment]
do you see a trace id? I think its visible somewhere in the ui.

**Comment by nilzzzzzz** [comment]
I found this trace for you: `companies?filterby=Test` . This is not correct, you need to have companies?filterby=name eq 'test'

**Comment by julianwitzel** [comment]
Ahhhh ok, my bad. Thank you!

Look, I made 3 tests to find the company "REPERA GmbH" in awork:

1. Input: REPERA GmbH
<img width="653" alt="Bildschirmfoto 2023-09-12 um 16 37 43" src="https://github.com/awork-io/awork/assets/43474478/dd38e4a9-06e0-487d-a977-07bfa05d6c4e">

2. Input: Repera GmbH
<img width="657" alt="Bildschirmfoto 2023-09-12 um 16 38 12" src="https://github.com/awork-io/awork/assets/43474478/9e10aa0e-1f34-4e46-856e-2896d962e923">

3. Input: Repera
<img width="602" alt="Bildschirmfoto 2023-09-12 um 16 38 28" src="https://github.com/awork-io/awork/assets/43474478/20481116-3e2e-42c5-adef-32591d0a7bfe">

In the third case it does not find the company.

I did the same test in my awork dashboard and there it works.
<img width="1026" alt="Bildschirmfoto 2023-09-12 um 16 40 59" src="https://github.com/awork-io/awork/assets/43474478/d5eed6ea-1d88-47fd-ae2a-ce096de413cb">

Do I need to put in some additional params?

**Comment by nilzzzzzz** [comment]
the `eq` filters for equality. Here you see the other possibilities: https://developers.awork.com/filtering

**Comment by julianwitzel** [comment]
Perfect! Thank you so much for your help :)
