### ISSUE TITLE
[Question]: How to add a line break when adding a project via API?

### ISSUE THREAD

**Issue by julianwitzel** [awork-io/awork#149]
### What is your question?

Hey guys,

I am creating a project and am still facing 2 problems:

1. How can I add the corresponding teams to the project via ID?
2. How can I add a line break in the project description?

I am using make.com and it works perfectly fine except for those 2 things.

This is my request body:
`{
    "name": "Website Creation (MAKE TEST)",
    "isPrivate": false,
    "description": "This is a testproject.\n{{if(9.webViewLink; "Drive: " + 9.webViewLink + "\n")}}Briefing: {{3.webViewLink}}\nSlack: https://app.slack.com/client/{{3.workspaceID}}/{{5.id}}",
    "startDate": "{{1.submitted_at}}",
    "dueDate": "{{39.projectDeadline}}",
    "companyId": "{{if(30.newClientID; 30.newClientID; 26.body[].id)}}",
    "projectTemplateId": "01475b9e-73d9-42f2-87cb-59de3a9f27e8",
    "teams": [
        {
            "id": "c7520764-3820-4987-be4a-3f30b461de72"
        },
        {
            "id": "23691c4a-c0c7-4fd6-8731-68a00e386f43"
        },
        {
            "id": "16a58fdc-bbe5-4df3-be4a-b9cc40581895"
        }
    ]
}`

**Comment by nilzzzzzz** [comment]
Hi @julianwitzel ,

the formatting needs to be done with HTML. So a line break is `</br>` 
The teams need to be added in a seperat call: https://openapi.awork.com/#/Teams/post_teams__teamId__addprojects

Best

Nils
