### ISSUE TITLE
[Question]: Why aren't task's tags included in time entries?

### ISSUE THREAD

**Issue by larspaetzke** [awork-io/awork#150]
### What is your question?

When fetching time entries (https://openapi.awork.com/#/TimeEntries), I noticed the associated tasks do not include their tags. For my use case, it would be beneficial if the tags associated with a task could be included directly within the response. This would save multiple additional calls to fetch each task's details just to get the tags.

Example response (array of time entries):

```
[
  /* time entry */
  {
    ...
    "task": {
       "tags": [ this array of tags does not exist ]
        ...
    },
    ...
  }
]
```

Is there a possibility to include tags in the time entries response in the future? Or is there another efficient way to retrieve tags for tasks associated with time entries that I might have missed?

### Do you have a trace id of the call?

I don't have a specific trace-id for this question as it's more about the structure of the response rather than a specific call issue.

**Comment by sebastianrosch** [comment]
Hi @larspaetzke this is not included for performance reasons at the moment. We will consider this and provide an update if we implement this. Thanks for bringing it up!

**Comment by nilzzzzzz** [comment]
Hi @larspaetzke,
as an recommendation how to still efficiently solve it: You can fetch all `timeEntries` which are relevant for you. Get all `taskIds` of those `timeEntries` and then make one call to the task endpoint `me/allavailabletasks` with a filter for the task ids like this: `filterby=id eq guid'abc' or id eq guid'def'`. 

Does that help?

Best

Nils
