### ISSUE TITLE
[Question]: Please provide a quick summary of your question

### ISSUE THREAD

**Issue by simonrueger90** [awork-io/awork#151]
### What is your question?

Wenn ich einen Webhook anlege im Interface (Frontend) von awork funktioniert er normal und kann getestet werden.

wenn ich die Authentifizierung auf on stelle, dann gibt es einen Fehler beim senden. Es wird kein request ausgeführt.

Wie kann ich die Authenifizierung nutzen?

Fehlermeldung oben rechts:
"Fehler
Fehlerhafte Daten
Etwas stimmt mit den Daten nicht."

**Comment by nilzzzzzz** [comment]
Hi @simonrueger90,

ich habe es gerade bei mir ausprobiert und es ging ohne Probleme. Könntest du mir einmal die `Trace-Id` aus dem Response Header zusenden oder ein Video von dem Verhalten machen?

**Comment by simonrueger90** [comment]
https://github.com/awork-io/awork/assets/148749298/0fa1dcca-e240-4bf2-9af7-ea4d6ced5552

Der erste Test wurde bei RequestBin registriert. Der Zweite nicht

**Comment by nilzzzzzz** [comment]
Hi @simonrueger90,

danke! 

Wir konnten das Problem nachstellen und der fix wird im Laufe des Tages ausgeliefert.

Grüße

Nils

**Comment by nilzzzzzz** [comment]
Der fix ist online. Bitte einmal die Anwendung neu laden.
