### ISSUE TITLE
[Question]: How to limit API key permissions

### ISSUE THREAD

**Issue by juekbr** [awork-io/awork#153]
### What is your question?

I have the following use case: our customers want to know how much (of their paid) time was consumed on their projects.
Easy task using google tables and google apps script. 
My problem is rather: when this goes out to customers / to externals, I have to limit the API key so it could only access specific projects. In all other cases I have just opened a security hole.
Is limitation possible?

**Comment by sebastianrosch** [comment]
Hi @juekbr 
This is possible via the OAuth 2.0 flow, where users log in granting the application access to awork. Users would then only see the projects they are allowed to see in awork, as normal user permissions will be applied in this case.

You can find more details here: https://developers.awork.com/authentication

I hope this helps
