### ISSUE TITLE
How to set up Two-way connection between Hubspot and Awork

### ISSUE THREAD

**Issue by ahatzold** [awork-io/awork#154]
### What is your question?

We want to trigger the creation, and the Update of Projects, Tasks & Customers from within Hubspot AND update Tickets in Hubspot triggered by specific Task-Status changes in Awork. As far as we know, you have done that internally already and we are curious to find out how.

By setting up a webhook in Awork and connecting it to hubspot, we can create elements in Hubspot (so far we only tried with contacts and did not manage to write into specific fields, creating only empty elements) We lack control over when the webhook is triggered in awork (creating filters on events / objects as triggers would be AMAZING)
![Screenshot 2023-12-11 at 15 04 24](https://github.com/awork-io/awork/assets/149073131/94ac5701-d5ee-4b9b-8194-c65fd4996346)

In Hubspot we tried to connect from within a workflow tool using the webhook interface and triying to connect to an API Client set up in Awork. 
<img width="1039" alt="Screenshot 2023-12-12 at 08 44 16" src="https://github.com/awork-io/awork/assets/149073131/0f92230d-4baf-4555-81a1-c01d16c9190e">

With the GET method we receive a positive Connection Test in Hubspot, but no data from Awork. 
<img width="450" alt="Screenshot 2023-12-12 at 08 46 08" src="https://github.com/awork-io/awork/assets/149073131/1ca725ff-8e65-4798-b3d8-daa2859ec872">

With the Post method we think there might be an issue with Permissions. 
<img width="452" alt="Screenshot 2023-12-12 at 09 03 55" src="https://github.com/awork-io/awork/assets/149073131/535c9af0-b28e-4fae-ad4b-7ee8579b9497">

It leaves us wondering, if the Send Weebhook interface in Hubspot is actually going to work with the awork API. Or do we have to write our own code in order to connect and manipulate elements in awork?
<img width="1129" alt="Screenshot 2023-12-12 at 08 58 04" src="https://github.com/awork-io/awork/assets/149073131/f242db1a-937e-4820-a6d7-3d06b5e90e3f">

**Comment by vdurante** [comment]
@ahatzold what authentication method are you using for the POST operation? By any change do you have the trace id?

**Comment by sebastianrosch** [comment]
Hi @ahatzold do you still need help here?
