### ISSUE TITLE
[Bug]: Please provide a quick summary of the problem | API Keys

### ISSUE THREAD

**Issue by tobiasarmiri** [awork-io/awork#156]
### What happened?

API Keys for my Integration: AccessToTimeEntries are not being shown.
I can click on the Show-Keys button but it's empty. It worked on Friday.

Please fix

### What is the trace id of the call?

No ID Call available.

**Comment by sebastianrosch** [comment]
Hi @tobiasarmiri, thanks for the report, this is fixed now.
