### ISSUE TITLE
[Bug]: Please provide a quick summary of the problem

### ISSUE THREAD

**Issue by simonrueger90** [awork-io/awork#157]
### What happened?

api-key is not shown in the input field
https://fuchsia-ambitious-wizards.awork.com/settings/workspace/integrations -> API Clients -> API Keys verwalten -> API Key kopieren

I can copy the key directly from the json request. The only bug is that after the request the key is not written into the input field.

### What is the trace id of the call?

d7edd4002e9f08c8fca8fd847790d64e

**Comment by sebastianrosch** [comment]
Hi @simonrueger90, thanks for the report, this is fixed now.
