### ISSUE TITLE
Are task and subtask included in Request for timetracking?

### ISSUE THREAD

**Issue by ujora** [awork-io/awork#158]
### What is your question?

Hi, 

We are trying to find a way to include the main task into our reporting when a user tracks time on a subtast. Currently, if the report is being downloaded, the task name is being replaced by the name of the subtask. 

My question is whether in the response for a timetracking entry (e.g. timetracking_added), will the name of the task AND subtask show up? 

(Maybe you could just paste an example response?)

Thank you!

**Comment by sebastianrosch** [comment]
Hi @ujora, I'm not sure I fully understand your requirement. Are you talking about the webhooks? I would recommend to simply set up a webhook in awork using a service like RequestBin so you can inspect the various properties sent to your webhook URL.

https://public.requestbin.com/

**Comment by ujora** [comment]
@sebastianrosch thanks for the quick reply. Yes, I was talking about the webhooks :)
I just tried via Requestbin. Thanks for the recommendation!

From what I can see, tasks (subtasks and tasks) are not being distinguished:

![image](https://github.com/awork-io/awork/assets/156102345/95dd9e27-d6c7-4721-8419-9f5094649041)

Both levels show up as **projecttask**, there is no differentiation into tasks and subtast

![image](https://github.com/awork-io/awork/assets/156102345/eae0c59b-9563-4cef-90cd-243c6993bfa1)
![image](https://github.com/awork-io/awork/assets/156102345/b8ef2629-12ae-4d35-a1ed-7dc001b7875d)

**Comment by sebastianrosch** [comment]
Correct, tasks and subtasks are the same entity, but subtasks have a parent id set, which is the id of another task. 
If the information you need is not part of the model sent via websocket, you can fetch this information from the API, so for example either the parent task or the project.

**Comment by sebastianrosch** [comment]
I'm closing this issue. Let us know if you need further help.
