### ISSUE TITLE
[Question]: Problems with API Authorisation

### ISSUE THREAD

**Issue by ArthurWenzel** [awork-io/awork#159]
### What is your question?

Hello,

I am trying to retrieve data for evaluations in PowerBI via the API and am redirected to my workspace during authorization, but I get the error: "... this is a 404! Unfortunately, the link you are calling up does not exist or the object has already been deleted. Please check the link and try again or use the search."

Unfortunately, I am not experienced in the topic of API calls and have tried the following code in Python:
import requests

#Client-Anmeldeinformationen (client_id und client_secret) einsetzen.
client_id = "test01"
client_secret = "client_secret provided by API client"
redirect_uri = "http://localhost:3000/oauth/callback"

# OAuth 2.0 Authorization-Endpoint URL
authorization_url = "https://MyCompanyName.awork.com/accounts/authorize"

# Aufforderung, die Autorisierung zu erteilen
authorize_params = {
    "client_id": client_id,
    "redirect_uri": redirect_uri,
    "scope": "offline_access",
    "response_type": "code"
}

authorize_response = requests.get(authorization_url, params=authorize_params)
print("Gib die Autorisierung im geöffneten Link ein:", authorize_response.url)

I suspect it's the authorization_url, but unfortunately I can't find the error.

Best regards Arthur

**Comment by nilzzzzzz** [comment]
Hi @ArthurWenzel,

for the powerBI case its probably much easier to use a fixed api token. Is that an option for you? Than you do not need to do the complex Oauth flow: here is explained how to generate a bearer token: https://support.awork.com/en/articles/5415664-client-applications-and-api-keys

Best

Nils

**Comment by ArthurWenzel** [comment]
> Hi @ArthurWenzel,
> 
> for the powerBI case its probably much easier to use a fixed api token. Is that an option for you? Than you do not need to do the complex Oauth flow: here is explained how to generate a bearer token: https://support.awork.com/en/articles/5415664-client-applications-and-api-keys
> 
> Best
> 
> Nils

Hello @nilzzzzzz 

If I can retrieve the data without authorization, that would be great. But I have tried it with the following code and unfortunately I get the error 401 {"message": "Bad token; invalid JSON"} back.

import requests
import json

access_token = "client_secret provided by API client"

projects_url = "https://MyCompanyName.awork.com/api/v1/projects"

headers = {
    "Authorization": f"Bearer {access_token}"
}

projects_response = requests.get(projects_url, headers=headers)

if response.status_code == 200:
    print("Projekte:")
    print(projects_response.json())
else:
    print(f"Fehler beim Abrufen der Projekte. Statuscode: {response.status_code}")
    print(response.text)

**Comment by nilzzzzzz** [comment]
@ArthurWenzel, are you sure that you are using the right key? It is not the client_secret which should be used as bearer token. The ui in awork is a bit misleading there, but the gif in the support article should help.

**Comment by nilzzzzzz** [comment]
@ArthurWenzel here i created a tutorial how to do the powerbi connection, maybe that helps: https://github.com/awork-io/awork/issues/135

**Comment by ArthurWenzel** [comment]
Thank you,
I will try to make that work.
It was indeed the wrong key
