### ISSUE TITLE
[Question] What's the purpose of/ plans for entity's "key"

### ISSUE THREAD

**Issue by podarcis** [awork-io/awork#16]
Hi there,

I noticed that entity types have a property "key", which are auto-generated based on a unique abbreviation of the entity's name. A new project "Foo Bar" becomes key "FB", and the first task of this project becomes key "FB-1".

Where and how is it currently used by the SPA?

Now I wonder whether we can use this information instead of the UUID/URL for (cross-)referencing tasks in other systems and in communication, like issue numbers are used in ticket/issue systems.

My concrete questions:

- Can the key of a project be set (on creation) or altered? Or is it R/O (seems to be)?
- Can this information (key, numberCount) used for the mentioned purpose above or would you advise against this usage?
- Will these fields stay in future versions of the API/entity or are we at risk that they are obsolete sometime in the near future?

**Comment by IanBuck-dev** [comment]
Hi there,

really good question! The key property is currently only used in the backend for things such as reordering in lists, but this could possibly change in the future. The property is auto-generated and cannot be changed manually. We also do not show the key anywhere in the frontend, therefore I would advise against using the key for referencing the entities (even tho it should be unique).

I hope I could answer your question!

Best wishes
Ian

**Comment by podarcis** [comment]
Hi @IanBuck-dev,

Thanks for your fast response! Alright, then we'd have to implement our own Issue-ID mechanism.

Maybe you want to update your docs and mark fields `key` and `numberCount` as OpenAPI `readOnly` and add a note that the fields are internal?
