### ISSUE TITLE
/me/allavailabletasks is missing assigned tasks of user

### ISSUE THREAD

**Issue by theDevelopper** [awork-io/awork#17]
Hello, I am currently looking into using these two endpoints:
- `/me/assignedtasks`
- `/me/allavailabletasks`

according to your API specification the `/me/allavailabletasks` endpoint returns:
 - project tasks if the user has "project-planning" permissions
 - all assigned tasks
 - private tasks created by the user and assigned to other users.

Whereas the `/me/assignedtasks` endpoint returns "all assigned tasks" (including private).

According to that logic the `/me/allavailabletasks` endpoint should return at least the same amount of tasks, if not more, than the `/me/assignedtasks` endpoint. But for us this is not the case.

But when using both calls with the same user, the `/me/allavailabletasks` does not return all assigned tasks that I get with `/me/assignedtasks`.

**Comment by nilzzzzzz** [comment]
Hi @theDevelopper,

thanks for reaching out to us.

Can you please provide us the `trace-id` of the response-headers of both calls and one id of a task which you expect in the result of `allavailabletasks` which is not in the result?
Are you using an oauth access token or an user unspecific access token?

Best

Nils

**Comment by theDevelopper** [comment]
All requests were made with the same OAuth Access Token:

Request to `/me/assignedtasks`:

Response 1 Header:
```etag: 'W/ZjDWjQ==',
aw-totalitems: '101',
aw-items: '50',
aw-page: '1',
aw-pagesize: '50',
trace-id: '2a68a7a7265ee5b2',
```

Response 2 Headers:
```etag: 'W/jVSjMQ==',
aw-totalitems: '101',
aw-items: '50',
aw-page: '2',
aw-pagesize: '50',
trace-id: '2ca303116a23a27b',
```

Response 3 Headers:
```etag: 'W/yo8ZkQ==',
aw-totalitems: '101',
aw-items: '1',
aw-page: '3',
aw-pagesize: '50',
trace-id: '2e9c537f3c8c72f6',
```



Request to `/me/allavailabletasks`:

Response Headers:
```etag: 'W/iRkY3Q==',
aw-totalitems': '4',
aw-items': '4',
aw-page': '1',
aw-pagesize': '50',
trace-id': '2fa9675226cac9c6',
```


A few Tasks I'd expect to be in the result of `allavailabletasks` that are part of `assignedtasks`:
 - b4a2a93d-5a81-e911-abc4-0017fa1003d8
 - b1a2a93d-5a81-e911-abc4-0017fa1003d8
 - aba2a93d-5a81-e911-abc4-0017fa1003d8
 - 03b2eb10-5a81-e911-abc4-0017fa1003d8

 Any task from this project is missing: 826aefcb-5581-e911-abc4-0017fa1003d8

**Comment by nilzzzzzz** [comment]
Hi @theDevelopper 

thanks for the detailed information.

The `allavailabletasks` was not returning tasks of projects which haven't been set to progress. So those tasks have been missing. We just pushed a fix - should be deployed in 30 minutes. 

Can you validate the fix from your side?

Best & thanks for the help again.

Nils

**Comment by theDevelopper** [comment]
I looks like it does the job, so I can confirm the fix works.

Thank you very much 👍
