### ISSUE TITLE
auto pilot via API 

### ISSUE THREAD

**Issue by HalloBeverly** [awork-io/awork#19]
Hi, 
how can I activate the autopilot of a project  via API? Preferably directly in the waterfall mode.
Beverly

**Comment by IanBuck-dev** [comment]
Hey there,
seems like our autopilot endpoints did not find their way into the open api docs. I will check if we can add them there.
In the meantime you can use the POST endpoint to `/projects/{projectId}/autopilot` with the model:

`
{"type":"waterfall","alerts":[{"alert":"behind_schedule","enabled":true,"channel":"mail"},{"alert":"due_soon","enabled":true,"channel":"mail"},{"alert":"overdue","enabled":true,"channel":"mail"},{"alert":"behind_budget","enabled":true,"channel":"mail"},{"alert":"budget_reached_soon","enabled":true,"channel":"mail"},{"alert":"over_budget","enabled":true,"channel":"mail"},{"alert":"dead","enabled":true,"channel":"mail"},{"alert":"pending","enabled":true,"channel":"mail"}]}
`

If you want to disable certain alters, just put the "enabled" to `false`.

 To get the autopilot you can use GET `/projects/{projectId}/autopilot` and PUT, DELETE at the same route.

Best wishes
Ian

**Comment by HalloBeverly** [comment]
Hey Ian,
many thanks for your help. It works :-)
