### ISSUE TITLE
project template with automations via API.

### ISSUE THREAD

**Issue by HalloBeverly** [awork-io/awork#20]
Hi, 
I create new projects with the project template with automations via API. The project is okay. But the automations are unfortunately added 17 times to the project. What could be the mistake?
Thanks for a help
Beverly

**Comment by IanBuck-dev** [comment]
Hey Beverly,
that sounds like a weird behaviour. Do have an example for us so we can check? Best would be to give us a trace id, which can be found as a response header in the call to POST the project.

Else it would be great if you could tell us route, request body and workspace id so I can check what automations are setup for that project template. Please don't forget to remove any private data such as access tokens ;)

Best wishes
Ian

**Comment by HalloBeverly** [comment]
Hey Ian,


thanks for your response. I hope the following infos are fair enough.


https://api.awork.io/api/v1/projects


Post


{
   "projectTemplateId": "8ac618af-25e6-eb11-a7ad-00155d312181",
      "name": "886155 || [Amdre] : 'TestWerbekompanie || AMDRE GmbH - aworkTest Projekt",
    "description": "AMDRE GmbH - aworkTest Projekt
Format: 85x54 mm / 85x54 mm
Farbe: VS: Schwarz      RS: -
---------------------
Hier sind die Laufzettel hinweise",
    "startDate": "2021-09-09T20:35:35",
    "dueDate": "2021-08-27T13:00:00",
      "companyId": "47b3e19b-00f9-eb11-b563-dc984023d47e",
   "timeBudget":7200,
  "projectTypeId": "8ac618af-25e6-eb11-a7ad-00155d312181"  
}






{"workspaceId":"4eb09e67-39be-eb11-a7ad-00155d31294d","id":"91c064ac-9e11-ec11-b563-dc984023d47e"
Best wishesAlexandra

Original Message processed by david® 
Re: [awork-io/awork] project template with automations via API. (#20) 8. September 2021, 22:46 Uhr 
Von Ian ***@***.***> 
An awork-io/awork ***@***.***> 
Cc (2) HalloBeverly ***@***.***>|Author ***@***.***> 


Hey Beverly,
that sounds like a weird behaviour. Do have an example for us so we can check? Best would be to give us a trace id, which can be found as a response header in the call to POST the project.
Else it would be great if you could tell us route, request body and workspace id so I can check what automations are setup for that project template. Please don't forget to remove any private data such as access tokens ;)
Best wishes
Ian
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nilzzzzzz** [comment]
hi @HalloBeverly,

we tried to find the project with the name '886155 || Projekt' to check what happened. But we could not find any.

Could you create a project with the described issue and give us the traceid (you can find it in the response header of the call to create the project).

Thanks

Nils

**Comment by HalloBeverly** [comment]
Hi @nilzzzzzz 

I create a new project 

Thanks
Beverly

{"workspaceId":"4eb09e67-39be-eb11-a7ad-00155d31294d","id":"2572137d-6914-ec11-ae72-0050f26748f5","hasImage":false,"key":"1T","createdOn":"2021-09-13T08:06:29.9658513Z","createdBy":"7a9449c7-aee3-eb11-a7ad-00155d312181","updatedOn":"2021-09-13T08:06:29.965856Z","updatedBy":"7a9449c7-aee3-eb11-a7ad-00155d312181","createdByProjectTemplateId":"8ac618af-25e6-eb11-a7ad-00155d312181","projectType":{"isArchived":false,"icon":"shopping_cart","name":"Produktion","id":"8ac618af-25e6-eb11-a7ad-00155d312181"},"projectStatus":{"typeOrder":2,"isArchived":false,"type":"not-started","name":"Noch nicht gestartet","id":"2072137d-6914-ec11-ae72-0050f26748f5"},"tags":[],"resourceVersion":637671171901772795,"projectStatusId":"2072137d-6914-ec11-ae72-0050f26748f5","name":"123456 || [Kunde] : 'Projekt || Test awork","description":"Test awork\nFormat: 99x10 mm / 99x10 mm\nFarbe: VS: CMYK      RS: CMYK\n---------------------\nabcdef","startDate":"2021-09-13T10:06:00","dueDate":"2021-09-14T15:00:00","companyId":"1c52150b-6914-ec11-ae72-0050f26748f5","timeBudget":3000,"isBillableByDefault":true,"projectTypeId":"8ac618af-25e6-eb11-a7ad-00155d312181"}

**Comment by nilzzzzzz** [comment]
@sebastianrosch could you Check the trace?

**Comment by sebastianrosch** [comment]
Hi @HalloBeverly, I was able to find an issue that resulted in the automations being added several times when a project was created using the API. A fix has been deployed. Could you try it again? Thank you!

**Comment by HalloBeverly** [comment]
Perfect!  It works  ;-)

Thanks 
Beverly
