### ISSUE TITLE
"team POST/PUT model" - Schema Description Mistake in OpenAPI Docs

### ISSUE THREAD

**Issue by MurmeltierS** [awork-io/awork#22]
There seems to be missmatching descriptions in the OpenAPI Doc at "team POST/PUT model".

![image](https://user-images.githubusercontent.com/6160707/132926911-dbc93371-afda-4628-bd21-67ad3ed8b1ae.png)

**Comment by MurmeltierS** [comment]
Also would be helpful to note which icons and colors are supported.

Icons: 'attach_money' | 'poll' | 'golf_course' | 'all_inclusive' | 'portrait' | 'timeline' | 'transform' | 'description' | 'folder' | 'computer' | 'web' | 'phone_iphone' | 'cloud' | 'local_movies' | 'shopping_cart' | 'brush' | 'image' | 'camera_alt' | 'movie_creation' | 'public' | 'whatshot' | 'extension' | 'explore' | 'lock' | 'settings' | 'stars' | 'store' | 'school' | 'local_bar' | 'question_answer' | 'favorite' | 'work' | 'flight_takeoff' | 'map' | 'local_dining'

Colors: 'red' | 'coral' | 'yellow' | 'green' | 'teal' | 'arctic' | 'blue' | 'azure' | 'purple' | 'violet'

**Comment by nilzzzzzz** [comment]
Hi @MurmeltierS,

thanks for the feedback. I created a pr to improve the docs. Should go online the next days!

Best

Nils
