### ISSUE TITLE
/accounts/connectToSocialAccount & /accounts/disconnectToSocialAccount

### ISSUE THREAD

**Issue by MurmeltierS** [awork-io/awork#24]
The API Docs mention `/accounts/connectToSocialAccount` & `/accounts/disconnectToSocialAccount` endpoints at [`/accounts/{accountId}`](https://openapi.awork.io/#/Accounts/put_accounts__accountId_)

Sadly, those endpoints don't seem to be documented. Could you provide guidance on how to use these?

Thanks for your time.

**Comment by nilzzzzzz** [comment]
@MurmeltierS those endpoints are internal and should be hidden in the docs. I need to check why they are not. Those endpoints connect/disconnect google/Apple accounts to awork accounts for the login.

Can you tell us a bit more about your Use case and why you need those endpoints?

**Comment by MurmeltierS** [comment]
Hey,

seems reasonable.
We are currently working on a complete node-js wrapper for your API, mainly for internal purposes but planning to open-source it soon. Thats the reason I'm interested in those "odd" endpoints.

**Comment by nilzzzzzz** [comment]
Cool, thanks for the info! If you need any help, let me know.

**Comment by MurmeltierS** [comment]
Thanks. Will do.
