### ISSUE TITLE
Sandbox Environment

### ISSUE THREAD

**Issue by MurmeltierS** [awork-io/awork#25]
We are currently using a 14-days trial version workspace as substitute for a sandbox environment (coral-incredible-stars.awork.io) for our automated [JEST](https://jestjs.io/) tests. This is a little hideous though, as we have to create a new account every ~14 days.

Is there any kind of sandbox or testing environment that we could use for our continuous testing?

**Comment by nilzzzzzz** [comment]
@MurmeltierS we have no dedicated sandbox environment, just production, staging and develop.

We could create a dedicated workspace for that and we change it to forever free. You only need one user in that workspace or multiple?

Best

Nils

**Comment by MurmeltierS** [comment]
Hey Nils,

thanks for your answer.
I think at two users would be needed (e.g. for the new Multi User Assignment).
A dedicated workspace for us would be wonderful.

Feel free to reach out via mail if you want to discuss parts of this private: kevin.sieger@brand-boosting.de

Best regards
