### ISSUE TITLE
tags in a certain order

### ISSUE THREAD

**Issue by HalloBeverly** [awork-io/awork#26]
Hi,
I created 4 new tags with 

 POST
​/tasks​/{entityId}​/addtags

[
{
 "name": "Tag1",
 "color": "kblue"
}
,
{
"name": "Tag2",
 "color": "purple"
}
,
{
"name": "Tag3",
 "color": "yellow"
}
,
{
"name": "Tag4",
 "color": "red"
}
]

Unfortunately, the tags are not added to the task in that order.  The order there is 
Tag3, Tag4, Tag1, Tag2

It is possible to determine the order?

On this occasion, can you tell me the colors available?

Hope to hear from you soon
Beverly

**Comment by MurmeltierS** [comment]
This should be the supported colors, at least those are the one which are accessible via the front-end.
'red' | 'coral' | 'yellow' | 'green' | 'teal' | 'arctic' | 'blue' | 'azure' | 'purple' | 'violet'

**Comment by nilzzzzzz** [comment]
@HalloBeverly tags are unordered - so you cannot specify the order. 

Best

Nils

**Comment by HalloBeverly** [comment]
@nilzzzzzz that's not so nice but thanks for the info
@MurmeltierS Tanks much :-)
