### ISSUE TITLE
tags value zero

### ISSUE THREAD

**Issue by HalloBeverly** [awork-io/awork#27]
Hi,
I created 2 new tags with

POST
​/tasks​/{entityId}​/addtags

[
{
"name": "Tag1",
"color": "blue"
}
,
{
"name": "Tag2",
"color": "purple"
}
]

If the value of Tag2 is zero, the tag should not be created.

Hope to hear from you soon
Beverly

**Comment by nilzzzzzz** [comment]
hi @HalloBeverly ,

i do not understand what you mean. How can a tag be "zero"? Can you give us a traceid with an example?

Best

Nils

**Comment by HalloBeverly** [comment]
Hi @nilzzzzzz 

sorry for the misunderstanding. Sometimes there is no value for the tag in the database. The tag therefore does not have to be created. Can I prevent the creation of the tag in Json or do I have to do that beforehand.

I hope it is now expressed in a more understandable way.

Beverly

**Comment by nilzzzzzz** [comment]
Hi @HalloBeverly,

so you mean if the name of the tag is an empty string the tag should not be created?

Best

Nils

**Comment by HalloBeverly** [comment]
Yes ;-)

**Comment by nilzzzzzz** [comment]
We can check the validation. But then we will return 400 if you pass a tag with empty string and not just ignore that one. So you should remove the empty item from the array on your side definitly.

Thanks!

Nils

**Comment by HalloBeverly** [comment]
OK - Thanks for your help.
