### ISSUE TITLE
[Question]: orderBy query parameter

### ISSUE THREAD

**Issue by MurmeltierS** [awork-io/awork#31]
### What is your question?

It seems you are using an (undocumented) 'orderBy' query parameter in your frontend. Is this orderBy option widely supported by your API or limited to certain endpoints?

It seems to be a good fit to be used with your filtering and and pagination options.
Is there any reason this is undocumented territory?

**Comment by nilzzzzzz** [comment]
@MurmeltierS omg - we forgot migrating the documentation of that. Yeah - it's adopted everywhere. @Albtraumtaucher can you add that to the docs next week?

Best

Nils

**Comment by MurmeltierS** [comment]
Thanks @nilzzzzzz !

**Comment by IanBuck-dev** [comment]
Hey @MurmeltierS , we added the docs for ordering. You can find them here: https://developers.awork.io/ordering

Best wishes

Ian
