### ISSUE TITLE
Custom Fields for Time Entries

### ISSUE THREAD

**Issue by ttiedtke** [awork-io/awork#35]
### What is your question?

We are currently developing an Interface to an external billing tool. Is it possible to mark time entries as "transferred" to the external tool, maybe via custom fields for time entries?

**Comment by nilzzzzzz** [comment]
Hi @ttiedtke ,

we unfortunately do not support custom fields. But you could use the property "IsBilled" or?

Best 

Nils

**Comment by ttiedtke** [comment]
Yep, this would be possible. Would it be possible to set (via API) billable = false and isbilled (meaning is transferred for us) = true?

**Comment by nilzzzzzz** [comment]
@ttiedtke if the user is an admin you can do it, otherwise we validate/prevent it. 

Best

Nils
