### ISSUE TITLE
[Question]: shameless plug for our js api wrapper

### ISSUE THREAD

**Issue by MurmeltierS** [awork-io/awork#37]
### What is your question?

As mentioned previously in conversation with @nilzzzzzz we were developing a JavaScript wrapper for the Awork REST API for internal use.
After some final code cleanup, we decided to open source the wrapper.

If you are interested, have a look: https://www.npmjs.com/package/@brandboostinggmbh/awork-sdk

**Comment by nilzzzzzz** [comment]
@MurmeltierS nice! 

I will try that out and put that to our docs. 
One question - you released it under GPL3, any reason for that? That makes it hard for example to use it in our zapier integration.

Best

Nils

**Comment by MurmeltierS** [comment]
@nilzzzzzz Licensing decision was not made  be me, but you are absolutely right. i‘m going to see of we Van distribute under MIT

**Comment by MurmeltierS** [comment]
@nilzzzzzz version 1.0.7 and above now distributed under MIT

**Comment by nilzzzzzz** [comment]
@MurmeltierS aweseome! I will link the package on our dev docs page.
