### ISSUE TITLE
[Question]: Negative RemainingDuration for tasks

### ISSUE THREAD

**Issue by Maackuus** [awork-io/awork#39]
### What is your question?

Is there a possibility to transfer a negative remaining duration to the endpoint (PUT) ​/tasks​/{taskId} (Updates the task with the specified id.)?
We send negative durations but in the tasks view the value is zero for the remaining duration.

**Comment by sebastianrosch** [comment]
Hi @Maackuus, first of all sorry for the late response.
The model currently accepts a negative remaining duration, but the frontend and other parts of the application treat it as 0 in this case. For example, when a user adds, updates or deletes a time entry for the task, it will be set to 0 in the case it's negative. So for consistency reasons, we shouldn't accept negative values in the first place, but that's not enforced at the API at the moment.

Can you explain what a negative value means for you and what you want to do with it?

**Comment by Maackuus** [comment]
Hi @sebastianrosch,
the remaining budget should be an overview so that the user can see how much time he has already spent on a task. If this is negative, it should therefore be possible to see how much time has already been used over the planned time.

**Comment by sebastianrosch** [comment]
Hi @Maackuus unfortunately this is not supported at the moment. If you create time entries for the task, the sum would show up in the task details, maybe that helps.
