### ISSUE TITLE
Which user how much time work on this project?

### ISSUE THREAD

**Issue by ybaskayadevops** [awork-io/awork#40]
### What is your question?

I want to use your API and make a program for our company.

https://api.awork.io/api/v1/projects this api end point wWhich I am using, 
but  I can not find in this API end point answer for the below question?

**Which user how much time work on this project? Can you add this to this API end point?**

**To better understand my question. I add a picture for my project.**

![awork_3](https://user-images.githubusercontent.com/52202354/148937347-1316ecde-9b1a-4377-a9e5-5b2308cdad7a.png)

![awork_2](https://user-images.githubusercontent.com/52202354/148934949-76a27b0e-6463-4c31-a2c6-bcfac6669c67.png)
`

**Comment by marcelotedeschi** [comment]
Indeed, having it pre-calculated would be better for performance, but that's a quite specific use case which unfortunately is not covered in our API currently.

But, nice to hear you already managed!

If you are thinking of performance, and taking a look in the code you shared above, I could think of one improvement:

1. Creating a Dictionary of the `.Sum()` of each user (member) per project in `TimeEntryList`.
2. Set the `totalWorkTime` per `member` (as in your code) but using the Map instead.

This way you only iterate over the items of `TimeEntryList` _once_ and not every time for each member of each item in the `list`, since you can access the data directly from the dictionary!

**Comment by ybaskayadevops** [comment]
Hi,

Thanks for your advices.

I already changed above code.  
It was quick writing code that time :)).

It is now like that.

![image](https://user-images.githubusercontent.com/52202354/148979732-f7560043-e9ec-4373-ab21-2c5f783a9b4d.png)

but I did not understand what you want say .  Also I put timer it is taking  200 ms.

How can use dictinary here. Maybe it will better performance. learning is always good. :))


   var entity=  (from t in TimeEntryList
   group t by new { t.projectId, t.userId }
   into grp
   select new
   {
       grp.Key.projectId,
       grp.Key.userId,
       duration = grp.Sum(t => t.duration)
   }).ToList();


           

  foreach (var item in list)
  {
      foreach (var member in item.members)
      {
          member.totalWorkTime = entity.Where(x=>x.projectId==item.id && x.userId==member.userId).Select(x=>x.duration).FirstOrDefault();
      }
  }



But The big problem is I am calling 8 API calls to my project. As in the picture. Maybe a faster way

![image](https://user-images.githubusercontent.com/52202354/148975677-67816187-b323-415f-b0ec-b95aae5e7613.png)

Thank you for your help.

**Comment by ybaskayadevops** [comment]
Hi Marcelote,

It is not what I want to achive. With your select I can calculate one project one user id. 
I did like below code. 

I made projectId+userid as key. 

  var entity = (from t in TimeEntryList
                              group t by new { t.projectId, t.userId }
                into grp
                              select new
                              {
                                  Key = grp.Key.projectId + grp.Key.userId,
                                  duration = grp.Sum(t => t.duration)
                              }).ToList().ToDictionary(ele => ele.Key.ToString(), ele => ele.duration);

then

                       string key = item.id + member.userId;
                        try
                        {

                            member.totalWorkTime = entity[key];
                        }
                        catch (Exception ex)
                        {

                        }

after your advice Yesterday I made like that. I asked  to learn anyting special.



Have a nice day.

**Comment by marcelotedeschi** [comment]
Ah, perfect, that's what I mentioned on `PS1`. Really cool ! Let me know if you have any further questions :)
