### ISSUE TITLE
How can I get Compony Logo?

### ISSUE THREAD

**Issue by ybaskayadevops** [awork-io/awork#43]
### What is your question?

Hi Awork Team

I wanted to get compony Logo from api. But I can't find from documentation. There is no Company Logo in this end point.

https://openapi.awork.io/#/Companies/get_companies

**Comment by nilzzzzzz** [comment]
Hi @ybaskayadevops,

the endpoint is documented here: https://openapi.awork.io/#/Images/get_files_images__entityName___entityId_

Best regards

Nils

**Comment by ybaskayadevops** [comment]
Hi ,

I knew but Have you got any sample. I need only Log for the company.

**Comment by nilzzzzzz** [comment]
What do you mean? It's a normal get request to api.awork.io/api/v1/files/images/companies/{id}
{id} <- id of the company

**Comment by ybaskayadevops** [comment]
Ok. I took my answer. I need this url.

**Comment by nilzzzzzz** [comment]
cool!
