### ISSUE TITLE
[Bug]: Links in the ticket are not displayed correctly when created via Rest API

### ISSUE THREAD

**Issue by TobiasDuelli** [awork-io/awork#44]
### What happened?

When I create a ticket using the REST API, the links in a ticket are not displayed correctly. However, as soon as I put the focus on the description field, the links are displayed correctly. Email links (i.e. mailto:) are always displayed correctly.

Unfocused links:
<img width="756" alt="Screenshot 2022-02-02 at 12 50 36" src="https://user-images.githubusercontent.com/26904930/152148348-6cb81b68-98d0-4a6f-9509-c94efe9310ea.png">

Focused links:
<img width="756" alt="Screenshot 2022-02-02 at 12 51 51" src="https://user-images.githubusercontent.com/26904930/152148529-08274cc5-ea3b-4f0e-a48c-9f4fc8441ab3.png">

### What is the trace id of the call?

https://antiquewhite-sensational-superstars.awork.io/projects/1682771f-4dfb-eb11-b563-dc984023d47e/tasks/board/(modal:a8ef546c-1684-ec11-a506-38563d686c6e/details)

**Comment by nilzzzzzz** [comment]
Hi @TobiasDuelli,

can you please give us the trace-id (in the response header) of the call to create the task? Then we can have a look.

Thanks

Nils

**Comment by TobiasDuelli** [comment]
The trace-id is 237bf34f26c9c3a6

**Comment by nilzzzzzz** [comment]
@TobiasDuelli this was the trace you took from a call made by the awork Ui and not from the api call you made to create the task or? It is a get call to get the projects and the client id is our internal one.

**Comment by TobiasDuelli** [comment]
Sorry for the confusion that was my mistake. This is the trace-id from the response header: 20b239c0a05342f2

**Comment by nilzzzzzz** [comment]
@TobiasDuelli i can confirm the strange behaviour - my colleague @OmarASelim is looking into that.

**Comment by OmarASelim** [comment]
Hi @TobiasDuelli Thanks for reporting the issue. The fix has been deployed. You can now double check :)
