### ISSUE TITLE
[Question]: More Webhook information in Webhook-Log

### ISSUE THREAD

**Issue by timkley** [awork-io/awork#45]
### What is your question?

We are currently writing an integration which will use the webhooks from awork.

Unfortunately we are seeing errors (status code 400 sent by our server, apparently) for which we can't find logs on our side. To better debug this it would be of great help if the log would provide at least the server message sent with the response, better yet: the complete response object.

Another thing I've found: testing webhooks from the UI always triggers a `405 Method Not Allowed`. It seems like the test functionality does not use a `POST` request?  
If possible it would also be great if we could choose which event to test, this would greatly reduce errors because of typos in the event name.

Thanks up front :)

**Comment by timkley** [comment]
Adding to this, the example for a bearer token is misleading because IMO it suggests the correct header would be `Authentication` when it really is `Authorization`. Changing this would probably help first time users :)

![Screenshot 2022-02-14 at 12 43 12](https://user-images.githubusercontent.com/6104339/153858339-540381ad-a757-41b6-b2c0-7385f162f85a.png)

**Comment by nilzzzzzz** [comment]
Hi @timkley, could you send me your server address? If it's a secret you can send it to nils@awork.io. Then i check the logs.

The test call is doing a post call to the webhook address. You have a trace id for the test call?

**Comment by nilzzzzzz** [comment]
> Authorization

Oh, damn. Where you have you found that?

**Comment by timkley** [comment]
@nilzzzzzz I actually don't have any issues anymore, these were just my findings on using webhooks. This is the trace ID for my most recent test: `2ad093965033d0f9 ` which results in 405, although the webhook itself works.

Regarding the "typo", this is the webhook modal when adding / editing a webhook:

![Screenshot 2022-02-14 at 14 09 25](https://user-images.githubusercontent.com/6104339/153870240-d0d758f6-661c-4edf-aa28-1a353d9f4b38.png)

**Comment by nilzzzzzz** [comment]
@timkley thank you. The "wrong" text is fixed and will be rolled out the next hours. 

The other issue i cannot repro. I tested the webhook ("webhook testen" button) and it posted correctly to my test site (webhook.site) 

Best regards

Nils
