### ISSUE TITLE
Welche Daten können über die API von awork ausgegeben werden?

### ISSUE THREAD

**Issue by TSchaefer78** [awork-io/awork#48]
### What is your question?

Hallo, 
ich habe eine Frage zur Datenabfrage über die API von awork. 
Wir ziehen uns Daten zu den Projekten aus awork. Das funktioniert mit der URL: https://api.awork.io/api/v1/projects und dem hinterlegten API-key.
Nun möchte ich auch auf die Benutzerdaten, Daten zu Aufgaben und Daten zu hinterlegten Einstellungen zugreifen. 
Wie komme ich an diese Daten ran?

MfG Tom Schäfer

**Comment by timkley** [comment]
@TSchaefer78 du kannst unter https://openapi.awork.io/ alle verfügbaren Endpoints sehen.
