### ISSUE TITLE
[Question]: Undocumented endpoints /stats/workhours

### ISSUE THREAD

**Issue by timkley** [awork-io/awork#49]
### What is your question?

Hi awork,

we are currently trying to get the login timestamp as seen in the time-entries view.

It seems, this info is available under the endpoint `/me/stats/workhours?date=...`. If I try to access this endpoint from our client application I unfortunately get the error "No permissions to access this endpoint.".

Would it be possible to access this endpoint from a client application? If possible it would be great if this was accessible under the `User` ressource so we can query this data for every user.

Thanks up front :)

**Comment by IanBuck-dev** [comment]
Hey @timkley ,
we have quite some endpoints which are for internal use only and offer additional features for our webapp and this is one of them. We currently do not plan on making this endpoint public available as it is not a core feature.

You could as an alternative just query the timetrackings of each user of the day to check the worked times.

Best wishes
Ian
