### ISSUE TITLE
What is the best authoriziation to access project tasks in a custom (google sheets) dashboard for a client

### ISSUE THREAD

**Issue by filmwirt** [awork-io/awork#5]
Dear awork team,
I'd like to use projecttasks endpoints to prepare a custom dashboard for a client. However, different from project level data where I've sucessfully managed to generate a google sheet dashboard, a generic API key doesn't seem to work. 
What kind of authorization can I use to access the data - ideally through google scripts - so that clients can see the dashboard/table but don't get access to the full data detail?
Thanks and regards,
Hendrik

**Comment by nilzzzzzz** [comment]
Hi Hendrik,

why is the generic api key not working? The endpoint me/projecttasks should give you all tasks which your user is allowed to see. If you use a generic api key, you should get all. 

How to solve that in the google sheet i have no idea, probably you can give your customers read only access so they cannot "grab" your api key?

Best

Nils

**Comment by filmwirt** [comment]
Hi Nils,

thanks for you feedback. I obviously didn’t get that even in the case of a generic api key I needed to at the “me” to the generic path. Now everything works and I’m sure I’ll find an easy solution for the read only access.

Thanks again and regards,

Hendrik
