### ISSUE TITLE
[Question]: Generelle Einrichtung der API

### ISSUE THREAD

**Issue by Jens-emetriq** [awork-io/awork#51]
### What is your question?

Hallo zusammen, 

der erste Versuch via google sheets ist kläglich gescheitert und im Grunde auch keine Option da wir google sheets im Unternehmen nicht einsetzen.

Gibt es eine Möglichkeit mal einen Telefontermin zu organisieren bei dem ihr unterstützen könnt? 

Was will ich eigentlich:
Mittels der Exportfunktion im Projektbereich erhalte ich nicht die Start und Enddaten der Projekte, die benötige ich aber für meine Auswertung (Controlling). Ich sehe aktuell keine andere Möglichkeit als über die API, außer der Standard-Export wird "erweitert". API mäßig bin ich wissensmäßig auf null.

Meine Frage hatte ich bereits im Helpcenter platziert und wurde dann an Euch als Entwickler verwiesen.

Danke für eure Hilfe,
Jens (emetriq GmbH)

**Comment by timkley** [comment]
@Jens-emetriq

Hi Jens, ich bin nicht von awork, wir haben jedoch mittlerweile einiges an Erfahrung mit der awork-API sammeln können und sind auch sonst im Bereich der Invididual-Entwicklung zuhause. Sofern awork nicht direkt unterstützen kann melde dich gerne bei mir :-)

**Comment by Jens-emetriq** [comment]
Hallo zusammen, auf wundersame Weise ist jetzt das Start und Enddatum beim Projektdownload hinzugekommen, vielen Dank! 

@timkley danke dir für dein Angebot. Falls ich das Thema API nochmal aufbringen muss, denk ich an dich.
