### ISSUE TITLE
[Question]: Frage zur API Filtersetzung /timeentries (IDs / Datetime)

### ISSUE THREAD

**Issue by JanLuen** [awork-io/awork#53]
### What is your question?

Hallo,

ich benötige Unterstützung bei der API /timeentries Filterfunktion. Ziel ist es mittels der Filterfunktion die Zeiteinträge einzelner Projekte zu betrachten. Der Filter funktioniert bei int, boolean und teilweise Strings. Bei Id's und Datetime erscheint jedoch die Message: "invalid-filter-or-order", "Something is wrong with the given 'filterby' expression.". 

Erfolgreich:	/timeentries?filterby=note%20eq%20%27Testbeschreibung%27

Fehler:		/timeentries?filterby=projectId%20eq%20%27000f215e-xxxx-ec11-xxxx-38563d6e4a56%27

Die Trace-ID für den Projekt-Filter lautet „248307f30689ca81“.

Vielen Dank im Voraus.

JanLue

### Do you have a trace id of the call?

248307f30689ca81

**Comment by nilzzzzzz** [comment]
Hi @JanLuen,

bei Guids & Datetimes müssen die filter jeweils den Typen as prefix haben. Beispiel: /timeentries?filterby=projectId eq guid'12345678-aaaa-bbbb-cccc-ddddeeeeffff'

Ich hoffe das hilft dir.

Viele Grüße

Nils
