### ISSUE TITLE
API access withouth specific user

### ISSUE THREAD

**Issue by denn1z** [awork-io/awork#55]
Moin moin,

I would like to generate a web form where users(without an awork User) in my company can generate a Task/Ticket for a specific project. Is there a way to do like that as I have checked the docs you are only able to do so with an awork user account?
If this is not the case I would alternatively use the e-mail, but I would prefer to use the API :)

Best regards
Dennis

**Comment by nilzzzzzz** [comment]
Hi @denn1z,

this is no problem. It is described here https://developers.awork.io/authentication how to do it. You can create a user agnostic token and use that one to create a task.
Does that help?

Best 

Nils

**Comment by denn1z** [comment]
Thanks @nilzzzzzz ,
you mean `POST https://api.awork.io/api/v1/accounts/tokenredirect_uri={redirect_uri}  &grant_type=authorization_code  &code={code}Authorization: Basic Base64({client_id}:{client_secret})`
like that?

**Comment by denn1z** [comment]
Ok thanks @nilzzzzzz,
That means for example the base request looks like that:
`myApp.config.globalProperties.$client = axios.create({
    baseURL: "https://api.awork.io/api/v1",
    headers: {
        Authorization: `Bearer ${apiKey}`,
    },
});`
and then you just use the endpoint rite?

Best regards
Dennis

**Comment by nilzzzzzz** [comment]
@denn1z yes.

**Comment by denn1z** [comment]
Thanks @nilzzzzzz

**Comment by denn1z** [comment]
@nilzzzzzz I found it, thanks for your help!
