### ISSUE TITLE
What is the most elegant way to discover the latest updated/created tasks 

### ISSUE THREAD

**Issue by PeterKuhnle** [awork-io/awork#56]
### What is your question?

I need to read all changed/updated (project) tasks to a sync-database. Therefore I will poll for latest changes periodically. From the API documentation, I see the opportunity to iterate all projects and then use /GET projetcs/{projectid}/projecttasks?filteryby=updatedOn ge datetime'xx' for latest changed/updated projecttasks. 
Is there a way to avoid the client-side projects iteration?

**Comment by IanBuck-dev** [comment]
Hey Peter,

to get all tasks the current user is allowed to see, you can simply call the me/allavailabletasks and then add the filter baseType eq 'projecttask' or 'private' (GET /me/allavailabletasks?filterby=updatedOn ge datetime'xx' and baseType eq 'projecttask')
or you use the GET /me/projecttasks endpoint, which has this projecttask filter included.

Hope this helps!
Ian

**Comment by PeterKuhnle** [comment]
Thank you!
