### ISSUE TITLE
How to detect new/updated comments via API

### ISSUE THREAD

**Issue by PeterKuhnle** [awork-io/awork#57]
### What is your question?

Hi,
when I want to sync latest tasks via the API, I can use the **updatedOn** attribute of a task. This is not true, when a comment is added or updated, which I - in my scenario - have to regard as a change in the task.
What are my possible methods to discover tasks, that have been updated by comments without iterating through all possible /tasks/{entityId}/comments?

Regards, Peter

edit: it seems so that also adding/removing tags, changes in list memberships and likely other view data changes need separate techniques for discovery. R P

**Comment by nilzzzzzz** [comment]
Hi @PeterKuhnle,

for the syncing there is unfortunately right now no other way.
An alternative would be depending on your infrastructure to use our webhooks. Would that be an option?

Best

Nils

**Comment by nilzzzzzz** [comment]
@PeterKuhnle ah we only support comment created. This is the issue?  For tag changes and list membership changes the task updated webhook will fire, because those properties are part of the task response model. 

We have a timestamp on the models. It is called `resourceVersion`.

**Comment by PeterKuhnle** [comment]
Thanks! The tick-based resourceVersion works and works in filterby/orderby properly and seem to reflect all changes in the tasks response. Webhooks for comments do their basic job. May I place a fetaure-request for **task_comment_deleted** and **task_comment_updated** resp **task_comment_changed**? Regards, Peter

**Comment by nilzzzzzz** [comment]
Sure, i add it to our list for the upcoming cycles, thanks for the feedback!

**Comment by PeterKuhnle** [comment]
Thank you for your excellent developer support!
