### ISSUE TITLE
[Question]: Endpoint /users/{userId}/timeentries/last return 404

### ISSUE THREAD

**Issue by timkley** [awork-io/awork#58]
### What is your question?

The [mentioned endpoint](https://openapi.awork.io/#/TimeEntries/get_users__userId__timeentries_last) unfortunately currently returns a 404 Not Found error.

Since it's documented on the public available page I assume that's an error?

On the OpenAPI-page is also the 404 error:

<img width="962" alt="Screenshot 2022-07-07 at 11 38 24" src="https://user-images.githubusercontent.com/6104339/177744001-23256d6e-d78c-487d-9bb8-76498a07f895.png">

### Do you have a trace id of the call?

2a9a79d3c9b475f1

**Comment by nilzzzzzz** [comment]
Hi @timkley,

we released the fix and verified that the endpoint is now reachable.

Best

Nils

**Comment by timkley** [comment]
Thanks @nilzzzzzz, can confirm that it now works, thanks for the quick fix 👍🏻
