### ISSUE TITLE
[Question]: Get the current time tracking state

### ISSUE THREAD

**Issue by nfech01** [awork-io/awork#59]
### What is your question?

We don't see any possibility to get the current time tracking state of a user.
Is it possible to check if a user currently tracks? A simple state: time_tracking: 'running', 'stopped' would be sufficient.

Thank you very much.

**Comment by IanBuck-dev** [comment]
Hey,
you should be able to get the currently running timetracking from the GET /me/timeentries/last or GET /users/id/timeentries/last endpoint. This returns the last timetracking of the user. If only the start date and time is set, so duration is 0 and no end date or time set, the timetracking is currently running.

Hope this helps!
Ian
