### ISSUE TITLE
Non-Destructive Task updating

### ISSUE THREAD

**Issue by timkley** [awork-io/awork#6]
Currently, when you are using the endpoint to update a task (PUT `/tasks/{entityId}`) all values which are omitted in the request are treated as if they are present but empty.

**Example:**

GET `/tasks/{entityId}` (I left out some response data)

```
{
  "id": "e230d4d0-2691-eb11-a607-00155d314496",
  "plannedDuration": 28800,
  "name": "Test task",
  "isPrio": false,
  "dueOn": "2021-03-31T16:00:00Z"
}
```

PUT `/tasks/{entityId}`

```
{
  "plannedDuration": 28800,
}
```

☝ this throws a validation error that "Name" is required even though I don't want to change it.

---

PUT `/tasks/{entityId}`

```
{
  "name": "Test task",
  "plannedDuration": 28800,
}
```

This works, but if i now GET the task again this is the response:

```
{
  "id": "e230d4d0-2691-eb11-a607-00155d314496",
  "plannedDuration": 21600,
  "name": "Test task",
  "isPrio": false
}
```

It is missing `dueOn` because it was unset during the PUT request. To mitigate this issue we are getting the task data and sending the whole payload back to the API after we changed the relevant fields. Since this happens in a queue system there could be possible race conditions of the task get's updated by a user in the meantime.

Is there some way to tell the API to just update the fields which are sent with the request?

**Comment by nilzzzzzz** [comment]
Hi @timkley,

thank you for reaching out to us. 
We currently only support PUT calls for updating resources and currently not plan to also support PATCH operations. 

If you run into race conditions i see no other way than implementing some kind of locking/transaction mechanism on your side.

Out of interest, what is your use-case you are implementing?

Best 

Nils

**Comment by timkley** [comment]
Hi @nilzzzzzz,

thanks for getting back to me!

I don't expect that we'll run into actual race conditions for this use case, it's just something we noticed when developing our companion application.  
Since the problem could be caused by a user editing the task I don't see any possibility to lock a task, but as said I don't expect we run into actual issues.

We have clients that book a fixed amount of hours every month. Since we don't know up front how (on a task/project basis), when (speaking in actual date) and where (user) these hours will be used we add a blocking task for every project member.

Example: User A gets a task with 30h from March 1st until March 31st.

For planning/reporting/invoicing it's not suitable to track directly on that task which means that the around mid month the capacities of all project members skyrocket since those 30h are compressed into half the time.

Our companion application identifies these tasks by a special tag and recalculates the `plannedDuration` based on weekdays left until `dueOn` is reached.

Cheers, Tim

**Comment by nilzzzzzz** [comment]
@timkley that sounds interesting. Thank you for the detailed insides!
