### ISSUE TITLE
How do I get the available icon-names for taskstatuses?

### ISSUE THREAD

**Issue by PeterKuhnle** [awork-io/awork#60]
### What is your question?

Dear team,
several by-name referenced read-only entities like taskstatuses/icons or tags/colors seem not to be queryable via the api. Are there hidden endpoints or docs for getting their names?
Regards, Peter

**Comment by IanBuck-dev** [comment]
Hey Peter,
we have some endpoints in our OpenAPI description that return the possible string values:
https://openapi.awork.io/#/ProjectTypes/get_projecttypes_icons
https://openapi.awork.io/#/TaskBundles/get_taskbundles_icons
https://openapi.awork.io/#/TypeOfWork/get_typeofwork_icons

For the other entities, I guess we should also add endpoints or add it to our docs. I'll create a dev task for that. For now:
The allowed tag colors are: `"red", "coral", "yellow", "green", "teal", "arctic", "blue", "azure", "purple", "violet"`
The allowed icons for task statuses are:
```
supportedIcons = [
    'circle_with_color',
    'arrow_forward',
    'phone',
    'mic',
    'laptop',
    'remove_circle_outline',
    'flag',
    'live_help',
    'list',
    'add',
    'keyboard',
    'print',
    'photo_camera',
    'movie',
    'pause',
    'bug_report',
    'whatshot',
    'search',
    'question_answer',
    'remove_red_eye',
    'settings',
    'review',
    'thumb_up',
    'done'
  ]
```

Hope this helps ;)
Best wishes
Ian

**Comment by PeterKuhnle** [comment]
Ian, thanks a lot. For the time being, I will use the constants. 
Best regards, Peter
