### ISSUE TITLE
[Question]: Zusammenfassung aller Zeiteinträge für mehrere Projekte mit einem Call

### ISSUE THREAD

**Issue by MircoKoenig** [awork-io/awork#61]
### What is your question?

Hallo zusammen,

es gibt ja die Möglichkeit, für ein Projekt die Zeiteintrage zu erhalten mit https://api.awork.io/api/v1/projects/{id}/timeentries. 
Meine Frage dazu:
- Ist es möglich, diese Anfrage für mehrere Projekte auf einmal durchzuführen, um z.B. für alle abgeschlossenen Projekte eines Monats die Zeiteinträge zu erhalten (dies im besten Fall in einem Array mit den einzelnen Projekten als Feldern)?

Vielen Dank im Voraus

Mirco

**Comment by sebastianrosch** [comment]
Hallo @MircoKoenig,

es gibt einen weiteren Endpoint, mit dem du das evtl. erreichen kannst: `/timeentries`

Hier kannst du alle time entries abrufen und dabei nach Projektfeldern wie Status filtern. Bedenke aber dass hier alle Zeiteinträge geladen werden die dem Filter entsprechen und die bei großen Datenmengen evtl. viele Pages abrufen musst.

**Comment by MircoKoenig** [comment]
Hallo @sebastianrosch, 

danke für die schnelle Antwort. 
Wenn ich mehrere Anfrage an die Schnittstelle durchführe um an alle Seiten zu gelangen (oder die Zeiteinträge der Projekte nacheinander abfrage), muss zwischen den Anfragen ein zeitlicher Delay sein, um das System nicht zu überlasten bzw. fälschlicherweise als Spam erkannt zu werden?

**Comment by IanBuck-dev** [comment]
Hallo @MircoKoenig ,
wir erlauben normalerweise 100 Requests pro Minute, dass heißt du solltest dir hier eigentlich keine Gedanken machen müssen. Nochmal zu deiner Frage: Du kannst den Endpoint `GET /timeentries` benutzen und dort direkt per `?filterby=...` filtern, ohne das In-memory zu machen. Hier findest du mehr Infos zum Filtering: https://developers.awork.io/filtering

Für timeentries auf abgeschlossenen Projekte sollte das sein: GET `/timeentries?filterby=Project/ProjectStatus/Type eq 'closed'`

LG
Ian
