### ISSUE TITLE
[Question]: RSS Feed / mailing list for API changes

### ISSUE THREAD

**Issue by timkley** [awork-io/awork#62]
### What is your question?

We where unfortunately unpleasantly surprised by the last API change. I can't seem to remember a mail which informed about it.

Since https://developers.awork.io/api-changes exists: would it be possible to provide a RSS feed for this site? Or a separate mailing list for API changes?

Thanks up front :)

**Comment by sebastianrosch** [comment]
Hi @timkley
could you explain which API changes you are referring to?

Unfortunately we don't have an RSS feed or any structured way of getting this information. I will add it to our feedback list. Thanks for the suggestion.

**Comment by timkley** [comment]
@sebastianrosch in this case it was the removal of `CapacityPerWeek` from the user model. No big deal but it totally slipped my radar. Maybe you even sent out an email and I just didn't see it.

But some kind of structured way would be really lovely, thanks for adding it to your list 👍🏻

**Comment by timkley** [comment]
Thank you!
