### ISSUE TITLE
[Question]: OpenAPI / Swagger.json / Postman collection

### ISSUE THREAD

**Issue by timkley** [awork-io/awork#63]
### What is your question?

To quickly test things it would be great if https://openapi.awork.io/ would also provide a standardized `swagger.json` or a separate Postman collection.

The json called from the OpenAPI URL (https://awork-function-swaggercombine-global.azurewebsites.net/api/swagger-combine) unfortunately cannot be imported into Postman :(

**Comment by sebastianrosch** [comment]
Hi @timkley,
importing this URL indeed throws in error in Postman. It worked in Insomnia, which most of us are using instead. I will create a bug ticket to see if we can fix the issue with Postman. Thanks for reporting this.

**Comment by timkley** [comment]
@sebastianrosch I also use Insomnia but miss features like predefined variables. Currently I have to set the Bearer token on every request, which is very cumbersome 🙈 

Thank you for the fast reply :)

**Comment by nilzzzzzz** [comment]
@timkley you can set the bearer token with insomnia on every request (i am doing that also that way..). Just set for an environment default headers. https://www.npmjs.com/package/insomnia-plugin-default-headers

Anyways, we try to fix the postman issue. ;)

**Comment by nilzzzzzz** [comment]
@timkley the issue is fixed. Thanks for bringing that up - can you retest on your side?

**Comment by timkley** [comment]
@nilzzzzzz can confirm that it works, thanks!

Also thanks for the tip about the default headers plugin, works like a charm ❤️
