### ISSUE TITLE
How to suppress user notifications when background jobs via API are performed?

### ISSUE THREAD

**Issue by PeterKuhnle** [awork-io/awork#64]
### What is your question?

In my case, I want to migrate tickets from jira to awork as they are the base for time-tracking. Lot's of notfications are fired, especially when comments are (API-) added. I would like to suppress that notifications as there is no benefit for any user to receive them. In this case, general user-individual notification disabling does not make sense.
Regards, Peter Kuhnle

**Comment by nilzzzzzz** [comment]
Hi @PeterKuhnle,

unfortunately we have right now no way to suppress those notifications. I created a feedback for our feature backlog.

Best

Nils

**Comment by PeterKuhnle** [comment]
Thanks Nils. Looking forward to get it in a future release.
