### ISSUE TITLE
Wie so funktioniert   'Authorization: Bearer  $token'  mit GET, aber nicht mit PUT oder POST ?

### ISSUE THREAD

**Issue by wwdto** [awork-io/awork#66]
### What is your question?

Es wäre gut, wenn es mehr konkrete Beispiele für komplette  Aufrufe gäbe, die Doku ist m.E. aktuell  leider nicht ausreichend.

An die anderen hier im WorkSpace: Wenn es funktioniert: sendet bitte auch den funktionieren en Code  nicht nur die Probleme -danke  - wwdto

Hier mein Problem:

### Do you have a trace id of the call?

Das hier funktiniert:
 CURL -X GET https://api.awork.io/api/v1/timeentries -H 'Authorization: Bearer eyXXXX'

aber nicht mit POST:

endpoint:  timeentries/setbilled
Variante#1: ID  hinter endpoint

CURL -X POST https://api.awork.io/api/v1/timeentries/setbilled/a6d47c6d-1b38-ed11-ae83-38563d6848fe -H 'Authorization: Bearer eyXXXX'

endpoint:  timeentries/setbilled
Variante #2 
Variante#1: ID  als --data Strindg, variante mit [ ]   als Array ebeenfalls getestet

curl -X POST 'https://api.awork.io/api/v1/timeentries/setbillable' -H 'Authorization: Bearer eyXXXX' -H 'Content-Type: application/json' --data-raw { "ids" : "a6d47c6d-1b38-ed11-ae83-38563d6848fe"}

**Comment by sebastianrosch** [comment]
Hallo @wwdto, ich schaue mir das mal an. Ich habe erstmal deinen Token aus der Nachricht entfernt.
Kannst du bitte noch die trace-ids der jeweiligen Requests hinzufügen die fehlschlagen? Dann kann ich den Fehler schneller finden. 

Danke.

**Comment by sebastianrosch** [comment]
So wie es aussieht ist dein POST Request Body nicht ganz richtig. Den `POST /timeentries/setbilled/id` endpoint gibt es nicht, es muss `POST /timeentries/setbilled` heissen, und dann mit einem body nach diesem Format:

```json
{
  "ids": [
    "3fa85f64-5717-4562-b3fc-2c963f66afa6"
  ]
}
```
In deinem Beispiel ist `ids` ein string, es muss aber ein string array sein.

Das steht so eigentlich auch in der API Doku, aber sag gerne wenn wir hier etwas besser beschreiben können.
<img width="1437" alt="Screenshot 2022-09-20 at 20 55 37" src="https://user-images.githubusercontent.com/2076369/191341447-ad412d7f-4605-4d74-8da4-766e1c54564d.png">

**Comment by wwdto** [comment]
Halo Sebastina,
danke fürs kümmern.

JA , dachte ich mir schon, war ein Versuch -( you never know…. )
Postman hat mir mit  dem JSON -Body wie in der Doku gezeigt  Fehler  gemeldet, bis ich den JSON-String so angepasst hatte wie im meiner Anfrage gezeigt. 

Aktueller Stand: 21.13h 

curl -s -L -X POST 'https://api.awork.io/api/v1/timeentries/setbilled' \
-H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjNjAxNzIzNi1jM2M3LTQxZWMtYmYwYy01MDJmMmQyYWYwNWMiLCJuYW1lIjoid3dkdG9AbWFjLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Ind3ZHRvQG1hYy5jb20iLCJpaWQiOiJjNjAxNzIzNi1jM2M3LTQxZWMtYmYwYy01MDJmMmQyYWYwNWMiLCJ3aWQiOiJhZmJmMzM4YS0xMDI1LWVkMTEtYWU4My0xNGNiNjUyNzVlNWIiLCJ1aWQiOiJjNmJmMzM4YS0xMDI1LWVkMTEtYWU4My0xNGNiNjUyNzVlNWIiLCJ0b2tlbl91c2FnZSI6ImFjY2Vzc190b2tlbiIsImp0aSI6IjE2MWRiMmE1LTJkYmEtNGRmNy05YWRiLWI2ZmU2YWJhNzcwOCIsImNmZF9sdmwiOiJwcml2YXRlIiwic2NvcGUiOiJvZmZsaW5lX2FjY2VzcyIsImF1ZCI6ImF3b3JrLmlvIiwiYXpwIjoiRDhDQUNGQTVGMEZDNDg4REJEQjUyNDlCRCIsIm5iZiI6MTY2Mjc0NDUwMSwiZXhwIjoxNjYyODMwOTAxLCJpYXQiOjE2NjI3NDQ1MDEsImlzcyI6Imh0dHBzOi8vYXdvcmsuaW8vIn0.lpFLe0CQxcCnaDX-_YB-c5QFKA4_0tu-cNztVkXpj38' \
-H 'Content-Type: application/json' \
-H 'Cookie: .AspNetCore.Antiforgery.9TtSrW0hzOs=CfDJ8NyZstk5bTlOmwuylEAF6SZAiZ3diFfTsyZ4WOt-KvWI9y4c6z_Wndwykk60SJYMD9J0gIX7_cnTUxxyMw-pcTRwO5WGA0B5HSEgqdY7UwEIHHVjf8QK6edONg1SHMgW7r5V-fKUs8aQoC6S6Fz__YQ' \
--data-raw '{
  "ids": [
    "a6d47c6d-1b38-ed11-ae83-38563d6848fe"
  ]
}’
-----------
RESPONSE
{
    "message": {
        "code": "unauthorized"
    }
}

Postman Console:
POST https://api.awork.io/api/v1/timeentries/setbilled
401
25 ms
Network
addresses: {…}
tls: {…}
Request Headers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjNjAxNzIzNi1jM2M3LTQxZWMtYmYwYy01MDJmMmQyYWYwNWMiLCJuYW1lIjoid3dkdG9AbWFjLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Ind3ZHRvQG1hYy5jb20iLCJpaWQiOiJjNjAxNzIzNi1jM2M3LTQxZWMtYmYwYy01MDJmMmQyYWYwNWMiLCJ3aWQiOiJhZmJmMzM4YS0xMDI1LWVkMTEtYWU4My0xNGNiNjUyNzVlNWIiLCJ1aWQiOiJjNmJmMzM4YS0xMDI1LWVkMTEtYWU4My0xNGNiNjUyNzVlNWIiLCJ0b2tlbl91c2FnZSI6ImFjY2Vzc190b2tlbiIsImp0aSI6IjE2MWRiMmE1LTJkYmEtNGRmNy05YWRiLWI2ZmU2YWJhNzcwOCIsImNmZF9sdmwiOiJwcml2YXRlIiwic2NvcGUiOiJvZmZsaW5lX2FjY2VzcyIsImF1ZCI6ImF3b3JrLmlvIiwiYXpwIjoiRDhDQUNGQTVGMEZDNDg4REJEQjUyNDlCRCIsIm5iZiI6MTY2Mjc0NDUwMSwiZXhwIjoxNjYyODMwOTAxLCJpYXQiOjE2NjI3NDQ1MDEsImlzcyI6Imh0dHBzOi8vYXdvcmsuaW8vIn0.lpFLe0CQxcCnaDX-_YB-c5QFKA4_0tu-cNztVkXpj38
Content-Type: application/json
User-Agent: PostmanRuntime/7.29.2
Accept: */*
Cache-Control: no-cache
Postman-Token: 83747926-eb40-4900-9aa3-fab4452f7e9f
Host: api.awork.io
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 61
Cookie: .AspNetCore.Antiforgery.9TtSrW0hzOs=CfDJ8NyZstk5bTlOmwuylEAF6SZAiZ3diFfTsyZ4WOt-KvWI9y4c6z_Wndwykk60SJYMD9J0gIX7_cnTUxxyMw-pcTRwO5WGA0B5HSEgqdY7UwEIHHVjf8QK6edONg1SHMgW7r5V-fKUs8aQoC6S6Fz__YQ
Request Body
Response Headers
Content-Type: application/json; charset=utf-8
Connection: keep-alive
Content-Length: 35
vary: Origin
Access-Control-Allow-Origin: *
Server: kong/2.5.0
Access-Control-Expose-Headers: trace-id
X-Kong-Response-Latency: 0
Response Body

**Comment by wwdto** [comment]
Erstmal Danke, ich bin weiter gekommen.
Allerdings nicht mit Postman, sonder ausschließlich mit FileMaker, was in meinem Sinne ist - ich aber verwirrend finde. 

Postman ist sonst ein super Tool zum Testen: nicht mit awork??  Was mache ich falsch?
Postman erzeugt in der CURL zwischen der ersten Zeile ( URL)  und den folgenden Zeilen  mit den Headern  ( und ggf —data) eine Zeilenschaltung.  Das funktionier nicht ???

response:
{
    "message": {
        "description": "Bad token; invalid JSON",
        "code": "unauthorized"
    }
}

Die komplette CURL  aus Postman rauskopiert, die  Zeilenschaltung im Terminal entfernt, funktioniert - manchmal.

Z.B mit GET …”timeentries"   funktioniert es.  “timeentries "ersetzt durch “customers”  gibt  kein Ergebnis zurück . Wie erklärt sich sowas ? ????


MAC OS 12.5 , Terminal, zsh.
OK:, JSON - result bei: 
CURL -X GET https://api.awork.io/api/v1/timeentries -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjNjAxNzIzNi1jM2M3LTQxZWMtYmYwYy01MDJmMmQyYWYwNWMiLCJuYW1lIjoid3dkdG9AbWFjLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Ind3ZHRvQG1hYy5jb20iLCJBc3BOZXQuSWRlbnRpdHkuU2VjdXJpdHlTdGFtcCI6IjVISk82MlRHT1FFSFZRRE5KUlhISzVZVU5OR0M2VkRBIiwiaWlkIjoiYzYwMTcyMzYtYzNjNy00MWVjLWJmMGMtNTAyZjJkMmFmMDVjIiwid2lkIjoiYWZiZjMzOGEtMTAyNS1lZDExLWFlODMtMTRjYjY1Mjc1ZTViIiwidWlkIjoiYzZiZjMzOGEtMTAyNS1lZDExLWFlODMtMTRjYjY1Mjc1ZTViIiwicnRpZCI6IjVmNzAxYzFiLWRjZGQtNDU5OC05NzE3LTJjYTZkZjhlZTljMyIsIm5iZiI6MTY2Mjg5NTg1NywiZXhwIjoxNjY1NDg3ODU3LCJpc3MiOiJodHRwczovL2F3b3JrLmlvLyIsImF1ZCI6ImF3LWFjY291bnRzIn0.6RnAq-_uCs9LatMn8JYy9LTwppyNGC-NkEkvntv7Lb4'


Leeres Ergebnis mit: 
CURL -X GET https://api.awork.io/api/v1/customers -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjNjAxNzIzNi1jM2M3LTQxZWMtYmYwYy01MDJmMmQyYWYwNWMiLCJuYW1lIjoid3dkdG9AbWFjLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Ind3ZHRvQG1hYy5jb20iLCJBc3BOZXQuSWRlbnRpdHkuU2VjdXJpdHlTdGFtcCI6IjVISk82MlRHT1FFSFZRRE5KUlhISzVZVU5OR0M2VkRBIiwiaWlkIjoiYzYwMTcyMzYtYzNjNy00MWVjLWJmMGMtNTAyZjJkMmFmMDVjIiwid2lkIjoiYWZiZjMzOGEtMTAyNS1lZDExLWFlODMtMTRjYjY1Mjc1ZTViIiwidWlkIjoiYzZiZjMzOGEtMTAyNS1lZDExLWFlODMtMTRjYjY1Mjc1ZTViIiwicnRpZCI6IjVmNzAxYzFiLWRjZGQtNDU5OC05NzE3LTJjYTZkZjhlZTljMyIsIm5iZiI6MTY2Mjg5NTg1NywiZXhwIjoxNjY1NDg3ODU3LCJpc3MiOiJodHRwczovL2F3b3JrLmlvLyIsImF1ZCI6ImF3LWFjY291bnRzIn0.6RnAq-_uCs9LatMn8JYy9LTwppyNGC-NkEkvntv7Lb4'

**Comment by nilzzzzzz** [comment]
Hallo @wwdto,

/customers ist einfach keine api route die wir haben. Man kann sich alle Routen hier anschauen: https://openapi.awork.io/
Die korrekte Adresse ist /companies.  In deinem Fall gibt es hier ein leeres Ergebnis, da in deinem Workspace noch keine Companies angelegt wurden.

Wir benutzen selbst Postman zum Testen und es gibt eigentlich keine Probleme damit.
Wenn du folgenden Fehler erhältst: Bad token; invalid JSON dann hast du wahrscheinlich den Bearer token nur unvollständig in den Header herein kopiert.

Viele Grüße

Nils

**Comment by wwdto** [comment]
OK - Danke!
“customers” is woocommerce  … ich turne grad in mehrere  Welten herum…

Das mit Postman  schau ich mir nochmal an.  Das Bearer Token ist als {{token}}  angelegt. 
Wenn es das ist,  geb ich nochmal Feedback

Danke und Gruß - Wolfgang Wunderlich

**Comment by wwdto** [comment]
Hallo Nils,
wir haben Teil #1  unserer Integration awork/FileMaker weitgehend  fertig.

Seit 2 Wochen empfangen und verarbeiten  wir Webhooks für  timeentries, inzwischen > 2000 Datensätze, scheint stabil zu laufen.
Dabei gab es nur einmal eine Irritation: 

Entity_id: 487e0d98-5c5c-ed11-ade6-cc60c8b6713c

Wie haben ein update nach delete  bekommen, was wir noch nicht abgefangen haben.

Drei Hooks  zur. og. id  kamen dieser Reihenfolge bei uns an:

1.) timetracking_added		2022-11-04T16:20:34.9036815+00:00
2.) timetracking_deleted		2022-11-04T16:26:19.987136+00:00
und dann:
3.) timetracking_updated   	2022-11-04T16:26:16.6363176+00:00

D.h. das der 2. Event vor dem 3. event bei uns ankam, obwohl der 3 . event  3 Sekunden älter war.

Liegt das jetzt an der Übertragung oder an der Verarbeitung bei uns??

Außerdem: der Update-Datensatz   #3  war sehr viel kleiner als  andere update-Datensätze.
Der war eigentlich unvollständig, nur mit Information zur Entity und dem User, keine informationen zu project, typeofwork, duration etc.

Weitere Information:
Wir erhalten oft zwei Webhooks direkt hintereinander zum selben timeEntry:  added & updated
D.h. das sieht für uns so aus, als würden noch während der Bearbeitung bereits  Hooks ausgelöst.

Gruß - Wolfgang


Wolfgang Wunderlich
DeskTop Organisation GmbH
***@***.***

Unsere Supportzeiten:
Mo - Do. von 9.00 - 16.00 Uhr
und Fr. 9.00 bis 15.00 Uhr


BERATUNG - UMSETZUNG - INTEGRATION

DeskTop Organisation GmbH
Datenbankentwicklung

Justus-von-Liebig-Ring 9
82152 Krailling
Tel. +49 (89) 548 475-0  
Fax:  +49 (89) 548 475-75
Web:  www.dto.de <http://www.dto.de/>
Email: ***@***.*** ***@***.***>

Geschäftsführer: Wolfgang Wunderlich

Sitz der Gesellschaft: München
HRB München 10 35 34
