### ISSUE TITLE
Ist ein Testing mit Postman möglich?

### ISSUE THREAD

**Issue by wwdto** [awork-io/awork#67]
### What is your question?

Ich hab versucht die CURL-Aufrufe, auch funktionerende, mit Postman abzusenden.

Antwort mit GET  ist HTML.... ??

z.B:.:
<!DOCTYPE html>
<html lang="en" translate="no">

<head><link rel="preconnect" href="https://use.typekit.net" crossorigin>
  
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
  <meta name="apple-mobile-web-app-capable" content="no"/>
  <meta name="robots" content="noindex"/>
  <meta name="slack-app-id" content="A9BP7F8G7"/>
  <meta name="description" content="awork - The joyful work management tool for happy teams."/>

  
  <title>awork.io</title>

  
  <link rel="apple-touch-icon" href="assets/app-icons/apple-touch-icon.png"/>
  <link rel="apple-touch-icon" sizes="57x57" href="assets/app-icons/apple-touch-icon-57x57.png"/>
  <link rel="apple-touch-icon" sizes="72x72" href="assets/app-icons/apple-touch-icon-72x72.png"/>
  <link rel="apple-touch-icon" sizes="76x76" href="assets/app-icons/apple-touch-icon-76x76.png"/>
  <link rel="apple-touch-icon" sizes="114x114" href="assets/app-icons/apple-touch-icon-114x114.png"/>
  <link rel="apple-touch-icon" sizes="120x120" href="assets/app-icons/apple-touch-icon-120x120.png"/>
  <link rel="apple-touch-icon" sizes="144x144" href="assets/app-icons/apple-touch-icon-144x144.png"/>
  <link rel="apple-touch-icon" sizes="152x152" href="assets/app-icons/apple-touch-icon-152x152.png"/>
  <link rel="apple-touch-icon" sizes="180x180" href="assets/app-icons/apple-touch-icon-180x180.png"/>
  <link rel="icon" type="image/png" sizes="32x32" href="assets/app-icons/favicon-32x32.png"/>
  <link rel="icon" type="image/png" sizes="16x16" href="assets/app-icons/favicon-16x16.png"/>
  <link rel="manifest" href="manifest.webmanifest"/>
  <link rel="mask-icon" href="assets/app-icons/apple-touch-icon-180x180.png"/>
  <meta name="msapplication-TileColor" content="#283157"/>
...... usw.

Bei POST  war es immer:

{
    "message": {
        "code": "unauthorized"
    }
}

**Comment by IanBuck-dev** [comment]
Hey @wwdto ,
das hört sich sehr danach an, dass du die falsche Base-Url benutzt. Unsere API Endpoints sind unter `https://api.awork.io/api/v1/` erreichbar. Mit der URL solltest du natürlich mit Postman auch Http Requests machen können.

Bezüglich der Authentification musst du in deinem awork workspace eine Client Application erstellen und dann den API Key im Header als Bearer Token an deine Request anhängen -> https://developers.awork.io/authentication

LG Ian

**Comment by wwdto** [comment]
...habe g hie geantwortet:  https://github.com/awork-io/awork/issues/66
