### ISSUE TITLE
Verständnisfrage zu WebHooks

### ISSUE THREAD

**Issue by wwdto** [awork-io/awork#68]
### What is your question?

WebHooks...
Ziel: FileMaker-Server 19.5.3
- es gibt leider noch kein Integration  awork/FileMaker

Habe einen WebHook angelegt, mir fehlt aber  was.....

Ein FileMaker Script soll getriggert werden, das JSON-Objekt  kann als Parameter übernommen und verarbeitet werden

Als  Ergebnis wünsche ich mir diesen Effekt:   (aus Postman kopiert )

curl -s -L -X POST 'https://fms5.dto.de/fmi/odata/v4/WEB_Zeiten/script.Webtrigger' \
-H 'Content-Type: application/json' \
-H 'Authorization: Basic V0VCaG9vazpwYXNzd29ydA==' \
--data-raw '{
    "scriptParameterValue" :
    {
      "Mein_JSON_Objekt":{
        "Text": "Hallo von OData",
        "JSON": "Hallo von OData-JSON",
        "Dauer": "1"
        }
 }
}'

Geht das?  Wenn ja, wie??

...oder brauche ich eien MiddleWare ?

**Comment by nilzzzzzz** [comment]
Hi @wwdto ,

ich bin mir nicht ganz sicher, ob ich verstehe was du vorhast. Unsere Webhooks haben die Möglichkeit einen bestimmten Endpoint zu callen und mit der Änderung die awork passiert ist. 

Um das zu testen kannst du zum Beispiel: https://webhook.site/ nutzen und dies als Ziel für die Webhooks in awork eintragen und dann eine Änderung vornehmen. Dann siehst du welche Informationen in dem Webhook übermittelt werden. 

Hier sind die user docs dafür: https://support.awork.io/de/articles/5415462-api-webhooks

Hilft dir das?

Viele Grüße

Nils

**Comment by wwdto** [comment]
Hallo Nils,
danke erstmal - ich teste das noch genauer.

Erster  Eindruck: das gelieferte JSON-Objekte passt nicht in das erwartete Schema für die Übermittlung an die ODATA -API  vom FileMaker-Server:
es fehl  das umschließende Objekt:   "scriptParameterValue” :

Ich wüßte jetzt nicht, wie ich das in die URL packen sollte, dass der WebHook das dann so liefert:

{
    "scriptParameterValue" :
    {
      "JSON_Objekt_von_awork:{
        "Text": "Hallo von awork ",
	"Dauer": “1"
        }
   }
}

Mein Stand aktuell ist, dass für die Nutzung von WebHooks von awork  an FileMAker-Server  eine Art -Agent als Connector benötigt wird.
Es gibt im Web php-Templates  für die Weitergabe von WebHooks an FileMaker-Server, das müsste ich ggf.  extern vergeben… installieren usw.
Es fühlt an wie “kurz vor der Lösung” zu sein …aber das tut es bei der API-Programmierung immer ;-)

Danke und Gruß - Wolfgang Wunderlich

DeskTop Organisation GmbH
***@***.***

Unsere Supportzeiten:
Mo - Do. von 9.00 - 16.00 Uhr
und Fr. 9.00 bis 15.00 Uhr


BERATUNG - UMSETZUNG - INTEGRATION

DeskTop Organisation GmbH
Datenbankentwicklung

Justus-von-Liebig-Ring 9
82152 Krailling
Tel. +49 (89) 548 475-0  
Fax:  +49 (89) 548 475-75
Web:  www.dto.de <http://www.dto.de/>
Email: ***@***.*** ***@***.***>

Geschäftsführer: Wolfgang Wunderlich

Sitz der Gesellschaft: München
HRB München 10 35 34

**Comment by nilzzzzzz** [comment]
Ok, ich glaube das geht etwas über unseren API Support hinaus. Unser Webhook schickt die Daten immer in einem standardisierten Format und kann nicht modifiziert werden.

Alternative ist einfach in regelmäßigen Abständen die Daten zu synchroniseren (api calls zu machen und abzurufen..)

Viele Grüße

**Comment by wwdto** [comment]
API-Abrufe zu synchronisieren ist aktuell  der der Plan…
Zeitplan : alle 5 Minuten ….

Problem/ Frage: was ist mit Löschungen?  Es gibt einen WebHook-Trigger  dafür.

Bekomme ich das über die API überhaupt mit, wenn  ein Datensatz gelöscht wurde?
Oder können Zeiteinträge ( Aufgaben, etc)  gar nicht gelöscht werden?

Gruß - Wolfgang Wunderlich

**Comment by wwdto** [comment]
Hmm, damit komme ich aktuell nicht weiter. 
Ich beschreib nochmal, wo ich hin muss, ich geb da noch nicht auf.

Vielleicht kann man noch was  mit Variationen in der URL bei der Einrichtung des WebHooks  erreichen.

Wenn ich in PostMan  das hier unten stehende absende funktioniert es.
Und das hätte ich  gern vom WebHook aus awork.

Ist das mit den vorhandenen Mitteln zu erreichen?

**1.)  AUTH in der URL**
Curl -s -L -X POST 'https://username:passwort@fms5.dto.de/fmi/odata/v4/WEB_Zeiten/script.Webtrigger' \
-H 'Content-Type: application/json' \
--data-raw '{
    "scriptParameterValue" :
    {
      "Mein_JSON_Objekt":{
        "Text": "Gruß vom Postman ",
        "JSON": "Hallo hier sind Daten",
        "Dauer": "1"
        }
 }
}'

**2. AUTH im HEADER**
curl -s -L -X POST 'https://fms5.dto.de/fmi/odata/v4/WEB_Zeiten/script.Webtrigger' \
-H 'Content-Type: application/json' \
-H 'Authorization: Basic UserPasswort_als_BAse64'
--data-raw '{
    "scriptParameterValue" :
    {
      "Mein_JSON_Objekt":{
        "Text": "Gruß vom Postman ",
        "JSON": "Hallo hier sind Daten",
        "Dauer": "1"
        }
 }
}'

Meine Vermutung warum es nicht gehen wird:  

 {  "scriptParameterValue" :  "......."}   
 wird als umschließendes Objekt  erwartet :-(

Wäre das irgendwo in awork editierbar?? Zu ergänzen ??
( es könnte "...der Beginn einer wunderbaren Freundschaft "sein ;-) 

Guß  - Wolfgang Wunderlich

**Comment by nilzzzzzz** [comment]
Hi @wwdto ,

leider lässt sich der Webhook nicht verändern (dies ist auch eher unüblich). Der Einzige Weg den ich sehe, wenn du ein spezielles Json Format in deiner Anwendung erwartest, dass du einen Umweg gehst über eine Middleware oder einen Service wie eine Azure Function und die Daten in das von dir erwartete Format konvertierst. 

Viele Grüße

Nils

**Comment by timkley** [comment]
@wwdto probiere mal [pipedream.com](https://pipedream.com/) aus. Die können einen Webhook entgegennehmen und dann einfach einen weiteren Request abfeuern. Das neue JSON-Objekt das du brauchst müsstest du dir jedoch selbst zusammenbauen.
