### ISSUE TITLE
[Question]: How does the `today` filter work regarding timezones?

### ISSUE THREAD

**Issue by timkley** [awork-io/awork#69]
### What is your question?

I just have a quick question: when we use the `eq today` filter: which timezone is used? Given a `timeEntry` there may be a difference when checking against `startDateUtc` and `startDateLocal`.

**Comment by nilzzzzzz** [comment]
Hi @timkley,

the used timezone is UTC. I hope this helps. 

Best

Nils

**Comment by timkley** [comment]
Thanks for clarifying!
