### ISSUE TITLE
Create client endpoint issue

### ISSUE THREAD

**Issue by chetaliparve** [awork-io/awork#7]
Hello

I was testing your API via postmen. I want to add the phone, email and URL fields to the endpoint but its not been added.

https://lh3.googleusercontent.com/-5yZ-LZeBcnQ/YJJEWdt5vDI/AAAAAAAAYqo/A8H1AhPa46U45WiU7dZ1dLLmSR0ebLgWgCK8BGAsYHg/s0/2021-05-05.png?authuser=0

This is the JSON data I am sending.

https://lh3.googleusercontent.com/-qpWreMMxy4U/YJJEku-mjCI/AAAAAAAAYqs/dEY-H1FNoUwvQI6X9nLxxLG3a9QmSNkUQCK8BGAsYHg/s0/2021-05-05.png?authuser=0

I am getting blank "companyContactInfo" array in response and also data is not populating in the account

What is the JSON structure of the request? An example will be helpful

Awaiting your response.

Regards

**Comment by nilzzzzzz** [comment]
Hi @chetaliparve ,

thanks for trying our api. 
We do not allow deep inserts. So you need to first create the company and then add the contact infos.

POST: api/v1/companies/{companyid}/contactinfo
Body: {"type":"email","subType":"central","value":"nils.czernig@lala.de", "isAddress":false}

![image](https://user-images.githubusercontent.com/22219385/117113316-94e41600-ad8a-11eb-80f5-651a08d8e39c.png)

I hope i was able to help you.

Best

Nils

Ps. The awork ui is also using completely the rest api, so you can also easily try out everything in the ui and copy the models/endpoints.

**Comment by chetaliparve** [comment]
This endpoint populates the data one at a time. I want to add email, phone, URL and address at once in the single API.

**Comment by nilzzzzzz** [comment]
Hi,

this is not possible.
