### ISSUE TITLE
How to delete orphaned tasks via API

### ISSUE THREAD

**Issue by PeterKuhnle** [awork-io/awork#70]
### What is your question?

Hi Awork team,
a user has deleted a project via the frontend. Tasks of the project remain in a orphaned state in the system and are list-able via /me/allavailabletasks (and by the way also by the action-button in the front-end).
Neither deleting (POST /tasks/delete) nor restoring (POST /tasks/{taskId}/restore) works via the api (404 resp. 401 status returned).
What to do to get rid of them? 

Best regards, Peter

**Comment by sebastianrosch** [comment]
Hi @PeterKuhnle could you please tell me the URL of your awork workspace and ideally the name of the project that was deleted? If you don't want to post this here, feel free to send an email to support@awork.io. I'll take a look as soon as I have this info. Thanks

**Comment by PeterKuhnle** [comment]
Thanks, Sebastian. Within the /me/allavailabletasks, the zombies are gone, in the GUI search, they still remain. I will anyway close the issue, as the api related problem is fixed. Hope that the GUI problem will be solved by some cache expiration.
Greets, Peter
