### ISSUE TITLE
Can the Project sorting be controlled by API? 

### ISSUE THREAD

**Issue by PeterKuhnle** [awork-io/awork#73]
### What is your question?

Hi Api-Support,
project listings in the project view follow some sorting rule, which is unclear to me. In despite to tasks, an order property is not existing in the model, so sorting works somehow implicitly, but neither by "name" nor "key" (although the project's "name" has some influence). Is there any property that I oversee?
Greets, Peter

**Comment by nilzzzzzz** [comment]
Hi @PeterKuhnle,

the projects are sorted by two properties: projectStatus/typeOrder asc,createdOn desc

Best

Nils

**Comment by PeterKuhnle** [comment]
Hi @nilzzzzzz,
thank you. Doesn't help me further to control the sorting (for us, the latest projects are often not the most important ones), but I understand know how it works.
Greets, Peter
