### ISSUE TITLE
[Question]: Kann beim Sortieren mit orderby auch case insensitive sortiert werden?

### ISSUE THREAD

**Issue by MircoKoenig** [awork-io/awork#74]
### What is your question?

Bei der Sortierung von Projekten nach ihren Namen mit "Name asc" ist mir aufgefallen, dass Projekte, dass diese Sortierung case-sensitive ist. Dadurch taucht beispielsweise "Testprojekt" vor "mustertest" auf. Gibt es die Möglichkeit, bei der Sortierung auf case-insenstive umzustellen?

### Do you have a trace id of the call?

https://api.awork.io/api/v1/projects?orderby=Name asc

**Comment by nilzzzzzz** [comment]
Hi @MircoKoenig, 

sorry, dass wir erst so spät antworten - das Thema war leider komplexer. Du hast da einen Bug identifiziert den wir gerade dabei sind zu beheben. Da dies leider ein Zusammenspiel aus Infrastruktur & Code in diesem Fall betrifft, wird der Fix erst in ca 4 Wochen flächendeckend ausgerollt sein.

Viele Grüß

Nils
