### ISSUE TITLE
Bug in documentation for filterung

### ISSUE THREAD

**Issue by timkley** [awork-io/awork#76]
### What happened?

On the page https://developers.awork.io/filtering the `startswith` and `endswith` filters are incorrectly documented. If you paste the example there are additional spaces which break the `filterby` expression.

**Current example:**
`https://awork.io/api/v1/users?filterby=startswith(FirstName, 'Neil' )`

**should be:**
`https://awork.io/api/v1/users?filterby=startswith(FirstName,'Neil')`

### What is the trace id of the call?

not relevant

**Comment by sebastianrosch** [comment]
HI @timkley thanks for reporting it. I've fixed the docs. Have a great day.

**Comment by timkley** [comment]
Hi @sebastianrosch, thanks for the quick response! I don't know if you've deployed yet but there are still spaces at the end of the string `'Neil' ` for all examples. Just wanted to let you know :)

**Comment by sebastianrosch** [comment]
@timkley thanks, fixed and deployed now! Let me know if you're still seeing the spaces.

**Comment by timkley** [comment]
@sebastianrosch LGTM 👍🏻 thanks!
