### ISSUE TITLE
API: user und accounts

### ISSUE THREAD

**Issue by wwdto** [awork-io/awork#77]
### What is your question?

Ich möchte über die API neue User anlegen und updaten. Mir ist nicht klar  wie  user und  accounts korrespondieren?

PUT.... users   - also ändern über user_id  ist klar. User neu anlegen geht nicht, für accounts gibt es in der API nur PUT.

Ich kann auch keine "ungenutzte Accounts"  abrufen , um diese für user zu nutzen: für den endpoint "accounts" wird inder DOKU nur "PUT"  angeboten.

Wie kann das über die API aus eine andern Anwendung gehen?

**Comment by nilzzzzzz** [comment]
Hi @wwdto ,

i added the docs for that endpoint: https://openapi.awork.io/#/Invitations/post_invitations
One user account can have multiple users (in different workspaces). 

In your case the model needs to look like this:
    ```
            {
                Email = assignForm.Email,
                FirstName = assignForm.FirstName,
                LastName = assignForm.LastName,
                Gender = assignForm.Gender,
                RoleId = assignForm.RoleId,
                InvitationFlow = "invite",
                SkipSendingEmail = true,
                WorkspaceId = workspaceId,
            }
```
