### ISSUE TITLE
[Question]: API update task

### ISSUE THREAD

**Issue by rlanzl** [awork-io/awork#78]
### What is your question?

We like to use the API to sync tasks between DevOps and work
However we didn't find a method to update the title or description of an existing task in awork

How could we achieve that?

**Comment by sebastianrosch** [comment]
Hi @rlanzl the PUT endpoint was missing from the documentation. It should be available in the next 15 minutes or so.

**Comment by sebastianrosch** [comment]
You can find the documentation here: https://openapi.awork.io/#/Tasks/put_tasks__taskId_
