### ISSUE TITLE
How can I filter for property values where a 'ß' is included?

### ISSUE THREAD

**Issue by p-stock** [awork-io/awork#79]
### What is your question?

https://api.awork.io/api/v1/users?filterby=lastname eq 'Weiß'

There is a user with the last name "Weiß" who is also returned when using the "Return all users" API-Call. However, when I filter the users by lastname (cf. call above) I receive an empty array as response. I am very positive about the special character "ß" being the reason for the behaviour. If I URL encode "ß" as "%DF" I still won't receive the expected response. Can you please tell me how to consider the special character "ß" when filterung in an API Call?

### Do you have a trace id of the call?

20a6a26200b4b95f

**Comment by nilzzzzzz** [comment]
Hi @p-stock,

we are lucky - it is not an encoding issue. Ms. 'Weiß' is having an empty char before her lastname, thats the reason the filter is not matching. 
<img width="218" alt="image" src="https://user-images.githubusercontent.com/22219385/200786255-2b92adea-ff7d-4312-9273-3b28d466f240.png">

If you adjust her lastname or add a space to the filter everything should work.

Best 

Nils

**Comment by nilzzzzzz** [comment]
No problem, we are happy to help! Have a great day.

Nils
