### ISSUE TITLE
"Falscher" API Error Code

### ISSUE THREAD

**Issue by ArneReimann** [awork-io/awork#82]
### What is your question?

Hi, Arne von timeBro hier.

Wir haben bei einem unserer gemeinsamen Kunden ein Problem festgestellt.

Und zwar können User unter gewissen Umständen (zB einem Projekt nicht zugewiesen, oder Projekt beendet) keine Zeiten mehr auf dieses Projekt buchen.

Als Fehlermeldung kommt derzeit aber nur ein 401 Fehler zurück.

Ein 401 Unauthorized Fehler führt aber leider dazu, dass wir davon ausgehen das die Authentifizierung nicht (mehr) gültig ist und wir zum (Re-)Login mit awork auffordern.

Wäre es möglich, dass ihr hier einen anderen Fehlercode werft (zB 403) und dazu einen Fehlertext mit dem die User etwas anfangen können? (ZB "Projekt kann aus folgendem Grund nicht mehr bebucht werden".

Viele Grüße
Arne

**Comment by nilzzzzzz** [comment]
Hi @ArneReimann ,

actually this should not happen. We return 400 when the request is not allowed because of business logic constraints. Could you provide us with a trace id to check what happened? 

Best

Nils

**Comment by ArneReimann** [comment]
Hi Nils,

I don't have a trace ID.

I have the following info in our log files:
"remoteRequest": "https://app.awork.io/api/v1/timeentries",
"remoteResponseStatus": 401,
"causingError": "The call to Project was blocked due to insufficient
permissions. (unauthorized)",
"timestamp": "2022-11-02T15:59:05.545Z"

Does that help?

Best regards
Arne

*Arne Reimann*

CEO

*timeBro - Reduce 75% of your time tracking effort.*

Schedule a zoom call with me
<https://t.sidekickopen01-eu1.com/s3t/c/5/f18dQhb0S7kC8f6h6LW4L4pnd2zGCz1N5xLs7slrBrYW1S-5-y3dkBjJMVyjhz3ZgjSf4r1-SP02?te=W3R5hFj4cm2zwW3F4Fph41QWmBW1JxwY51LvdMgW3JF5fm3T0W7-W41pM0f1GF6FPW1Gznnc3FbtXwW49TKQt3zd6BQW3K73DG43TDjHW2dMcHg1S06N90&si=8000000020992003&pi=957da757-70da-4a53-9787-e56a7c429679>

www.timebro.com <https://timebro.com/>


timeBro GmbH, Germany, 81375 Munich, Mäuselweg 14.
Registering court: Amtsgericht München. Registration number: HRB 220442.
Represented by: Arne Reimann, Niclas Preisner, Mislav Boras.


Am Do., 24. Nov. 2022 um 18:40 Uhr schrieb nilzzzzzz <
***@***.***>:

**Comment by nilzzzzzz** [comment]
Hi @ArneReimann ,

ok, so its no pre-requirement issue. The user simple had no permissions to track times on that project.

This case needs to be handled. You can check if the user is logged out, by checking for this json response body:
`{
	"message": {
		"code": "unauthorized",
		"description": "Unauthorized"
	}
}`

If its a different response body, it is a specific permissions issue related to the entity the user is trying to track time. Does that help?

Best

Nils

**Comment by ArneReimann** [comment]
Not really.

We created a video that shows the issue:
https://loom.com/share/9ae4f292454841ec84cf726dc4ffd36d

And we made a call with trace id as an example:

api POST call to:  https://app.awork.io/api/v1/timeentries
trace-id:  20ffd0a0073d0d1d
 POST request body:

{"startDateUtc":"2022-11-25T00:00:00+00:00","startTimeUtc":"10:35:00.0000000","duration":300,"userId":"9eb9939a-5281-e911-abc4-0017fa1003d8","taskId":"4fe644fd-5981-e911-abc4-0017fa1003d8","note":"11","typeOfWorkId":"9625f686-3ec4-4638-02ea-08d6df9c2473","timezone":"Europe/Berlin","isbillable":false,"projectId":"826aefcb-5581-e911-abc4-0017fa1003d8"}

Response status: 401
Response body:

{code: 'unauthorized', description: 'The call to task was blocked due
to insufficient permissions.'}

When looking at your API docs, we would rather expect a message like this:

not-found
The requested resource could not be located.entity-archived
The request tried to perform an operation with an archived entity.


Best regards
Arne

*Arne Reimann*

CEO

*timeBro - Reduce 75% of your time tracking effort.*

Schedule a zoom call with me
<https://t.sidekickopen01-eu1.com/s3t/c/5/f18dQhb0S7kC8f6h6LW4L4pnd2zGCz1N5xLs7slrBrYW1S-5-y3dkBjJMVyjhz3ZgjSf4r1-SP02?te=W3R5hFj4cm2zwW3F4Fph41QWmBW1JxwY51LvdMgW3JF5fm3T0W7-W41pM0f1GF6FPW1Gznnc3FbtXwW49TKQt3zd6BQW3K73DG43TDjHW2dMcHg1S06N90&si=8000000020992003&pi=957da757-70da-4a53-9787-e56a7c429679>

www.timebro.com <https://timebro.com/>


timeBro GmbH, Germany, 81375 Munich, Mäuselweg 14.
Registering court: Amtsgericht München. Registration number: HRB 220442.
Represented by: Arne Reimann, Niclas Preisner, Mislav Boras.


Am Fr., 25. Nov. 2022 um 12:07 Uhr schrieb nilzzzzzz <
***@***.***>:

**Comment by nilzzzzzz** [comment]
@ArneReimann i was able to repro the issue and will create a bug ticket on our side, we will try to get that fixed. Should be response code 400 in this case because a property in the post model is invalid (task id of not existing task).

Best 

Nils

**Comment by ArneReimann** [comment]
Great. Have you also tried other scenarios (not just deleted)?

I didn't reproduce other issues, but I think the same problem occurs also
for other reasons where a time entry cannot be made anymore.

Best regards
Arne

*Arne Reimann*

CEO

*timeBro - Reduce 75% of your time tracking effort.*

Schedule a zoom call with me
<https://t.sidekickopen03-eu1.com/s3t/c/5/f18dQhb0S7kC8f6h6LW4L4pnd2zGCz1N5xLs7slrBrYW1S-5_M5F3qL0N5J0-SY3ZnM1f45fpqC02?te=W3R5hFj4cm2zwW3F4Fph41QWmBW1JxwY51LvdMgW3JF5fm3T0W7-W41pM0f1GF6FPW1Gznnc3FbtXwW49TKQt3zd6BQW3K73DG43TDjHW2dMcHg1S06N90&si=8000000019731355&pi=7b8898e0-632e-44f8-c9e1-e0ed09014d13>

www.timebro.com <https://timebro.com/>


timeBro GmbH, Germany, 81375 Munich, Mäuselweg 14.
Registering court: Amtsgericht München. Registration number: HRB 220442.
Represented by: Arne Reimann, Niclas Preisner, Mislav Boras.


Am Mi., 7. Dez. 2022 um 19:48 Uhr schrieb nilzzzzzz <
***@***.***>:

**Comment by nilzzzzzz** [comment]
@ArneReimann yes. Those cases should also be fixed.
