### ISSUE TITLE
[Question]: How to filter tasks if a specific tag is present

### ISSUE THREAD

**Issue by timkley** [awork-io/awork#83]
### What is your question?

I want to fetch all projectTasks that don't have a specific task.

Previously we have worked with the following `filterBy` expression:

```
tags/any (tag: tag/name ne '%s') or tags/count() eq 0
```

This works if exactly one tag is present but if we assign more tags it breaks because the expression is satisfied.

I can't wrap my head around how I should write the expression to only give me tasks that don't have the tag. In good old try and error fashion I swapped `any` for `all` which results in `Something is wrong with the given 'filterby' expression.`.

Thanks up front!

**Comment by nilzzzzzz** [comment]
Hi @timkley,

ouch - seems to be an issue with the mongo driver we use: `MongoDB.Driver.dll: 'Unsupported filter: All`
Need to do a bit of research if that is a known issue. Your query looks correct.

Best

Nils

**Comment by nilzzzzzz** [comment]
Seems to be an issue which is not easy to fix unfortunately: 
<img width="926" alt="image" src="https://user-images.githubusercontent.com/22219385/203791437-20ac80c7-7336-40b8-9526-06b58ddfd298.png">

**Comment by timkley** [comment]
@nilzzzzzz good find. If I interpret the linked issue correctly `all` is just syntactic sugar for `not tags:any(tag: tag/name ne '%s')`. My test seems to confirm that.

I think this would be a great addition to the [filtering](https://developers.awork.io/filtering) docs, the `not` is currently not documented.

**Comment by nilzzzzzz** [comment]
@timkley yeah but the `not` is unfortunately not supported for our filter expression language..

**Comment by nilzzzzzz** [comment]
@timkley to be honest, we thought that is not supported, i do more tests 👯

**Comment by timkley** [comment]
@nilzzzzzz would traceIds help you in your testing? Could quickly get you two where the difference between the two filters can be seen.

**Comment by nilzzzzzz** [comment]
I already tested: expression looks good: `"Tags" : { "$not" : { "$elemMatch" : { "Name" : "blocker" }` . Thanks!
