### ISSUE TITLE
API upload a file in project

### ISSUE THREAD

**Issue by silkflo** [awork-io/awork#84]
### What is your question?

Hello,
I want upload a file in a project using the API.
I need help to execute the API request post entity file : https://openapi.awork.io/#/EntityFiles/post__entityName___entityId__files
The parameter to add the data file is missing from the documentation.
I can't find the correct syntax.
Can you please show me an example how to execute that request?

**Comment by nilzzzzzz** [comment]
Hi @silkflo ,

thx for reaching out.
The file needs to be attached to the request as multi part form data.

`curl 'https://develop.awork.io/api/v1/tasks/bacf5fa6-9f53-ed11-ade6-cc60c8b6347d/files' \
  -H 'Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryqlB1dGamvzIL7UEF' \
  -H 'accept: application/json' \
  --data-raw $'------WebKitFormBoundaryqlB1dGamvzIL7UEF\r\nContent-Disposition: form-data; name="file"; filename="welcome-image-top.png"\r\nContent-Type: image/png\r\n\r\n\r\n------WebKitFormBoundaryqlB1dGamvzIL7UEF\r\nContent-Disposition: form-data; name="name"\r\n\r\nwelcome-image-top.png\r\n------WebKitFormBoundaryqlB1dGamvzIL7UEF\r\nContent-Disposition: form-data; name="filename"\r\n\r\nwelcome-image-top.png\r\n------WebKitFormBoundaryqlB1dGamvzIL7UEF--\r\n' \
`

I hope this helps.

Best 
Nils
