### ISSUE TITLE
[Question]: Importierte Aufgaben starten

### ISSUE THREAD

**Issue by mgrabnermw** [awork-io/awork#85]
### What is your question?

Nach dem Import von Projekten und Aufgaben benötige ich ein Skript, welches alle Projekte startet, damit User ohne Admin-Rolle die Aufgaben zur Zeiterfassung nutzen können. Gibt es hier einen Workaround oder kann mir ggf. jemand ein vorhandenes Skript zur Verfügung stellen? Danke!

**Comment by sebastianrosch** [comment]
Hi @mgrabnermw, entschuldige bitte die späte Antwort. Wir haben dafür aktuell keine Lösung und kein Script. Die einzige Möglichkeit ist über die web app oder die API. Ich habe dies aber als Feedback eingetragen. Liebe Grüße, Sebastian
