### ISSUE TITLE
get projectStatuses

### ISSUE THREAD

**Issue by wwdto** [awork-io/awork#86]
### What is your question?

We create projects im  from FileMaker  using a projecttemplate  via api.
This template contains 3 statuses wir repeating  wording: 
"In Arbeit", "Abgeschlossen"; "Abgerechnet"

We want to change the statuses of the  project by api
Is possible ? 

If not  - I can stop here. :-(

#-------------------------#

Tried this to get of the statuses according to the project.

https://api.awork.io/api/v1/projectstatuses?filterby=projectId eq '954faff1-797c-ed11-ac20-14cb65275439'

returns:
{
    "code": "invalid-filter-or-order",
    "description": "Something is wrong with the given 'filterby' expression."
}

same with 
https://api.awork.io/api/v1/projectstatuses?filterby=name eq "Abgerechnet"

So what to do??

**Comment by nilzzzzzz** [comment]
Hi @wwdto ,

the first one needs to look like this: `https://api.awork.io/api/v1/projectstatuses?filterby=projectId eq guid'954faff1-797c-ed11-ac20-14cb65275439'`

the second one needs single quite instead of double quotes.

Best

Nils

**Comment by wwdto** [comment]
Hello Nils,
thanks  it worked. I can retrieve the statuses of the  project    (I did not find it in  the documentation.)

But I can not apply them .

CURL  in  Postman looks like this:

curl -s -L -X PUT 'https://api.awork.io/api/v1/projects/b48359e2-6c7c-ed11-ac20-14cb65275439' 

I tried several payloads, for example  like this
{
    "name" : "99031003 - Nächster Job - mit Template???",
    "projectstatus" : 
    {
        "id" : "b18359e2-6c7c-ed11-ac20-14cb65275439",
        "name" : "Abgeschlossen",
        "tye" : "closed"
    }
}


RESULT  is:
{{
    "id": "b48359e2-6c7c-ed11-ac20-14cb65275439",
    "hasImage": false,
    "key": "9NJMT",
    "createdOn": "2022-12-15T11:37:51.6860517Z",
    "createdBy": "a1e05c75-cc51-ec11-981f-501ac527b592",
    "updatedOn": "2022-12-15T15:21:19.2440453Z",
    "updatedBy": "a1e05c75-cc51-ec11-981f-501ac527b592",
    "createdByProjectTemplateId": "0b661661-f941-ec11-981f-501ac527b592",
    "projectStatus": {
        "typeOrder": 3,
        "isArchived": false,
        "type": "progress",	
        "name": "In Arbeit",
        "id": "b08359e2-6c7c-ed11-ac20-14cb65275439"
    },
    "tags": [],
    "plannedDuration": 0,
    "members": [],
    "trackedDuration": 0,
    "resourceVersion": 638067144792619789,
    "projectStatusId": "b08359e2-6c7c-ed11-ac20-14cb65275439",
    "name": "99031003 - Nächster Job - mit Template???",
    "isPrivate": false,
    "timeBudget": 0,
    "isBillableByDefault": true
}

Nothing has changed


Regards - Wolfgang

**Comment by nilzzzzzz** [comment]
Hi @wwdto,

you need to use this endpoint to change the for example the name of the status:
https://openapi.awork.io/#/ProjectStatuses/put_projectstatuses__projectStatusId_

PUT https://api.awork.io/api/v1/projectstatuses/{projectStatusId}

**Comment by wwdto** [comment]
Hello Nils,
I am not shure if  I understood everything .

I don't want  to change the name of a status - I want to change the status of a project,

In my understanding  I have to address the project  by id and apply one of  the status-id  according to that project, created by the template

in the example below I want in project  "b48359e2-6c7c-ed11-ac20-14cb65275439”
change  the status  " In Arbeit”      to status  "Abgeschlossen”,


1.) Project  

{
    "id": "b48359e2-6c7c-ed11-ac20-14cb65275439",
    "hasImage": false,
    "key": "9NJMT",
    "createdOn": "2022-12-15T11:37:51.686Z",
    "createdBy": "a1e05c75-cc51-ec11-981f-501ac527b592",
    "updatedOn": "2022-12-21T20:51:20.839Z",
    "updatedBy": "a1e05c75-cc51-ec11-981f-501ac527b592",
    "closedOn": "2022-12-17T12:12:51.902Z",
    "closedBy": "a1e05c75-cc51-ec11-981f-501ac527b592",
 "createdByProjectTemplateId": "0b661661-f941-ec11-981f-501ac527b592”,

# ——-------—  this i want to change    ——--------—#
    "projectStatus": {
        "typeOrder": 3,
        "isArchived": false,
        "type": "progress",
        "name": "In Arbeit",
        "id": "b08359e2-6c7c-ed11-ac20-14cb65275439"
    },
#---------------------------------------------------
    "tags": [],
    "plannedDuration": 0,
    "tasksCount": 26,
    "tasksDoneCount": 0,
    "members": [],
    "trackedDuration": 0,
    "resourceVersion": 638072526810958214,
    "teams": [],
    "projectStatusId": "b08359e2-6c7c-ed11-ac20-14cb65275439",
    "name": "99031003 - Nächster Job - mit Template???",
    "isPrivate": false,
    "timeBudget": 0,
    "isBillableByDefault": true
}

2.) Statuses  of the project created by the template :
https://api.awork.io/api/v1/projectstatuses?filterby=projectId eq guid'b48359e2-6c7c-ed11-ac20-14cb65275439'

[
    {
        "id": "b28359e2-6c7c-ed11-ac20-14cb65275439",
        "name": "Abgerechnet",
        "type": "closed",
        "order": 2,
        "createdOn": "2022-12-15T11:37:51.6303841Z",
        "createdBy": "a1e05c75-cc51-ec11-981f-501ac527b592",
        "updatedOn": "2022-12-15T11:37:51.6965207Z",
        "projectId": "b48359e2-6c7c-ed11-ac20-14cb65275439",
        "updatedBy": "a1e05c75-cc51-ec11-981f-501ac527b592"
    },
#———  this projectStatus  I want to apply to the project   —#
    {
        "id": "b18359e2-6c7c-ed11-ac20-14cb65275439",
        "name": "Abgeschlossen",
        "type": "closed",
        "order": 1,
        "createdOn": "2022-12-15T11:37:51.6303779Z",
        "createdBy": "a1e05c75-cc51-ec11-981f-501ac527b592",
        "updatedOn": "2022-12-15T11:37:51.6965172Z",
        "projectId": "b48359e2-6c7c-ed11-ac20-14cb65275439",
        "updatedBy": "a1e05c75-cc51-ec11-981f-501ac527b592"
    },
#——— I want not to change the name of this projectStatus  —#
    {
        "id": "b08359e2-6c7c-ed11-ac20-14cb65275439",
        "name": "In Arbeit",
        "type": "progress",
        "order": 0,
        "createdOn": "2022-12-15T11:37:51.6303586Z",
        "createdBy": "a1e05c75-cc51-ec11-981f-501ac527b592",
        "updatedOn": "2022-12-15T11:37:51.6965006Z",
        "projectId": "b48359e2-6c7c-ed11-ac20-14cb65275439",
        "updatedBy": "a1e05c75-cc51-ec11-981f-501ac527b592"
    }
]


Regards - wwdto

**Comment by nilzzzzzz** [comment]
Hi @wwdto ,

This is the correct endpoint for the operation:

https://openapi.awork.io/#/Projects/post_projects__projectId__changestatus

Best

Nils

**Comment by wwdto** [comment]
Hello Nils,

Thanks - I finally found it 

regards  - Wolfgang
