### ISSUE TITLE
[Bug]: 500 Internal Server Error for 'accounts/token'

### ISSUE THREAD

**Issue by DmitrySidorenkoShim** [awork-io/awork#87]
### What happened?

I have api request:  
POST https://api.awork.io/api/v1/accounts/token  
for refresh token
and it use to work perfectly
but it returns an error for last few days:

```
{
  "code": "server-error",
  "description": "Oops, something went wrong. Try repeating the request. If it still fails, visit our developer portal for help at https://developers.awork.io. Provide the 'trace-id' from the response header so that we can help you best."
}
```

I tried it with new `refresh_token` but I got the same error

### What is the trace id of the call?

trace-id: 23d2720aa40eb8ea

### Relevant error responses

```shell
{
  "code": "server-error",
  "description": "Oops, something went wrong. Try repeating the request. If it still fails, visit our developer portal for help at https://developers.awork.io. Provide the 'trace-id' from the response header so that we can help you best."
}
```

**Comment by nilzzzzzz** [comment]
Hi @DmitrySidorenkoShim ,

we released a fix 2 minutes ago. Can you double check on your side if everything now works as expected?

Best

Nils

**Comment by DmitrySidorenkoShim** [comment]
Wow,

it was blazing fast 

it working again now

thank you very much for your support

have a nice day

best regards 

Dimon

**Comment by nilzzzzzz** [comment]
🙏
