### ISSUE TITLE
[Question]: Gibt es Trigger über die ich eigene funktionen ausführen kann?

### ISSUE THREAD

**Issue by digitalwert-devs** [awork-io/awork#88]
### What is your question?

Ich würde gern eine Funktion schreiben die alle tasks fortlaufend nummeriert. Bei neuen tasks sollte die Funktion getriggert werden und eine Nummer (z.B als Tag) an das Ticket geschrieben werden.

**Comment by IanBuck-dev** [comment]
Moin @digitalwert-devs,
du könntest unsere Webhooks benutzen, siehe https://support.awork.io/de/articles/5415462-api-webhooks
Hier könntest du dann auf das task-created Event subscriben und dann z.B. eine Azure Function oder einen Http Endpoint einer Webapp triggern, die dem Task den jeweiligen Tag hinzufügt.

Für die API Docs schaue mal bei https://developers.awork.io/ vorbei, dort findest du auch wie API Access Token etc. erstellst.

Ich hoffe ich konnte dir weiterhelfen. Melde dich gerne falls du noch Fragen hast.
LG Ian
