### ISSUE TITLE
[Bug]: Update ("PUT") Task mit nur "name" im body setzt die "plannedDuration" zurück.

### ISSUE THREAD

**Issue by digitalwert-devs** [awork-io/awork#89]
### What happened?

Ich habe eine Webhook eingerichtet die sobald ein ticket erstellt wird eine ticketnummer an den ticket namen hängt. 
Dabei setzt sich das Feld "plannedDuration" zurück

### What is the trace id of the call?

allgemeiner bug ohne trace-id

**Comment by digitalwert-devs** [comment]
Dies scheint ein allgemeines problem zu sein und betrifft nicht nur die plannedDuration.
Außerdem tritt dies auch bei der helloHQ-awork integration auf! 
Das ist als Schwerer Fehler zu betrachten da z.b auch zugewiesene Kunden wieder entfernt werden und nicht nachvollziehbar ist wann das passiert

**Comment by nilzzzzzz** [comment]
HI @digitalwert-devs ,

bei dem beschriebenen Verhalten handelt es sich nicht um einen Fehler.
Bei einem PUT request wird nach HTTP Standard immer die komplette Ressource ersetzt. D.h. du musst in deinem Request alle Felder setzen, ansonsten werden die nicht gesendeten Felder geleert.

Viele Grüße

Nils
