### ISSUE TITLE
awork ->> Google Sheet ->> pull tags and start date for specific task

### ISSUE THREAD

**Issue by martin-lakoer** [awork-io/awork#9]
Hallo Ihr Lieben,

ich habe über Eure tolle API und anhand des von Euch bereitgestellten Beispiel-Codes eine awork Anbindung für Google Sheets realisiert.
Nun gibt es noch einige spezielle Anforderungen, die ich leider nicht gelöst bekommen und freue mich, wenn Ihr hier unterstützen könnt.

1. Tags eines Projektes in eine Spalte schreiben 
-> über welche Variable kann ich die Tags auslesen? 
-> schaut gerne mal im anhängenden Screenshot, was ich meine (so klappt es leider nicht)

2. für jedes Projekt das Startdatum der Aufgabe "Projektstart" auslesen und dieses in eine Spalte schreiben 
-> hier arbeite ich derzeit noch mit einem Code-Schnipsel von Euch, mittels dessen ich die früheste Aufgabe auslesen kann und damit sozusagen den Projektstart auslesen kann (siehe hier: https://github.com/awork-io/awork/issues/8)
-> leider klappt das nicht, da manche Aufgaben einfach vor Projektstart beginnen (ja, klingt komisch)
-> jetzt möchten wir den Projektstart gerne in der Aufgabe "Projektstart" hinterlegen und dann für jedes Projekt auslesen

Könnt Ihr mich hier bitte mit einem Code unterstützen?
Vielen vielen Dank vorab für Eure Bemühungen.

Liebe Grüße,
Martin

<img width="1440" alt="Screenshot 2021-05-21 at 15 15 21" src="https://user-images.githubusercontent.com/84152394/119669213-2c8fce00-be38-11eb-966f-b1b1c5273ad3.png">

**Comment by IanBuck-dev** [comment]
Hallo Martin,

bezüglich der Tags handelt es sich hierbei um eigene Objekte mit id, name, entityId etc. Um hier die name Property von jedem Tag pro Projekt abzurufen, falls es Tags gibt, könntest du z.B. folgenden Code benutzen:
``` javascript
sheet.getRange(currentRow, 14).setValue([getTagsFromProject(project.tags)])

// Funktion um die Tags zusammenzufügen
function getTagsFromProject(tags) {
  var names = [];
  for (tag of tags)
    names.push(tag.name);

  if (names.length > 0)
    return names.join();

  return null;
}
```

Für das Abrufen der Aufgabe könntest du die Funktion für die erste Aufgabe umschreiben, dass du bei dem Filter nach dem Namen der Aufgabe suchst. Diese würde dann so aussehen:
``` javascript
function getEarliestTaskForProject(projectId, options) {
  var filter = "?filterby=name eq 'Projektstart'";
  var response = UrlFetchApp.fetch("https://api.awork.io/api/v1/projects/" + projectId + "/projecttasks" + filter, options);

  var json = response.getContentText();
  var data = JSON.parse(json);

  if (data.length > 0 && data[0].startOn != null)
    return new Date(data[0].startOn);

  return null;
```

Ich hoffe ich konnte dir mit meiner Antwort weiterhelfen.

Liebe Grüße
Ian

**Comment by martin-lakoer** [comment]
Lieber Ian,

toll, das funktioniert. 
Erneut vielen Dank für Deine schnelle Hilfe :)

Liebe Grüße,
Martin
