### ISSUE TITLE
[Question]: Was ist die planner-service api?

### ISSUE THREAD

**Issue by juekbr** [awork-io/awork#90]
### What is your question?

Ich hab den Task die freie oder gebuchte Zeit eines User zu erheben (aggregiert, no details).
In der Doku https://openapi.awork.io/#/ find ich dazu die ProjectMemberCapacities, die sind allerdings schon deprecated, und es wird auf die planner-service api verwiesen bzw. Project Time bookings.

Zu Beiden finde ich nichts in der Doku, wird das erst ausgerollt?

**Comment by nilzzzzzz** [comment]
Hi @juekbr,

die planner-api hat hat tatsächlich in den Docs gefehlt. 
Die Endpoints sind nun sichtbar.

Viele Grüße

Nils

**Comment by sebastianrosch** [comment]
Hi @juekbr, folgende Endpoints sollten dir helfen: https://openapi.awork.io/#/ProjectTimeBookings
