### ISSUE TITLE
WebHooks unzuverlässig ??

### ISSUE THREAD

**Issue by wwdto** [awork-io/awork#91]
### What happened?

Wir tracken Zeiteinträge  für Auswertungen in FileMaker  von awork über einen Webhook.
Dabei haben wir festgestellt, dass einige Zeiteinträge nicht  ankommen. 
Jeder ankommende WebHook erzeugt einen Datensatz und wird protokolliert
Beobachtung: 
- es werden bei einer Änderungen an  einem TimeEntries manchmal mehr als 1 Hook direkt hintereinander gefeuert, evtl.  nach Änderungen an einzelnen Feldern.
- bei event: "timetracking_deleted"  kam  ein Hook  mit  "timetracking_updated" , nach  6 Sekunden nach dem timetracking_deleted bei uns ankam.
- Die Fehler fallen uns auf, wenn Datensätze komplett fehlen, es fehlen aber auch updates. D.h. in awork haben die timeEntries evtl. einen anderen Wert als bei uns. Wenn es danach noch ein Update gibt - ist es OK, wenn es kein weiteres Update zu TimeEntry mehr kommt, kann es sein, dass der Zeiteintrag bei uns nicht den letzen Wert enthält.
- 
Wir können von Zeit zu Zeit alle timeEntries  abrufen und bei uns nachträglich aktualisieren, würden aber uns und unserem Kunden (vMM) diesen Aufwand gern ersparen.

### What is the trace id of the call?

2 Beispiele
**timetracking, entidyId: f3198d69-4567-ed11-ac20-cc60c8b66d72**
-update nach delete

**timetracking, entidyId: afb56e75-1f9e-ed11-bf7a-14cb65277a35**
- letzte Änderungen an timeEntries kamen nicht bei uns an = > abweichende Werte zwischen awork  und FileMaker 

Es sind bis zu 250 Hooks am Tag für timeEntries

**Comment by nilzzzzzz** [comment]
Hi @wwdto ,

zu diesem Verhalten kann es in einigen Fällen kommen, da die Webhooks asynchron generiert werden. Zum Beispiel kann es dazu kommen, wenn ein Zielserver kurzfristig nicht erreichbar ist oder wenn es gerade hohe Last auf den entsprechenden Services gibt, die die Webhooks raus senden. Das Problem lässt sich aber einfach lösen. In jedem Event gibt es ein `timestamp ` Feld. Dieses Feld müsstest du zusätzlich zu dem Datensatz weg speichern und dann nur Änderungen übernehmen, die einen späteren `timestamp` haben. So lösen wir das zum Beispiel auch in awork selbst mit unseren Live Ui updates (websockets).

Viele Grüße

Nils

**Comment by wwdto** [comment]
Hallo Nils,
danke für die Antwort.

Die Anwendung läuft auf einem Root Server bei Hetzner mit eigener NGINX-Instanz, die derzeit nur für den WebHook zuständig ist. Bei ca 300  WebHooks am Tag sollte es keine Überlastung geben und die Erreichbarkeit  gut sein
Bei >30.000 WebHooks haben wir ca 860 fehlende Datensätze feststellen können.
Merkwürdigerweise war 1 Projekt zu 95% beteiligt. Dieses Projekt wird von allen 40 Usern für die Erfassung interner Arbeiten genutzt und hat somit die meisten Zeiteinträge von allen Projekten.

Unser Vorgehen ist folgendes:
- jeder amnkommende WebHook erzeugt einen Datensatz in einer WebHook-Tabelle  ( = Protokoll )
- Wir schreiben zur  timeentryID   einen Datensatz in unsere ZeitEintrag-Tabelle ( das Ziel ) 
    - gibt es keinen Zeiteintrag zur timeentryID: Datensatz erzeugen
    - gibt einen Zeiteintrag zur timeentryID: Datensatz updaten
- unser Zeiteintrag hat immer den letzten Stand ( so das Konzept ... )

Wenn jetzt ein Hook ausfällt - warum auch immer -  und KEIN Folge-Hook zur selben timeentryID mehr kommt, 
ist unser letzter Eintrag NICHT der letzte Stand.

D.h. wir können nicht sicher sein, ob unser Datenstand synchron und aktuell  ist. 

WorkArround: per API die letzen ( 1000 ) timeentries  abrufen und per timeentryID entweder erzeugen oder aktualisieren. Das funktioniert  :-|

Was wäre der Wunsch? Dass der WebbHook weiß, ob er entgegengenommen wurde  und es nochmal versucht.

Gruß - Wolfgang

**Comment by nilzzzzzz** [comment]
Hi @wwdto ,

ich habe mir die Logs angeschaut für: afb56e75-1f9e-ed11-bf7a-14cb65277a35
und es wurden alle webhooks erfolgreich ausgeführt. Der letzte, mit der letzten Änderung um 17.05 mit folgendem response: 

http.response.body: array(2) {
  ["response"]=>
  array(2) {
    ["scriptResult"]=>
    string(32) "{"Text":"Alles OK","id":"17453"}"
    ["scriptError"]=>
    string(1) "0"
  }
  ["messages"]=>
  array(1) {
    [0]=>
    array(2) {
      ["code"]=>
      string(1) "0"
      ["message"]=>
      string(2) "OK"
    }
  }
}

Sollte euer Server nicht erreichbar sein gibt es 10 retries. 

Kannst du noch mal schauen ob bei euch da etwas nicht passt?

**Comment by wwdto** [comment]
Hallo Nils,
- alle TimeEntry-Hooks, die bei uns aufgeschlagen sind wurden auch korrekt verarbeitet.
- scheinbar haben nicht alle  timeEntries oder Änderungen daran einen WebHook ausgelöst? ist sowas möglich?
Das wäre dann ein awork Problem.

Dabei gibt es ein Häufung bei einigen (internen) Projekten  ?? project_id = d3cfc5c3-fcbb-ec11-997e-38563d6e6dce

Das  WebHook -Protokoll in awork >>Integrations zeigt. max 1000 Einträge, das entspricht hier ca 4-5 ArbeitsTagen.
- Leider ohne IDs, sodass  die die Events nicht wirklich identifizierbar sind
-  musste mehrfach manuell angeklickt werden, bevor das Log angezeigt wurde  ( Safari 16.3)

Gib es ein detaillierteres Hook-Protokoll?
 
Es bleiben jetzt  noch 2 Szenarios:
  	1.)  Webhook kommt an, wird “verschluckt”  und ist deshalb auch nicht im   …./nginx/logs/access.log
	2.) manche WebHooks werden gar nicht erst ausgelöst , das wäre dann ein awork Problem

Maßnahme bei uns:
- doppeltes Protokoll:
	1,) bei Entgegennnahme des WebHooks ( fehlt noch )
	2.) bei Verarbeitung   		 -> …./nginx/logs/access.log  (das haben wir schon, alles OK)


Gruß - Wolfgang Wunderlich

**Comment by nilzzzzzz** [comment]
Hallo Wolfgang, 

wie gesagt, deine vorigen Beispiele habe ich überprüft. Es sind alle Webhooks erfolgreich verschickt wurden. Ich hab dir ja das Log dazu gegeben, was euer Server returned hat. Wenn du konkrete Dinge hast die nicht angekommen sind bitte die Id der Entität und den Timestamp der Änderung, dann kann ich gerne noch mal schauen.

Viele Grüße

Nils

**Comment by wwdto** [comment]
OK-Verstanden
Aktuell habe ich den Januar 2023  erstmal komplett synchronisiert, damit die Agentur weiter arbeiten kann.

Bei dem nächste Differenzen kommt die melde ich mich wieder



Mit freundlichen Grüßen 

Wolfgang Wunderlich
DeskTop Organisation GmbH
***@***.***

Unsere Supportzeiten:
Mo - Do. von 9.00 - 16.00 Uhr
und Fr. 9.00 bis 15.00 Uhr


BERATUNG - UMSETZUNG - INTEGRATION

DeskTop Organisation GmbH
Datenbankentwicklung

Justus-von-Liebig-Ring 9
82152 Krailling
Tel. +49 (89) 548 475-0  
Fax:  +49 (89) 548 475-75
Web:  www.dto.de <http://www.dto.de/>
Email: ***@***.*** ***@***.***>

Geschäftsführer: Wolfgang Wunderlich

Sitz der Gesellschaft: München
HRB München 10 35 34

**Comment by wwdto** [comment]
Status:  Wir haben weiter eProtokoll geführt: die WebHooks kommen bei uns an, werden aber nicht alle verarbeitet, bei ca 0,5% haben wir Probleme.
D.h. unser PHP-Tool, das die Hooks entgegen nimmt hat offenbar noch ein Problem.

- Vorgang kann geschlossen werden. 

Gruß - Wolfgang Wunderlich
