### ISSUE TITLE
api, absences erzeugen

### ISSUE THREAD

**Issue by wwdto** [awork-io/awork#92]
### What happened?

Via Postman:

Neue  absence erzeugen, eine absenceId wird zurückgemeldet

 - absence kann nicht aktualisiert werden MELDUNG: EXISTIERT NICHT

### What is the trace id of the call?

POST https://api.awork.io/api/v1/absences

{
    "description": "Urlaub",
    "endOn": "2023-02-03T23:59:00Z",
    "startOn": "2023-01-30T00:00:00Z",
    "userId": "a1e05c75-cc51-ec11-981f-501ac527b592"
}

ERGEBNIS:

    "id": "215f8b42-8d9e-ed11-bf7a-14cb65277a35",
    "userId": "a1e05c75-cc51-ec11-981f-501ac527b592",
    "startOn": "2023-01-30T00:00:00Z",
    "endOn": "2023-02-03T23:59:59Z",
    "description": "Urlaub",
    "createdOn": "2023-01-27T21:55:08.5404956Z",
    "createdBy": "a1e05c75-cc51-ec11-981f-501ac527b592",
    "updatedOn": "2023-01-27T21:55:08.5404994Z",
    "updatedBy": "a1e05c75-cc51-ec11-981f-501ac527b592",
    "isReadOnly": false,
    "isHalfDayOnStart": false,
    "isHalfDayOnEnd": false
}

### Relevant error responses

```shell
Änderung AN "endON"

PUT   https://api.awork.io/api/v1/absences/215f8b42-8d9e-ed11-bf7a-14cb65277a35

{
    "description": "Urlaub",
    "endOn": "2023-02-05T23:59:00Z",
    "startOn": "2023-01-28T23:00:00Z",
    "userId": "a1e05c75-cc51-ec11-981f-501ac527b592"
}

ERGEBNIS:

{
    "code": "not-found",
    "description": "The absence with the id '215f8b42-8d9e-ed11-bf7a-14cb65277a35' does not exist."
}
```

**Comment by nilzzzzzz** [comment]
Hi @wwdto ,

kannst du uns bitte die Trace Id aus dem Response Header geben, ansonsten können wir den Request nicht überprüfen.

Viele Grüße

Nils

**Comment by wwdto** [comment]
Erneuter Versuch eine absence zu erzeugen -  mit Trace-ID's

- Absence mit POST erzeugen 
trace-id : 29b898802f3f1eb7

RESULT:
{
    "id": "3f11a7bd-e7a7-ed11-ba77-38563d687ba0",
    "userId": "a1e05c75-cc51-ec11-981f-501ac527b592",
    "startOn": "2023-01-30T00:00:00Z",
    "endOn": "2023-02-03T23:59:59Z",
    "description": "Urlaub",
    "createdOn": "2023-02-08T19:35:38.8504677Z",
    "createdBy": "a1e05c75-cc51-ec11-981f-501ac527b592",
    "updatedOn": "2023-02-08T19:35:38.850472Z",
    "updatedBy": "a1e05c75-cc51-ec11-981f-501ac527b592",
    "isReadOnly": false,
    "isHalfDayOnStart": false,
    "isHalfDayOnEnd": false
}

- Mit GET ID  aufrufen:
- trace-id : 29323c5eea347a6c
{
    "code": "not-found",
    "description": "The absence with the id '3f11a7bd-e7a7-ed11-ba77-38563d687ba0' does not exist."
}

**Comment by nilzzzzzz** [comment]
Hi @wwdto ,

die Absence wurde direkt nach dem anlegen wieder gelöscht (ein paar MS später). Es sind mir aus als wenn die `HelloHQ` Integration die Löschung durchgeführt hat. Wenn die `HelloHQ` Integration aktiviert ist können nur Absences im `HelloHQ` angelegt werden, alle anderen werden von der Integration direkt wieder gelöscht.

Grüße

Nils

**Comment by sebastianrosch** [comment]
Hi @wwdto da wir nichts mehr von dir gehört haben, gehen wir davon aus dass sich dein Anliegen geklärt hat. Viele Grüße, Sebastian
