### ISSUE TITLE
I need help for an Integration webhook from KUSS Portal to awork. 

### ISSUE THREAD

**Issue by STE008** [awork-io/awork#93]
### What is your question?

I need help for an Integration webhook from KUSS Portal to awork.

**Comment by sebastianrosch** [comment]
Hi @STE008 could you share some more details about what it is you need help with? Also, what is KUSS Portal and how are you expecting the integration to work? Thanks

**Comment by STE008** [comment]
Hi Sebastian, thx for a speed answer.
I am working with awork and the over that portal i get new orders for my work. Over webhook i will be able to get messages from that portal into awork.
![image](https://user-images.githubusercontent.com/125490775/219102778-33defd96-3fbc-45cc-a3cd-31151b738f1d.png)
My question i will have a complete communikation as "Dienstleister" over that way oh webhooks.
I have a webadress with the integrations, but i do not know how to share it with you safely.
Cheers Stephan

**Comment by sebastianrosch** [comment]
@STE008 this looks like this portal's way of sending updates to another service. Do you want those events to create tasks or projects in awork? Then I recommend checking out Zapier, which specializes in integrating web tools like awork. Setting up a webhook receiver in Zapier and then creating tasks in awork should be easy. https://support.awork.io/en/articles/5396698-zapier-integration
