### ISSUE TITLE
[Question]: groupby for API endpoints

### ISSUE THREAD

**Issue by timkley** [awork-io/awork#94]
### What is your question?

Is it possible to provide another GET parameter for API endpoints to group entities? This prevents us from using the API directly for more complex reports as there is always another step / application needed to do this.

I believe your MongoDB driver should support this [out-of-the-box](https://mongodb.github.io/mongo-csharp-driver/2.5/reference/driver/crud/linq/#groupby), although I can't assess how complex the implementation would be.

**Comment by nilzzzzzz** [comment]
Hi @timkley ,

we currently have no plans for this, because we have no real use case for that. If we want to group the data in our Frontend we just sort by the grouping fields and then aggregate on the client.

Best

Nils
