### ISSUE TITLE
[Question]: Sum billable Time Entries

### ISSUE THREAD

**Issue by mstffck** [awork-io/awork#95]
### What is your question?

Hey,

we recently switched to awork & HelloHQ. 
Since **all** the tracked project time entries (billable as well as unbillable) seem to be transferred from awork to HQ (without option to filter), we have no possibility of comparing the tracked billable time entries (from awork) in comparison to the (billable) times we agreed on in our offers with customers (stored in HQ & awork per project). 

To this end, I wanted to implement a rudimentary app to deliver this comparison per API.

You have an endpoint called "**/{entityName}/{entityId}/trackedtime**" which seems to return again **all** time trackings, not only the billable ones. 
To gather the sum over all **billable** tracked time entries **per project**, is there a shorter way than iterating above all "**/{entityName}/{entityId}/timeentries**" while filtering for the billable ones and sum up their durations?

Do you plan on adding a "billable" value on the "/{entityName}/{entityId}/trackedtime" endpoint?

I would appreciate any tips regarding this problem 😊 Thanks in advance!

**Comment by nilzzzzzz** [comment]
HI @mstffck ,

sure there is. :) 

https://openapi.awork.io/#/TimeEntries/get_timeentries
You can use `https://api.awork.io/api/v1/timeentries?filterby= isBillable eq true`
or if you want to filter for a specific project: `https://api.awork.io/api/v1/timeentries?filterby= isBillable eq true and projectId eq guid'abc'`

Does that help?

Best

Nils

**Comment by mstffck** [comment]
Hey @nilzzzzzz 
thanks for your fast reply! Works perfectly 😊👍
