### ISSUE TITLE
[Bug]: Cannot change Taskstatus by click on Task-status-icon. Nothing happens on click new status - Chrome/Linux.

### ISSUE THREAD

**Issue by newton730ia** [awork-io/awork#96]
### What happened?

e.g. https://green-remarkable-brains.awork.io/my/dashboard - click on Icon before task name, List of possible status-icons pops up. On clicking one of the status-icons in this list, list closes. No AJAX-request(network-tab), no error-messages in Browser-console.

Debian Linux/Google Chrome 110.0.5481.177, also Linux/Vivaldi 5.7.2921.60 stable
Tried: Install browser in another user-account on same system. Tried there.

Does work in Windows11/Chrome with same awork-user-account.

### What is the trace id of the call?

Message from Awork Support was:
Linux is not in the expertise range of the support. Could you go and create an issue at https://github.com/awork-io/awork/issues and ask your questions directly to our development team. They will then answer you there in a short time.

**Comment by newton730ia** [comment]
![screenshot](https://user-images.githubusercontent.com/7635408/221896311-481e908c-58ab-41d9-b042-c4eef4605826.png)!

**Comment by newton730ia** [comment]
Here an example on /tasks/filters. Problem happens everywhere in awork.io
![screenshot](https://user-images.githubusercontent.com/7635408/221896778-b43d3a6e-4a1d-4a5f-b8ef-ed54ac634e13.png)

**Comment by nilzzzzzz** [comment]
Hi @newton730ia ,

i just tried this combination: Debian 10.10 and Chromium 89.0.4389.114 and the issue you described is not reproducable. We cannot try your exact scenario because chrome is not available for arm64 / linux right now. Could you try chromiumn to see if the issue is also reproducible there for you?

**Comment by newton730ia** [comment]
Thanks for your fast response - same problem in chromium, though there I get an error about fonts-loading & google analytics. Screenshot attached.
Version for chromium is "Version 108.0.5359.94 (Official Build) built on Debian 11.5, running on Debian 11.6 (64-bit)"

**Comment by nilzzzzzz** [comment]
Hmmm, strange, and the same issue that you cannot switch the task status? My colleague will try to setup a debian 11 and then we double check there.

**Comment by nilzzzzzz** [comment]
Hi @newton730ia, 
we now have exactly the same setup, could we make a quick call the next days to see the issue on your machine? 
Could you send me a proposal for a short call to nils@awork.io ? 

Best

Nils
