### ISSUE TITLE
Automatisertes erstlle aund Abrufen eines Refresh-Tokens  für API

### ISSUE THREAD

**Issue by wwdto** [awork-io/awork#97]
### What is your question?

ca Alle 2 Monate  funktioniert  die API nicht mehr. Zufall oder Konzept?

Wir müssen  dann - manuell  AUTH-Dialog im  Browser einen refresh Token abholen und den vorhandenen Token  austauschen und  eintragen -  dann läuft es wieder.

Wie kann man das automatisieren, damit die Anwender oder wir als Supporter das nicht tun müssen ?
Wenn ich  die Doku richtig verstanden habe, sollte das möglich sein mit :

Postman:
POST https://api.awork.io/api/v1/accounts/token?grant_type=refresh_token&refresh_token={{refresh_token}}&client_id={{clientID}}&client_secret={{clientSecret}}

Ergebnis: {
    "code": "invalid_request",
    "description": "The mandatory 'Content-Type' header must be specified."
}

'Content-Type' = application/x-www-form-urlencoded      .... wird akzeptiert

dann folgt aber 

{
    "code": "invalid_request",
    "description": "The mandatory 'grant_type' parameter is missing."
}

grant_type=refresh_token

Wie komme ich da weiter ?

### Do you have a trace id of the call?

471599f2e339f6b11c8e34782b2f9b5d

**Comment by sebastianrosch** [comment]
Hi @wwdto,
die Gültigkeit der refresh token unserer Implementierung verlängert sich eigentlich automatisch. Wir hatten im letzten Release allerdings einen Fehler, der diese aufgrund einer geänderten Validierungslogik als ungültig deklariert hat. Das haben wir behoben sodass vorher ausgestellte Tokens weiterhin gültig sein sollten.

Der von dir beschriebene Request wird verwendet, um einen refresh token in einen access token umzuwandeln. Das muss immer passieren wenn der access token abgelaufen ist. Hier sollte es eigentlich keine Probleme geben. Hast du hier noch einen cURL für mich damit ich nachvollziehen kann was du hier machst? Den trace mit dieser id kann ich leider nicht finden.

**Comment by wwdto** [comment]
Hier der CURL-aufruf zur obigen URL (postman)


curl -s -L -X POST 'https://api.awork.io/api/v1/accounts/token?grant_type=refresh_token&refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZjI5YmQ2Yy1iMGIyLTQ5ZjgtYjRkNy1iNzE2MjlhODMyOGQiLCJuYW1lIjoiaXRAdm9ubWVuZGUuZGUiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJpdEB2b25tZW5kZS5kZSIsIkFzcE5ldC5JZGVudGl0eS5TZWN1cml0eVN0YW1wIjoiN1NKN09VTzNBMkdEQ0tKM09DVUlDUUdQR0M2NUozUFUiLCJpaWQiOiI1ZjI5YmQ2Yy1iMGIyLTQ5ZjgtYjRkNy1iNzE2MjlhODMyOGQiLCJ3aWQiOiJhYjBlMGMzNy1mOTQxLWVjMTEtOTgxZi01MDFhYzUyN2I1OTIiLCJ1aWQiOiJhMWUwNWM3NS1jYzUxLWVjMTEtOTgxZi01MDFhYzUyN2I1OTIiLCJydGlkIjoiYTI1NmM5OGItOWM4Yi00ZGQxLWJmOTQtOGMxZjcwMjkzODM5IiwidG9rZW5fdXNhZ2UiOiJyZWZyZXNoX3Rva2VuIiwibmJmIjoxNjc4NDU4OTkxLCJleHAiOjE2ODEwNTA5OTEsImlzcyI6Imh0dHBzOi8vYXBpLmF3b3JrLmlvLyIsImF1ZCI6ImF3b3JrLmlvIn0.KdOIuP5HnaBDsMLuh2D19GHNjZDOZAWxCurobXMwua4' \
-H 'Content-Type: application/x-www-form-urlencoded' \
-H 'Authorization: Basic YWlzdm9uTWVuZGU6bnI2WnY0eFJnRFU3VmpENnJkQ0c5dFA3' \
-H 'Cookie: .AspNetCore.Antiforgery.VyLW6ORzMgk=CfDJ8AQFW8fqVFFCmEFzdj9bYeaN3oNQpnuLufp1-3PxhgxvzPI2HinxVmXJPZ6NmTo61oq8SRx0CQ56ooR3FFIM653aObOyY_CaHa44xF_cQaoeYE1AZc35j5pMxYHt1ffeWCVLIgUqCw5_C5Bzf6JuacU'

**Comment by sebastianrosch** [comment]
@wwdto Du musst hier `grant_type` und `refresh_token` als URL-encoded Body Parameter mitschicken statt sie in der URL als Query Parameter zu senden. Ich habe das in unserer Doku nochmal etwas klarer gemacht. Ich hoffe das hilft. https://developers.awork.io/authentication#authentication-resourcerequest-1

**Comment by sebastianrosch** [comment]
Hi @wwdto ich hoffe das hat dir geholfen. Ich schließe dieses Ticket. Meld dich gerne wieder falls du weitere Fragen hast.
