### ISSUE TITLE
Add New task using api?

### ISSUE THREAD

**Issue by tahirbilal1** [awork-io/awork#98]
### What is your question?

How to attachments for creating a new task in a project with attachements?

**Comment by tahirbilal1** [comment]
How to create a task with api?
As I am unable to get the taskstatusID?
Which endpoint will help to get the taskstatusID?
Also for storing files, what kind of data needed to upload there?
Base64?
And if I have multiple files then Do I need to upload one by one?

**Comment by tahirbilal1** [comment]
How to create a task with api?
As I am unable to get the taskstatusID?
Which endpoint will help to get the taskstatusID?
Also for storing files, what kind of data needed to upload there?
Base64?
And if I have multiple files then Do I need to upload one by one?

**Comment by sebastianrosch** [comment]
@tahirbilal1  You first have to create a project, then you can get the task statuses for this project as they are project specific. With this you can create a task. Then you can create a file and upload a new version with this endpoint: https://openapi.awork.io/#/EntityFiles/post__entityName___entityId__files__fileId__versions
