### ISSUE TITLE
Task Satatuses

### ISSUE THREAD

**Issue by tahirbilal1** [awork-io/awork#99]
### What is your question?

Where to get taskstatuses to create a new task?

**Comment by sebastianrosch** [comment]
Hi @tahirbilal1 please take a look at our API documentation where you can find all endpoints the awork API supports, including the task statuses for each project: https://openapi.awork.io/#/ProjectTasks/get_projects__projectId__taskstatuses

**Comment by tahirbilal1** [comment]
It is returning me whole html of some webpage

**Comment by tahirbilal1** [comment]
![image](https://user-images.githubusercontent.com/127947363/225397157-7cfa3f76-6442-4e67-b442-68e1ea69a096.png)
